---
title: "Авторы"
---

## Список статей по авторам


### А


**Абрамова Л.** (1)

- [Изучение эффективности деятельности аппарата КПСС. Мало известные страницы истории ленинградской социологии](files/article_content140481096774373file.pdf). 2013. № 4.

**Алексеев А.** (27)

- [А.Н. Алексеев. Мои пожелания и/или распоряжения](files/2017-6-07.pdf). 2017. № 6.
- [Моя жилищная история. Опыт тематически фокусированного автобиографического повествования](files/2016-5-05.pdf). 2016. № 5.
- [О мере легитимности Правителя](files/article_content1478173144142810file.pdf). 2015. № 6.
- [Историко-биографические поиски и открытия Бориса Докторова](files/article_content1476364857275833file.pdf). 2015. № 1.
- [Созидатель. По случаю 85-летия Бориса Максимовича Фирсова](files/article_content144473435137663file.pdf). 2014. № 3.
- [«Телескоп» — на марше](files/article_content1404811102113417file.pdf). 2013. № 4.
- [Многообразие экспликаций и синонимический ряд "наблюдающего   участия" (Опыт текстологического анализа, с тяготением к историко-научному)](files/article_content138130780821523file.pdf). 2012. № 6.
- [Социальный опыт, общая направленность и ценностный профиль личности](files/article_content1380213011264081file.pdf). 2012. № 4.
- [К дискуссии о соотношении «субъективного» и «объективного» в биографическом нарративе](files/article_content1380212231357946file.pdf). 2012. № 3.
- [Дискуссия через океан. Защита наблюдающего участника](files/article_content137992374928758file.pdf). 2012. № 2.
- [Два "Четвертых "Всероссийских социологических конгресса" и Социологическая ассоциация России](files/article_content1356939372119236file.pdf). 2011. № 6.
- [На стыке методологических и этических проблем (Читая Дмитрия Шалина. Продолжение диалога)](files/article_content1356939153366948file.pdf). 2011. № 5.
- [Борису Зусмановичу Докторову 70 лет — поздравляем!](files/article_content1356760939228942file.pdf) 2011. № 3.
- [30 лет "в строю" (Мое членство в КПСС)](files/article_content1356760952287504file.pdf). 2011. № 3.
- [Открытое письмо группы петербургских социологов коллегам-социологам России (июль 2007)](files/article_content1230124118295578file.pdf). 2008. № 6.
- [Память семейная и историческая: точки пересечения и разрывы (гипотеза о влиянии семейной памяти на мировосприятие)](files/article_content1255522008101292file.pdf). 2008. № 5.
- [Замечание об истории социологии "с человеческим лицом"](files/article_content1216017615146483file.pdf). 2008. № 3.
- [Письмо, дневник, автобиография: многообразие форм и сопряжение смыслов (теоретико-методологические заметки)](files/article_content122071303773076file.pdf). 2007. № 4.
- [От синкретизма – через дифференциацию – к синтезу (об эпистемологической структуре и логике развития социологического знания)](files/article_content12012582035821file.pdf). 2004. № 6.
- [Социологический комментарий к итогам выборов в Госдуму-2003](files/article_content1196672860360215file.pdf). 2004. № 1.
- [Президент третьего тысячелетия. «Желаю веселья!» (заметки о феномене талантливого патриотизма и народной любви)](files/article_content1196673144479555file.pdf). 2004. № 1.
- ["Хотели хорошего, но... не успели!"](files/article_content1194269694373333file.pdf). 2003. № 3.
- [Эстафета памяти. Ресурсы, нормы и эффекты автобиографического повествования](files/article_content1259144472190697file.pdf). 2001. № 4.
- [Письмо в редакцию: эпизод из жизни СПАС](files/2001_4_07.pdf). 2001. № 4.
- [Драматическая социология и социологическая ауторефлексия](files/article_content1225556519121396file.pdf). 2000. № 6.
- [О создании Социологического института РАН на базе Санкт-Петербургского филиала Института социологии РАН (аналитическая записка)](files/article_content1202482959491803file.pdf). 2000. № 1.
- [Новая российская газетная пресса: типологическая структура и ее изменения (1988 – 1997 гг.)](files/article_content1202497597234485file.pdf). 1999. № 1.

**Алексеев И.** (1)

- [Рок-фестиваль «Окна открой»](files/article_content1195573985365478file.pdf). 2003. № 1.

**Андреева Е.** (11)

- [Служба 77: доставка товаров на дом](files/2002_2_Andreeva.pdf). 2002. № 2.
- Рынок хрустящей продукции (сухие завтраки и закуски). 2001. № 3.
- [Встречают по фасаду... (обзор рынка фасадных красок СПб)](files/2001-1-09.pdf). 2001. № 1.
- Перспективы использования нетрадиционных строительных материалов на рынке СПб. 2000. № 5.
- Люблю я макароны (обзор рынка макаронных изделий СПб). 2000. № 4.
- Рынок недвижимости СПб: планы и предпочтения потребителей. 2000. № 1.
- Готовы ли потребители к инновациям в медицинской промышленности? 1999. № 5.
- Туристический рынок в ожидании нового сезона. 1999. № 3.
- Рынок меховых изделий СПб. 1999. № 2.
- Исследование рынка напольных покрытий. 1998. № 6.
- Обзор потребительского рынка готовых лекарственных средств СПб. 1998. № 4.

**Андрюшкина И.** (1)

- [Что волнует лидеров профсоюзов в год юбилея?](files/article_content1207062863381971file.pdf) 2005. № 6.

**Анушкова Ю.** (1)

- [Образ Петербурга глазами молодежи](files/article_content135694029335472file.pdf). 2011. № 4.

**Аргунова Е.** (1)

- [Социально-экономическое положение и самочувствие молодежи в Санкт-Петербурге](files/article_content1327333615213372file.pdf). 2010. № 2.

**Аронсон П.** (1)

- [Что русскому хорошо, то немцу смерть: русские студенты в Германии о русских и немецких нормах медицины](files/article_content1208529406388183file.pdf). 2006. № 2.

**Артемов В.** (1)

- [Социальное время: предвидение, исследовательски-прикладная и планово-управленческая практика](files/article_content125552196469224file.pdf). 2008. № 5.

**Асочаков Ю.** (2)

- [Постглобализация и новые контуры будущей современности](files/2019-1-03.pdf). 2019. № 1.
- [Будущее как предмет социологии](files/2016-3-02.pdf). 2016. № 3.

**Ачильдиев С.** (2)

- [Отклики читателей на публикацию книги «Моя жилищная история. Автобиографические очерки и биографические интервью»](files/2019-1-10.pdf). 2019. № 1.
- [Русский интеллигент: опыт литературно0социологического портрета](files/2017-5-05.pdf). 2017. № 5.

### Б


**Баденко Д.** (1)

- Оценка параметров деятельности в сфере коммерческих маршрутных пассажирских перевозок в СПб. 2002. № 6.

**Балыбердина И.** (1)

- [Симптомы кризиса и антикризисные меры на предприятиях Санкт-Петербурга](files/article_content1296914336227300file.pdf). 2009. № 3.

**Бардин В.** (1)

- [Картины мира и информационная герменевтика](files/2018-3-03.pdf). 2018. № 3.

**Батыгин Г.** (1)

- [Социальные науки как текст](files/article_content1202893707276790file.pdf). 2005. № 4.

**Бачинин В.** (4)

- [Новый цезарепапизм, панихида по демократии и наше не состоявшееся духовное возрождение](files/article_content1220712908361685file.pdf). 2008. № 1.
- [Неудачный роман социологии с государством](files/article_content1220713109472049file.pdf). 2007. № 5.
- [Что нам стоит "Содом-2" построить? Медиасреда как зеркало русской аномии](files/article_content122000647326663file.pdf). 2007. № 3.
- [Социальная работа христиан в российских тюрьмах](files/article_content1207922451148201file.pdf). 2006. № 1.

**Безгодов А.** (1)

- Бизнес и предпринимательство в зеркале свободных высказываний петербуржцев. 1999. № 1.

**Безрукова О.** (1)

- Обучение на факультете социологии университета глазами студентов. 2001. № 6.

**Бекреев А.** (1)

- [Застройщик из черного списка и банковская аккредитация](files/2017-2-05.pdf). 2017. № 2.

**Белов А.** (3)

- [Межконфессиональные особенности практической составляющей структуры религиозного жизненного мира](files/article_content1404987315451225file.pdf). 2013. № 6.
- [Переосмысление понятия «профессиональная деятельность» в современном евангельском сообществе: культурно-богословские предпосылки и современная ситуация](files/article_content1381307770361262file.pdf). 2012. № 6.
- [Культурная типология протестантских конфессий в культурно-историческом пространстве Санкт-Петербурга](files/article_content1356940470401980file.pdf). 2011. № 5.

**Белов С.** (4)

- [Имена и фамилии у Достоевского](files/article_content144731790198758file.pdf). 2014. № 6.
- [Числа у Достоевского](files/article_content144473455511102file.pdf). 2014. № 3.
- [Ф. М. Достоевский и евреи](files/article_content1356761424487790file.pdf). 2011. № 2.
- [Сайгон – это судьба](files/article_content1195573552423600file.pdf). 2003. № 1.

**Белоусов К.** (2)

- [Социологический конгресс 2014 года в Йокогаме (Япония)](files/article_content1446551250338061file.pdf). 2014. № 4.
- [Сайт Санкт-Петербургского центра девиантологии "deviantology.spb.ru"](files/article_content144473460272377file.pdf). 2014. № 3.

**Беляев Э.** (1)

- [Взгляд на биографические интервью: важность нахождения паттернов](files/article_content1356939879141238file.pdf). 2011. № 6.

**Беспалова Ю.** (5)

- [Нарративный поворот в социологии и проблема сохранения семейно-родовой памяти](files/article_content1477987265126635file.pdf). 2015. № 3.
- [Экзистенциальная парадигма в социологии и новые возможности ее применения](files/article_content1443694853124126file.pdf). 2014. № 1.
- [Западносибирская семейная кухня: социологический подход](files/article_content1381307269467835file.pdf). 2012. № 5.
- [Устойчивые выражения западносибирской семьи («семейные слова»): социологический подход](files/article_content137951921134509file.pdf). 2012. № 1.
- [Песни семьи: возможности социологического исследования](files/article_content1297505352253011file.pdf). 2009. № 5.

**Бляхер Л.** (1)

- [Социология в регионе: это как?](files/article_content1477989558225826file.pdf) 2015. № 4.

**Богданова М.** (1)

- [К 60-летию со дня рождения Батыгина Геннадия Семеновича](files/article_content1356760850220790file.pdf). 2011. № 1.

**Богомягкова Е.** (2)

- [Бороноеву Асалхану Ользоновичу 80 лет!](files/2017-3-01.pdf) 2017. № 3.
- [Новые конфигурации социального неравенства в контексте развития биотехнологий](files/2016-2-06.pdf). 2016. № 2.

**Божков О.** (39)

- [33 экспедиционных дня 2018 года (заметки с социологического поля)](files/2018-6-05.pdf). 2018. № 6.
- [XV международная научно-практическая конференция в Каргополе](files/2018-5-10.pdf). 2018. № 5.
- [Возможно ли качественное и профессиональное выполнение госзадания?](files/2018-4-03.pdf) 2018. № 4.
- [Международному симпозиуму «Пути России» 25 лет](files/2018-3-08.pdf). 2018. № 3.
- [X социологические чтения памяти В.Б. Голофаста](files/2018-3-09.pdf). 2018. № 3.
- [Куда идет современная социология?](files/2017-5-08.pdf) 2017. № 5.
- [Петербуржцы о теракте в метро 3 апреля 2017 г.](files/2017-3-08.pdf) 2017. № 3.
- [Социальные и пространственные измерения современного мегаполиса](files/2017-3-09.pdf). 2017. № 3.
- [Шестой Методологический семинар памяти Г.С. Батыгина. «Эвристический потенциал социального знания: потребности общества и возможности науки»](files/2017-3-10.pdf). 2017. № 3.
- [Не все зависит от нас, особенно жилье](files/2017-2-07.pdf). 2017. № 2.
- [Что новенького? (Обзор новых практик в экономике, политике и культуре)](files/2016-6-04.pdf). 2016. № 6.
- [Нацеленность на живой результат своего труда. Алле Александровне Русалиновой — 85](files/2016-4-01.pdf). 2016. № 4.
- [Непростая география России](files/2016-3-06.pdf). 2016. № 3.
- [Три грустных песни о том, как государство «сливало» промышленность и рабочий класс](files/2016-3-07.pdf). 2016. № 3.
- [О Всероссийских Чтениях памяти В.А. Ядова](files/2016-1-08.pdf). 2016. № 1.
- [Патриархи уходят и все ложится на нас](files/article_content1478173265205278file.pdf). 2015. № 6.
- [Социальные проблемы российского села и аграрных отношений](files/article_content1477987437323211file.pdf). 2015. № 3.
- [Об объекте и предмете социологии](files/article_content147696779050656file.pdf). 2015. № 2.
- [Эссе о прошлом и патриотизме](files/article_content1444734640234875file.pdf). 2014. № 3.
- [7-е социологические чтения памяти В.Б. Голофаста. СПб, 26-29 марта 2014 г.](files/article_content1444734692448856file.pdf) 2014. № 3.
- [Две конференции: пессимистично и немного оптимизма](files/article_content144473470356145file.pdf). 2014. № 3.
- [Откуда вышли опросы общественного мнения?](files/article_content1444125424187890file.pdf) 2014. № 2.
- [Прошло сто лет. К чему пришли?](files/article_content1444125471430753file.pdf) 2014. № 2.
- [Прошло сто лет... (о состоянии современной — не только российской — социологии)](files/article_content1404987464191542file.pdf). 2013. № 6.
- [Кому (или чему) должна служить наука?](files/article_content140481115514825file.pdf) 2013. № 4.
- [Заметки о детстве и социологии детства](files/article_content1380212991105695file.pdf). 2012. № 4.
- [Политика: отвлекающие маневры](files/article_content138021308718624file.pdf). 2012. № 4.
- [История нашей социологии — свидетельства действующих лиц](files/article_content1380212531373351file.pdf). 2012. № 3.
- [Однополые браки — проблема в основном политическая](files/article_content1379519310139357file.pdf). 2012. № 1.
- [Социология вчера, сегодня, завтра. Четвертые чтения памяти Валерия Голофаста](files/article_content1327333919182019file.pdf). 2010. № 2.
- [От юбилея до юбилея недалеко](files/article_content1297505802407351file.pdf). 2009. № 6.
- [Задача – возрождение профессионального сообщества](files/article_content1297505182406899file.pdf). 2009. № 4.
- [15 лет социологического изучения театральной жизни Ленинграда](files/article_content1235725504131794file.pdf). 2008. № 6.
- [Электронная база данных Биографического фонда: краткий анализ материалов](files/article_content1215453273491266file.pdf). 2007. № 3.
- [О важности и смысле исторических свидетельств. Рецензия на книгу Б. Докторова «Отцы –основатели: история изучения общественного мнения »](files/article_content1210867786168724file.pdf). 2006. № 5.
- [«Гляжу в себя как в зеркало эпохи» (история в документах о том, как не была допущена к печати книга «Семья в крупном городе», под редакцией В.Б. Голофаста)](files/article_content1202893457446877file.pdf). 2005. № 6.
- [Век живи, век учись…](files/article_content1201258134486193file.pdf) 2004. № 6.
- К портрету идеального кандидата в депутаты Законодательного собрания Петербурга образца 1998г. 1998. № 5.
- Реальные проблемы современной школы в восприятии учащихся и их родителей. 1997. № 2.

**Борисов Б.** (1)

- [Две зарисовки с натуры (опыт наблюдающего участия)](files/article_content1201863403437442file.pdf). 2004. № 3.

**Бочаров В.** (1)

- [Новые требования к работнику промышленного производства в условиях современной модернизации (социологический анализ)](files/article_content1477987408404132file.pdf). 2015. № 3.

**Бояркина С.** (1)

- [Аспекты институционального функционирования социального предпринимательства](files/article_content1446551092483228file.pdf). 2014. № 4.

**Боярский К.** (1)

- [Контексты эмпирического познания в социологии и возможности программы ВЕГА](files/article_content1260464166454700file.pdf). 2008. № 6.

**Браславский Р.** (1)

- [По поводу "полемических заметок" А. Щелкина](files/article_content1328103701104361file.pdf). 2010. № 5.

**Брик Т.** (1)

- [Сетевой анализ биографических интервью: возможности и ограничения](files/2017-1-06.pdf). 2017. № 1.

**Быльева Д.** (2)

- [Оценка коммуникативных качеств виртуального собеседника на основании ника и аватара](files/article_content1380212444403485file.pdf). 2012. № 3.
- [Отношение молодежной аудитории к ребрендингу компании «МТС»](files/article_content1260464350398723file.pdf). 2008. № 6.

**Быстрова А.** (1)

- [О "старой гвардии", академизме и групповых интересах](files/article_content1194855327170639file.pdf). 2003. № 2.

### В


**Васильев В.** (1)

- Рынок продуктов быстрого приготовления СПб. 1999. № 1.

**Васильев Г.** (1)

- Поколенческая трансформация политического сознания. 2002. № 6.

**Васильев И.** (3)

- [Читатели газет в Российской национальной библиотеке](files/article_content1223472097490482file.pdf). 2007. № 4.
- Население СПб – детали социально-экономического портрета. 1999. № 6.
- Запросы корпоративных потребителей на рынке персональных компьютеров в оценках руководителей предприятий, организаций и фирм Петербурга. 1997. № 1.

**Васильева Е.** (1)

- [Спецэффекты в кино: от иллюзии чуда к иллюзии реальности](files/article_content1356938872324376file.pdf). 2011. № 4.

**Вейхер А.** (4)

- [Рынок аренды нежилых помещений: некоторые данные на фоне скрытого дефицита информации](files/article_content1220006318250348file.pdf). 2007. № 3.
- [Домохозяйства Петербурга - социологическое изучение экономической  дифференциации](files/article_content1204703682425502file.pdf). 2005. № 3.
- Оценка параметров деятельности в сфере коммерческих маршрутных пассажирских перевозок в СПб. 2002. № 6.
- Население СПб – детали социально-экономического портрета. 1999. № 6.

**Вехов И.** (5)

- [Самые популярные телепрограммы 2009 года в Санкт-Петербурге](files/article_content132673186314927file.pdf). 2010. № 1.
- [Основные характеристики российской Интернет-аудитории](files/article_content1297505106238557file.pdf). 2009. № 4.
- [Аудитория телевидения: итоги и тенденции](files/article_content1296914189134529file.pdf). 2009. № 2.
- [Санкт-Петербург: особенности телесмотрения](files/article_content124547907012833file.pdf). 2008. № 2.
- [Телесмотрение жителей Санкт-Петербурга: изменения в 2006 году](files/article_content1213794653217904file.pdf). 2007. № 1.

**Вешнинский Ю.** (2)

- [Ментальные основания архаизации современной российской культуры и «выбросов архаики вверх»](files/2017-3-06.pdf). 2017. № 3.
- [Развитие градоведческой традиции И.М. Гревса в отечественной науке](files/article_content140437953156075file.pdf). 2013. № 2.

**Винер Б.** (3)

- [Приключения в поисках национальности](files/2018-4-07.pdf). 2018. № 4.
- [Развитие Социологического института РАН: решения тактические или стратегические?](files/article_content1194855627474602file.pdf) 2003. № 2.
- [Почему петербургским социологам сегодня не нужна профессиональная ассоциация](files/2001_4_06.pdf). 2001. № 4.

**Войцеховский В.** (2)

- [Особенности социальной адаптации трудового населения Ленинградской области к изменениям на рынке труда](files/article_content1196673593244701file.pdf). 2004. № 1.
- [Социокультурная среда преобразований и институализирующая роль профессионального образования в условиях изменяющегося рынка труда](files/article_content1194853383443055file.pdf). 2003. № 2.

**Волков А.** (1)

- [Реклама алкоголя в прессе](files/2001_1_Volkov.pdf). 2002. № 1.

**Волчков А.** (1)

- Анализ потребительского поведения населения СПб на рынке продовольственных товаров. 1999. № 6.

**Волчкова Л.** (3)

- [Рынок мясной продукции в Санкт-Петербурге: проблемы формирования и функционирования](files/article_content1204703916107711file.pdf). 2005. № 3.
- [Образцы семейного питания как фактор формирования социальных отношений и потребительских предпочтений на рынке продовольствия](files/2001-1-07.pdf). 2001. № 1.
- Анализ потребительского поведения населения СПб на рынке продовольственных товаров. 1999. № 6.

**Воронин А.** (2)

- [Советский человек](files/2016-2-03.pdf). 2016. № 2.
- [Сдвиги в фундаментных основаниях самосознания: я не мыслю, значит, я существую](files/article_content140437942420975file.pdf). 2013. № 2.

**Воронков В.** (1)

- [От объяснения к пониманию: в развитие дискуссии](files/article_content120063896443531file.pdf). 2004. № 5.

**Воронцов А.** (4)

- [Как петербуржцы смотрели Евро-2016](files/2016-6-06.pdf). 2016. № 6.
- [Недвижимость на локальном рынке рекламы и покупательское поведение в категории](files/2016-3-04.pdf). 2016. № 3.
- [Как петербуржцы смотрели XXII зимние Олимпийские Игры](files/article_content144655120018013file.pdf). 2014. № 4.
- [Итоги телесезона 2012-2013: что смотрят петербуржцы?](files/article_content1404986276120334file.pdf) 2013. № 5.

**Вырская М.** (1)

- [Коммуникационные сбои в стандартизованном телефонном интервью](files/2017-6-02.pdf). 2017. № 6.

**Вычик Т.** (1)

- [Петербуржцы о частной собственности на землю: идеологические штампы, политико-экономические ориентации, хозяйственные практики](files/2001_1_Rybina.pdf). 2002. № 1.

**Вьюговская Е.** (1)

- [Схемы выдвижения в стандартизированном интервью](files/article_content1380213060383346file.pdf). 2012. № 4.

### Г


**Гавра Д.** (12)

- [Нужен ли хорошему социологу внешний аудит качества?](files/article_content1327767650229652file.pdf) 2010. № 4.
- [Рецензия на книгу: Головин Н.А. «Теоретико-методологические основы исследования политической социализации»](files/article_content1207921373183270file.pdf). 2006. № 1.
- Досуговые практики Санкт-Петербургской элиты. 2001. № 6.
- Политическая толерантность жителей Санкт-Петербурга. 2001. № 5.
- Политическое сознание пожилых петербуржцев: опровержение стереотипа единообразия. 2000. № 5.
- Петербуржец как дачник и огородник – штрихи к портрету владельцев загородной недвижимости. 2000. № 3.
- Кто решит судьбу думских выборов в СПб? Эскиз портрета потенциального электората. 1999. № 5.
- Ю. Лужков и В. Яковлев: социальные позиции в СПб, сравнительный анализ. 1999. № 4.
- Готовность к насилию в Санкт-Петербурге. 1999. № 2.
- Сторонники и противники губернатора Санкт-Петербурга В. Яковлева: наброски социальных портретов. 1998. № 5.
- Конец 1997 г.: позиции губернатора СПб достаточно устойчивы. 1998. № 1.
- Жилищно-коммунальная реформа в общественном мнении петербуржцев. 1997. № 5.

**Галицкая Е.** (1)

- [Социография: инновационная аналитическая стратегия](files/article_content1327333739127963file.pdf). 2010. № 2.

**Галицкий Е.** (1)

- [Социография: инновационная аналитическая стратегия](files/article_content1327333739127963file.pdf). 2010. № 2.

**Ганскау Е.** (3)

- [Рынок мясной продукции в Санкт-Петербурге: проблемы формирования и функционирования](files/article_content1204703916107711file.pdf). 2005. № 3.
- [Образцы семейного питания как фактор формирования социальных отношений и потребительских предпочтений на рынке продовольствия](files/2001-1-07.pdf). 2001. № 1.
- Анализ потребительского поведения населения СПб на рынке продовольственных товаров. 1999. № 6.

**Гегер А.** (2)

- [Проблема изучения ценностных ориентаций: поворот к микс-методам](files/article_content147798728531286file.pdf). 2015. № 3.
- [Потенциал технологии открытых вопросов в выявлении индивидуальных и групповых ценностей](files/article_content14049861893691file.pdf). 2013. № 5.

**Гегер С.** (1)

- [Проблема изучения ценностных ориентаций: поворот к микс-методам](files/article_content147798728531286file.pdf). 2015. № 3.

**Герасимова Е.** (1)

- Массовое жилищное строительство и изменения в повседневной жизни горожан. 1998. № 3.

**Герасимчук Ю.** (1)

- [Кризис как фактор роста](files/article_content1296914315433398file.pdf). 2009. № 3.

**Гилинский Я.** (3)

- [Преступность как повседневность](files/2019-1-04.pdf). 2019. № 1.
- [О главных противоречиях и главных проблемах общества постмодерна](files/2018-5-04.pdf). 2018. № 5.
- [Человеческое, слишком человеческое. Human, toohuman](files/2018-3-02.pdf). 2018. № 3.

**Гладарев Б.** (3)

- [Условия службы и социальное положение рядовых сотрудников милиции: социологический очерк к юбилею](files/article_content1234351469236759file.pdf). 2008. № 1.
- [Информационно-коммуникационные технологии – между автономией и контролем](files/article_content1207921652207629file.pdf). 2006. № 1.
- [Повседневное пользование информационно-коммуникационными технологиями](files/article_content1200638785329094file.pdf). 2004. № 5.

**Глазова Л.** (1)

- [Тайное оружие PR-специалистов fashion-рынка (обзор популярных PR-инструментов на примере анализа информационной активности джинсовых брендов)](files/article_content1380212509328124file.pdf). 2012. № 3.

**Глотов М.** (2)

- [V Голофастовские чтения](files/article_content1356760152330860file.pdf). 2011. № 3.
- [Адаптация иногородних студентов к культуре Санкт-Петербурга](files/article_content1209135793417793file.pdf). 2006. № 3.

**Головин Н.** (1)

- [Вызовы индивидуализации](files/2019-1-09.pdf). 2019. № 1.

**Голод С.** (1)

- [О "старой гвардии", академизме и групповых интересах](files/article_content1194855327170639file.pdf). 2003. № 2.

**Голофаст В.** (9)

- [Размышления о культуре](files/article_content1296913788318891file.pdf). 2009. № 2.
- [Социально-культурные аспекты перестройки](files/article_content1218781130367904file.pdf). 2007. № 2.
- [Мегамашины и повседневность](files/article_content1190618489488146file.pdf). 2005. № 1.
- [Глобализация и место морали](files/article_content1190618295315877file.pdf). 2004. № 2.
- [Гибридизация и культурные смеси](files/article_content1190100709279505file.pdf). 2003. № 3.
- [Разновидности экономики и экономизм](files/article_content1259859719189632file.pdf). 2002. № 6.
- [Электронная среда или новые пещерные люди](files/article_content1207925582292684file.pdf). 2002. № 2.
- [Глобальное и локальное как контексты и как контрасты](files/article_content1207925519320603file.pdf). 2002. № 1.
- [Люди и вещи. Заметки о социально-культурных изменениях](files/article_content1190099701387286file.pdf). 2000. № 5.

**Голубева У.** (1)

- [Ненужная информация или дополнительные знания? Тестирование персонала – «За» и «Против»](files/article_content1198083903142382file.pdf). 2004. № 3.

**Голумеев Д.** (2)

- [Рынок пельменей в Санкт-Петербурге](files/article_content1195574351396488file.pdf). 2003. № 1.
- Рынок пельменей в Санкт-Петербурге. 2001. № 5.

**Гольберт В.** (1)

- [Инновационная маркетизация общества: российский вариант](files/article_content1234351327197017file.pdf). 2008. № 1.

**Гольбрайх В.** (1)

- [Почему произошел «сибирский Чернобыль»? Авария на Саяно-Шушенской ГЭС в российской блогосфере](files/article_content1356940146165846file.pdf). 2011. № 6.

**Гопкало О.** (1)

- [Символическое потребление на рынке труда](files/article_content1196673434371409file.pdf). 2004. № 1.

**Горлина К.** (1)

- [Симптомы кризиса и антикризисные меры на предприятиях Санкт-Петербурга](files/article_content1296914336227300file.pdf). 2009. № 3.

**Горный М.** (7)

- [Гражданское общество в Санкт-Петербурге с 2012 г. до осени 2017 г.](files/2018-1-04.pdf) 2018. № 1.
- [Гражданское общество в Санкт-Петербурге: взаимодействие с властями после дефолта 1998 г. до «закручивания гаек» (до 2013 г.).](files/2017-6-03.pdf) 2017. № 6.
- [Гражданское общество в Санкт-Петербурге: становление и развитие коалиций некоммерческих организаций до 1998 г.](files/2017-5-03.pdf) 2017. № 5.
- [Возвращение городу первоначального названия Санкт-Петербург](files/article_content1478172189196126file.pdf). 2015. № 5.
- [«Ленсовету-21» — 25 лет](files/article_content1477987371293798file.pdf). 2015. № 3.
- [Взаимоотношения институтов гражданского общества и органов власти на примере Санкт-Петербурга в начале XXI века](files/article_content144369492134491file.pdf). 2014. № 1.
- [Общественные консультативные структуры при органах власти: опыт Санкт-Петербурга](files/article_content1356761233457816file.pdf). 2011. № 2.

**Городков О.** (1)

- [Книга в жизни петербуржцев](files/2017-2-06.pdf). 2017. № 2.

**Горохов В.** (1)

- [Записки дилетанта](files/article_content129691422038434file.pdf). 2009. № 2.

**Горячева Н.** (1)

- Исследование алкогольного рынка СПб. 2000. № 5.

**Готлиб А.** (2)

- [Собственным голосом: опыт социолого-поэтического освоения нарративов](files/article_content1478173105176319file.pdf). 2015. № 6.
- [Качественная методология, исторический нарратив или можно ли написать историю советской социологии «с человеческим лицом»](files/article_content1379519171284216file.pdf). 2012. № 1.

**Гофман А.** (1)

- [Несколько слов о Леониде Александровиче Седове](files/2018-5-03.pdf). 2018. № 5.

**Григорьев В.** (2)

- [Гендерный порядок в современной России](files/article_content1297505138385681file.pdf). 2009. № 4.
- [Социолог в обществе](files/article_content1210867708271464file.pdf). 2006. № 5.

**Григорьев С.** (1)

- [Упоминания высочайших особ как товар (по материалам придворной цензуры)](files/article_content120913543528422file.pdf). 2006. № 3.

**Григорьева И.** (1)

- [Старение населения, пенсионная реформа и прочие кризисы российской жизни](files/article_content1404378603143913file.pdf). 2013. № 1.

**Грушин Б.** (1)

- [Воспоминания о Якове Самуиловиче Капелюше (1937-1990)](files/article_content1202893665366675file.pdf). 2005. № 2.

**Губа К.** (1)

- [Коммуникативная структура локального академического сообщества: роль внутренних интеллектуальных ресурсов](files/article_content1326731975267724file.pdf). 2010. № 1.

**Гуревич Л.** (1)

- [Способна ли казахстанская социология выйти за рамки провинциальной эмпирики?](files/2018-4-02.pdf) 2018. № 4.

**Гуревич Ю.** (1)

- [Как мы находим дорогу?](files/2018-6-04.pdf) 2018. № 6.

**Гусман Л.** (1)

- [Рецензия на книгу Веременко В. А. "Дворянская семья и государственная политика России (вторая половина XIX - начало XX вв.)"](files/article_content1230370266395065file.pdf). 2007. № 6.

**Гуца А.** (2)

- Духовность общества и качество жизни. 2002. № 4.
- [К вопросу о создания интегрированной системы информационно-аналитического обеспечения деятельности администрации Санкт-Петербурга](files/2001-1-10.pdf). 2001. № 1.

### Д


**Давыдов А.** (1)

- [Партийная принадлежность президентов США, 1852-2016: анализ и прогнозирование](files/2017-3-03.pdf). 2017. № 3.

**Дадали Н.** (2)

- [Петербург читающий](files/article_content1226750595425621file.pdf). 2007. № 5.
- [Чтение подростков Санкт-Петербурга](files/article_content1194854402451778file.pdf). 2003. № 2.

**Дамберг С.** (3)

- [О прагматике российских социологических исследований](files/article_content1209135309184694file.pdf). 2006. № 3.
- [Многонациональный Петербург. История. Религия. Народы](files/article_content1196672208460831file.pdf). 2003. № 3.
- [Петербуржцы о частной собственности на землю: идеологические штампы, политико-экономические ориентации, хозяйственные практики](files/2001_1_Rybina.pdf). 2002. № 1.

**Даугавет Д.** (3)

- [Рынок аренды нежилых помещений: некоторые данные на фоне скрытого дефицита информации](files/article_content1220006318250348file.pdf). 2007. № 3.
- [Грозит ли монополизация розничному рынку продовольствия?](files/article_content12187806391600file.pdf) 2007. № 2.
- Оценка параметров деятельности в сфере коммерческих маршрутных пассажирских перевозок в СПб. 2002. № 6.

**Девит М.** (1)

- [Тетрасоциология как социальная теория и практика для 21 века: строительство культуры мира из естественного порядка социальной гармонии. Рецензия на книги Л.М. Семашко](files/article_content1208530308416129file.pdf). 2006. № 2.

**Демина Н.** (3)

- [Тестирование мертоновской концепции этоса науки: случай академика Виталия Гинзбурга](files/article_content129750556767442file.pdf). 2009. № 6.
- [Этос российской философии 2002-2008 гг.: контент-анализ некрологов и юбилейных статей](files/article_content129620860498808file.pdf). 2009. № 1.
- [Этос науки в перспективе В. Голофаста](files/article_content1250571042244216file.pdf). 2008. № 4.

**Дивисенко К.** (16)

- [Посещаемость сайта журнала «Телескоп» в 2018 году](files/2019-1-07.pdf). 2019. № 1.
- [Апробация краткой версии методики «Религиозный копинг» (Brief RCOPE)](files/2018-5-05.pdf). 2018. № 5.
- [Сайта журнала «Телескоп» в 2017 году](files/2018-1-06.pdf). 2018. № 1.
- [Посещаемость сайта журнала «Телескоп» в 2016 году](files/2017-1-08.pdf). 2017. № 1.
- [Сайт журнала «Телескоп» в 2015 году: аудитория и статистика посещений](files/2016-1-06.pdf). 2016. № 1.
- [Интернет-аудитория сайта журнала "Телескоп" в 2014 году](files/article_content1476365191444360file.pdf). 2015. № 1.
- [Сайт журнала "Телескоп" в 2013 году](files/article_content1443694983493587file.pdf). 2014. № 1.
- [Межконфессиональные особенности практической составляющей структуры религиозного жизненного мира](files/article_content1404987315451225file.pdf). 2013. № 6.
- [Сайт журнала "Телескоп" в 2012 году: статистика посещений](files/article_content1404811365488347file.pdf). 2013. № 1.
- [Журналу «Телескоп» — 15 лет!](files/article_content1379519393195725file.pdf) 2012. № 1.
- [Интернет-аудитория журнала "Телескоп" в 2010 году](files/article_content1356760518465711file.pdf). 2011. № 1.
- [Сайт журнала «Телескоп» в 2009 году](files/article_content1326731765109907file.pdf). 2010. № 1.
- [Биографическое исследование жизненного мира](files/article_content1297505374260527file.pdf). 2009. № 5.
- [«Телескоп» в сети Internet: статистика посещений сайта журнала](files/article_content129621039016508file.pdf). 2009. № 1.
- [Представления о будущей семейной жизни в биографических текстах школьников](files/article_content1255522214378890file.pdf). 2008. № 5.
- [Электронная база данных Биографического фонда: краткий анализ материалов](files/article_content1215453273491266file.pdf). 2007. № 3.

**Дмитревская Н.** (2)

- [Санкт-Петербург: в поисках горожанина](files/article_content1190100199461532file.pdf). 2001. № 3.
- Образ города: эссе к проблеме синтеза наук. 1998. № 6.

**Дмитриевский В.** (2)

- [Художник и власть на сломе эпох. (Режиссер Марк Захаров и другие)](files/article_content1380212352415329file.pdf). 2012. № 3.
- [Н. Акимов и Г. Товстоногов: взаимоотношения художника и власти](files/article_content1356940388268871file.pdf). 2011. № 6.

**Добрин В.** (5)

- Рынок недвижимости СПб: планы и предпочтения потребителей. 2000. № 1.
- Готовы ли потребители к инновациям в медицинской промышленности? 1999. № 5.
- Туристический рынок в ожидании нового сезона. 1999. № 3.
- Рынок меховых изделий СПб. 1999. № 2.
- Обзор потребительского рынка готовых лекарственных средств СПб. 1998. № 4.

**Докторов Б.** (82)

- [О биографичности социологического творчества. Поиски методологии и опыт анализа](files/2019-1-06.pdf). 2019. № 1.
- [Леонид Кесельман: человек и явление. К 75-летию со дня рождения](files/2019-1-08.pdf). 2019. № 1.
- [Нариман Аитов. Основатель социологии в Башкортостане](files/2018-6-01.pdf). 2018. № 6.
- [Уникальное историко-биографическое наследие А.Н. Алексеева](files/2018-5-09.pdf). 2018. № 5.
- [Юло Вооглайд: социолог, политик, гражданин](files/2018-4-04.pdf). 2018. № 4.
- [Валерий Голофаст: «...И чудо сделал я». Стихи, хокку](files/2018-3-10.pdf). 2018. № 3.
- [Григорьева Е.И., Ситдиков И.М. Электронные издания. Технология подготовки: учебное пособие для бакалавриата и специалиста.](files/2018-3-11.pdf) 2018. № 3.
- [Разговоры с Валерием Голофастом: мысленные и реальные](files/2018-2-01.pdf). 2018. № 2.
- [Джордж Гэллап как российский социокультурный феномен](files/2018-2-06.pdf). 2018. № 2.
- [Из прошлого ленинградской социологии](files/2018-1-10.pdf). 2018. № 1.
- [Три мониторинга президентских избирательных кампаний: 2008, 2012 и 2016 годы. Технология. Главный историко-научный вывод](files/2017-3-04.pdf). 2017. № 3.
- [История науки присваивает себе право, в котором люди отказывают богам: она меняет прошлое](files/2017-1-04.pdf). 2017. № 1.
- [О сделанном и перспективах ](files/2016-6-03.pdf). 2016. № 6.
- [О жизнестойкости «Ленинградской социологической школы». Олегу Борисовичу Божкову — 75](files/2016-4-02.pdf). 2016. № 4.
- [И это все вместила одна жизнь ](files/2016-4-03.pdf). 2016. № 4.
- [И это все вместила одна жизнь](files/2016-3-01.pdf). 2016. № 3.
- [Я стою на берегу информационного океана](files/2016-1-02.pdf). 2016. № 1.
- [История есть, если только она написана-2. После дороги продолжительностью в 11 лет](files/article_content1478172144344631file.pdf). 2015. № 5.
- [Мир Владимира Александровича Ядова. По страницам журнала «Телескоп»](files/article_content1477989840442348file.pdf). 2015. № 4.
- [О «загадочности Шереги»](files/article_content1447317636281765file.pdf). 2014. № 6.
- [Истинное творчество только и может быть биографичным. К 80-летию Жана Терентьевича Тощенко](files/article_content1447317663255815file.pdf). 2014. № 6.
- [Ориентир — классика. Без алармизма об очень важном](files/article_content1447317978157228file.pdf). 2014. № 6.
- [«Социологи России». Книга новая, необходимая, но трудно доступная](files/article_content1446551567420025file.pdf). 2014. № 4.
- [Созидатель. По случаю 85-летия Бориса Максимовича Фирсова](files/article_content144473435137663file.pdf). 2014. № 3.
- [«Обращение к себе» и множество вопросов к себе](files/article_content1444736541221270file.pdf). 2014. № 3.
- [Почему в 2012 году организация Гэллапа не предсказала победу Барака Обамы?](files/article_content1443694895267727file.pdf) 2014. № 1.
- [Аскольд Кузьминский: его творчество знакомо миллионам, его имя знают немногие](files/article_content1404987408155498file.pdf). 2013. № 6.
- [«Телескоп»: праздник, который всегда во мне](files/article_content140481111112321file.pdf). 2013. № 4.
- [А.Г. Здравомыслов: его деятельность и наследие еще предстоит изучить. К 85-летию со дня рождения](files/article_content1404379381266300file.pdf). 2013. № 2.
- [13 ключей к Белому дому Алана Лихтмана. По следам мониторинга президентских выборов в США 2012 года](files/article_content140437858080708file.pdf). 2013. № 1.
- [Президентские выборы в США 2012 года. Социологические заметки](files/article_content138130752198401file.pdf). 2012. № 6.
- [Генеалогия четырех первых поколений советских/российских социологов](files/article_content1381307087129266file.pdf). 2012. № 5.
- [Борис Раббот и страницы истории, которые нам еще предстоит узнать](files/article_content1381307398366301file.pdf). 2012. № 5.
- [К семилетию рубрики «Современная история российской социологии»](files/article_content1356939805257404file.pdf). 2011. № 5.
- [Игорь Кон. Из переписки](files/article_content1356760697151527file.pdf). 2011. № 3.
- [К 60-летию со дня рождения Батыгина Геннадия Семеновича](files/article_content1356760850220790file.pdf). 2011. № 1.
- [Есть ли душа Петербурга в «Ленинградской социологической школе»?](files/article_content1328194692116213file.pdf) 2010. № 6.
- [Правый поворот на красный свет светофора](files/article_content1328194841245820file.pdf). 2010. № 6.
- [Борис Грушин: начало постбиографии](files/article_content1328103922294913file.pdf). 2010. № 5.
- [Биография и судьба](files/article_content1327767619127252file.pdf). 2010. № 4.
- [Юрий Левада. Портрет для потомков. В связи с выходом книги «Воспоминания и дискуссии о Юрии Александровиче Леваде»](files/article_content1327768603125548file.pdf). 2010. № 4.
- [Как это было — 5. Кто перевел книгу У. Гуда и П. Хатта? И другое](files/article_content1327508955292328file.pdf). 2010. № 3.
- [Борис Грушин. Человек идеалов и идей](files/article_content132733354967512file.pdf). 2010. № 2.
- [Как это было. Решение задачи с 42 неизвестными](files/article_content1326732435298183file.pdf). 2010. № 1.
- [Пессимист по наблюдениям и оптимист по убеждениям. Научные и нравственные основы "драматической социологии"](files/article_content1297504348133098file.pdf). 2009. № 4.
- [Что произошло в Нью-Гэмпшире?](files/article_content1297504919189312file.pdf) 2009. № 4.
- [«Телескоп» смотрит в прошлое. Беседа об изучении истории современной российской социологии](files/article_content1296208499123748file.pdf). 2009. № 1.
- [Открытое письмо группы петербургских социологов коллегам-социологам России (июль 2007)](files/article_content1230124118295578file.pdf). 2008. № 6.
- [Как это было — 3. Об анатомии коллективного действия](files/article_content1230123535264416file.pdf). 2008. № 6.
- [Мониторинг президентской избирательной кампании 2008 года в США. Общие вопросы и первые результаты](files/article_content1260464242168155file.pdf). 2008. № 6.
- [Полвека служения социологии. Андрею Григорьевичу Здравомыслову – 80 лет](files/article_content123194477735911file.pdf). 2008. № 4.
- [Биография — это рассказ о прошедшем, но написанный сегодня](files/article_content1250570983204393file.pdf). 2008. № 4.
- [Разговоры через океан: о поколениях отечественных социологов на протяжении полувека](files/article_content121601777511087file.pdf). 2008. № 3.
- [Валерий Голофаст. Фрагменты истории российской социологии как истории с "человеческим лицом"](files/article_content1208530346289952file.pdf). 2008. № 2.
- [Галина Старовойтова. Фрагменты истории российской социологии как истории с "человеческим лицом"](files/article_content1230371054493134file.pdf). 2007. № 6.
- [Наука приходит в рекламное агентство](files/article_content1230370016234053file.pdf). 2007. № 6.
- [Клод Хопкинс. Научная реклама](files/article_content1220006429146848file.pdf). 2007. № 3.
- [Учителя и учителя учителей. К построению траектории преемственности](files/article_content1218780823163295file.pdf). 2007. № 2.
- [Биографии для истории](files/article_content1213796252400955file.pdf). 2007. № 1.
- [Джон Уонамейкер и Джон Пауэрс. Начало многих дорог](files/article_content1211646268223812file.pdf). 2006. № 6.
- [Дэвид Огилви: рекламист на все времена](files/article_content1209827280110033file.pdf). 2006. № 4.
- [Рекламист в Америке – больше чем рекламист](files/article_content1208529504390814file.pdf). 2006. № 2.
- [Оцифрованные голоса поколений](files/article_content120792124560587file.pdf). 2006. № 1.
- [Как это было – 2. Анатомия закрытия](files/article_content1203348535107750file.pdf). 2005. № 6.
- [Альберт Ласкер: « я – всего лишь апостол очевидности»](files/article_content1207062956338077file.pdf). 2005. № 6.
- [Реклама должна продавать](files/article_content1205342942379773file.pdf). 2005. № 5.
- [Воспоминания о Якове Самуиловиче Капелюше (1937-1990)](files/article_content1202893665366675file.pdf). 2005. № 2.
- [История есть, только если она написана](files/article_content1200639339303032file.pdf). 2004. № 5.
- [Б. А. Грушин. Четыре десятилетия изучения российского общественного мнения](files/article_content1198483131163958file.pdf). 2004. № 4.
- [Элмо Роупер: исследователь рынка, поллстер, общественный деятель](files/article_content1198084439274710file.pdf). 2004. № 3.
- [Арчибальд Кросли – первый в изучении радиоаудитории и общественного мнения](files/article_content1196675704479520file.pdf). 2004. № 1.
- [Хедли Кэнтрил: исследователь общественного мнения и консультант президента Рузвельта](files/article_content1192622057159644file.pdf). 2003. № 6.
- [Сентябрьский звонок](files/article_content1192623012112843file.pdf). 2003. № 6.
- [Из XVII столетия в наступивший век: к становления пост-гэллаповских опросных технологий](files/article_content1194854593310773file.pdf). 2003. № 2.
- [Эмиль Хурья – волшебник политического анализа](files/article_content1257325794458470file.pdf). 2002. № 5.
- Начало 2000-х: отношение петербуржцев к Америке (США). 2002. № 3.
- [Геллаповское наследие: прошлое и настоящее одного из наиболее известных социологических индексов. Статья вторая](files/article_content1257325305250693file.pdf). 2002. № 1.
- [Гэллаповское наследие: прошлое и настоящее одного из наиболее известных социологических индексов. Статья первая](files/article_content1257325281213799file.pdf). 2001. № 6.
- [Они сильнее других хотели знать, как работает реклама (Из истории становления исследований рынка в Америке)](files/article_content1259144351374472file.pdf). 2001. № 4.
- [Джордж Гэллап: «Мне всегда нравилось изучение рекламы»](files/article_content1257324392226875file.pdf). 2000. № 6.
- [Дж. Гэллап - наш современник: к 100 летию со дня рождения](files/article_content1257324236203949file.pdf). 2000. № 2.
- Социология на российском Интернете: в начале долгого пути. 1999. № 6.

**Докучаева И.** (1)

- [Санкт-Петербургская ассоциация социологов в цифрах](files/article_content1194270079308338file.pdf). 2003. № 3.

**Долинина М.** (1)

- [О книге Дженнифер Хиллман «Сексуальность и старение»](files/2016-6-08.pdf). 2016. № 6.

**Доровская Н.** (2)

- [Психологические трудности в работе интервьюеров социологических колл-центров (cati) и способы их преодоления](files/2018-6-03.pdf). 2018. № 6.
- [Массовое высшее образование, или я б в рабочие пошел... Рефератный бизнес: деньги и этика](files/article_content1328103520495931file.pdf). 2010. № 5.

**Дорогостайский В.** (1)

- [Использование и возможности развития информационных коммуникационных технологий в компаниях Санкт-Петербурга](files/article_content1193063236494200file.pdf). 2003. № 5.

**Древаль И.** (1)

- [Актуальные проблемы реформы государственной власти](files/2002_2_Kluev.pdf). 2002. № 2.

**Дружинин А.** (1)

- [Дискуссии о гражданском оружии: между наукой и медиакоммуникациями](files/2018-2-05.pdf). 2018. № 2.

**Дудченко В.** (2)

- [Прогноз социальных реакций на планируемое социальное изменение и прикладные аспекты позиции исследователя](files/article_content1204705509306879file.pdf). 2005. № 3.
- [Авангард шахтерского движения на финише преобразования отрасли](files/article_content1203675156473872file.pdf). 2005. № 1.

**Дука А.** (1)

- [О "старой гвардии", академизме и групповых интересах](files/article_content1194855327170639file.pdf). 2003. № 2.

**Дуков Е.** (7)

- [Урбанизация и новая художественная культура](files/2018-4-06.pdf). 2018. № 4.
- [Урбанизация и искусство](files/2016-5-03.pdf). 2016. № 5.
- [Киберпространство артефактов](files/article_content1478173064141768file.pdf). 2015. № 6.
- [Компьютер и дивидуум](files/article_content144731775757533file.pdf). 2014. № 6.
- [Компьютер и человек](files/article_content1404810928367414file.pdf). 2013. № 4.
- [Новые размышления о публике](files/article_content1380212325370515file.pdf). 2012. № 3.
- [Зрелище как социальный феномен](files/article_content1327509073440309file.pdf). 2010. № 3.

**Дунаевская Д.** (1)

- [«Петербуржцы» и «ленинградцы» в культурном пространстве города](files/article_content1204299118218600file.pdf). 2005. № 2.

**Духовный М.** (1)

- Контент – анализ предвыборных обещаний кандидатов в депутаты в органы местного самоуправления. 1997. № 6.

### Е


**Евдокимова Е.** (2)

- Варианты экономического поведения и социально-психологическая адаптация групп населения Санкт-Петербурга, связанных с оборонным комплексом. 2002. № 6.
- Долг петербуржцев за жилье продолжает расти. Кто виноват и что делать? 2000. № 3.

**Евсикова Е.** (1)

- [Прошлое через призму настоящего. VIII социологические чтения памяти В.Б. Голофаста](files/article_content1476364882122032file.pdf). 2015. № 1.

**Евсикова И.** (2)

- Рынок хрустящей продукции (сухие завтраки и закуски). 2001. № 3.
- Люблю я макароны (обзор рынка макаронных изделий СПб). 2000. № 4.

**Евстигнеев Ю.** (1)

- [Многонациональный Петербург. История. Религия. Народы](files/article_content1196672208460831file.pdf). 2003. № 3.

**Ежов С.** (1)

- [Обучение в высшем учебном заведении глазами современного студента: на примере Технологического института](files/article_content138130767010256file.pdf). 2012. № 6.

**Еремичева Г.** (3)

- [Социальное неравенство - проблема интегрирующейся Европы](files/article_content1246550326348216file.pdf). 2008. № 3.
- [Последнее собрание СПАС глазами очевидца](files/article_content1194270532249656file.pdf). 2003. № 3.
- Варианты экономического поведения и социально-психологическая адаптация групп населения Санкт-Петербурга, связанных с оборонным комплексом. 2002. № 6.

**Еремичева Н.** (1)

- [Дискаунтеры - это мода или будущее розничной торговли?](files/2001_4_03.pdf) 2001. № 4.

### Ж


**Желнина А.** (3)

- [Обзор новых книг для социологов](files/article_content1213795766256867file.pdf). 2007. № 1.
- [Обзор новых книг для социологов](files/article_content1207924301450246file.pdf). 2006. № 6.
- [Образ города и визуальные методы социологического исследования](files/article_content1201257414203593file.pdf). 2004. № 6.

**Жигулин В.** (1)

- [Реклама алкоголя в прессе](files/2001_1_Volkov.pdf). 2002. № 1.

**Жирнов В.** (1)

- [Мировой мировоззренческий кризис](files/article_content129691428633018file.pdf). 2009. № 3.

**Жудина Н.** (1)

- [Петербургские ресурсы интернет: эффективность, востребованность, запросы пользователей](files/2001-1-03.pdf). 2001. № 1.

### З


**Загребина А.** (1)

- [Опыт исследования экономического поведения в сфере пенсионного обеспечения и межпоколенческих трансфертов на примере семей петербургских студентов](files/article_content1327509217125453file.pdf). 2010. № 3.

**Задорин И.** (2)

- [Исследование информационной культуры и профессиональной коммуникации в социологическом сообществе ](files/article_content1404810013281844file.pdf). 2013. № 3.
- [Нужен ли хорошему социологу внешний аудит качества?](files/article_content1327767650229652file.pdf) 2010. № 4.

**Зарайская Е.** (1)

- [Обзор рынка шоколадных изделий в плитках в Петербурге](files/article_content119808403390484file.pdf). 2004. № 3.

**Зарин М.** (1)

- [Социальная революция под музыку рингтонов](files/article_content1220006574357129file.pdf). 2007. № 3.

**Захаров Ю.** (2)

- Духовность общества и качество жизни. 2002. № 4.
- [К вопросу о создания интегрированной системы информационно-аналитического обеспечения деятельности администрации Санкт-Петербурга](files/2001-1-10.pdf). 2001. № 1.

**Звоновский В.** (2)

- [Самоидентификация пользователей в онлайн-пространстве. Виртуальные личности](files/article_content1477989633124273file.pdf). 2015. № 4.
- [Материальный достаток как фактор самоидентификации профессиональной принадлежности российского врача](files/article_content1476364718428205file.pdf). 2015. № 1.

**Здравомыслова А.** (1)

- [Записки о нашем детстве: из воспоминаний А.Г.Здравомысловой](files/article_content1404810859329164file.pdf). 2013. № 4.

**Земнухова Л.** (1)

- [Летняя школа факультета политических наук и социологии Европейского университета в Санкт-Петербурге «Университет без Профессоров» как новый образовательный формат](files/article_content1446720780288227file.pdf). 2014. № 5.

**Зимогорова И.** (1)

- [Проблемы профориентационной деятельности в образовательных учреждениях Санкт-Петербурга](files/article_content121379476866644file.pdf). 2007. № 1.

### И


**Иванов А.** (1)

- [О задачах культурной политики в современном обществе](files/article_content119808337243398file.pdf). 2004. № 3.

**Иванов Д.** (7)

- [От глобализации к постглобализации: анклавы дополненной современности и перспективы социального развития](files/2019-1-02.pdf). 2019. № 1.
- [Будущее как предмет социологии](files/2016-3-02.pdf). 2016. № 3.
- [Новые конфигурации неравенства: анклавы глобальности и структуры глэм-капитализма](files/article_content1477989585438534file.pdf). 2015. № 4.
- [Эволюция социологии и эволюционное метатеоретизирование](files/article_content1404810898464599file.pdf). 2013. № 4.
- [Глэм-капитализм: логика сверхновой экономики](files/article_content1356939612241411file.pdf). 2011. № 5.
- [В режиме гламура. Общество и социальные науки начала века](files/article_content1220006185873file.pdf). 2007. № 3.
- [Эволюция концепции глобализации](files/article_content1261130754388117file.pdf). 2002. № 4.

**Иванов О.** (1)

- [Социальное пространство России вчера, сегодня и завтра (штрихи к портрету)](files/2017-6-04.pdf). 2017. № 6.

**Игнатова С.** (2)

- [Две конференции: пессимистично и немного оптимизма](files/article_content144473470356145file.pdf). 2014. № 3.
- Варианты экономического поведения и социально-психологическая адаптация групп населения Санкт-Петербурга, связанных с оборонным комплексом. 2002. № 6.

**Илеуова Г.** (1)

- [Восприятие населением Казахстана ситуации в сфере культуры](files/article_content1356761332491740file.pdf). 2011. № 2.

**Илле А.** (7)

- [Футбольные фанаты в поле политики](files/2018-3-06.pdf). 2018. № 3.
- [«Околофутбола»](files/article_content1443695026192398file.pdf). 2014. № 1.
- Российские консерваторы – кто они? 2002. № 6.
- Выборы в Государственную Думу-99 на страницах петербургских СМИ. 1999. № 5.
- Рейтинг продаж книг, аудио, видеокассет, компакт-дисков. 1998. № 6.
- Контент-анализ художественных фильмов, демонстритуемых на общероссийских каналах. 1998. № 2.
- Тематический анализ программ телеканалов. 1997. № 5.

**Илле М.** (39)

- [Образ «идеального» петербуржца и культурная жизнь города](files/2017-4-04.pdf). 2017. № 4.
- [Журналу «Телескоп» 20 лет!](files/2017-1-02.pdf) 2017. № 1.
- [Участие жителей «культурной столицы» в культурной жизни Петербурга](files/2016-5-04.pdf). 2016. № 5.
- [Неравенство как ценность в культуре](files/2016-1-07.pdf). 2016. № 1.
- [Мир Владимира Александровича Ядова. По страницам журнала «Телескоп»](files/article_content1477989840442348file.pdf). 2015. № 4.
- [Образ петербуржца в массовом сознании горожан](files/article_content1477987334259708file.pdf). 2015. № 3.
- [Интересы и информационные потребности жителей Петербурга в области истории и культуры города](files/article_content144672073735357file.pdf). 2014. № 5.
- [Юбилейный номер журнала "Телескоп"](files/article_content1404811085136819file.pdf). 2013. № 4.
- [О развлечении в искусстве, демократии и культуре ](files/article_content1404810043428630file.pdf). 2013. № 3.
- [Список ВАК: элитарный журнальный клуб или профанация качества научных публикаций?](files/article_content140437964857056file.pdf) 2013. № 2.
- [Петербургская аудитория концертов музыки академических жанров](files/article_content137992386498194file.pdf). 2012. № 2.
- [Журналу «Телескоп» — 15 лет!](files/article_content1379519393195725file.pdf) 2012. № 1.
- [Кинотеатр в культурном пространстве Санкт-Петербурга](files/article_content1356760283380687file.pdf). 2011. № 2.
- [О литературе массовой и классической. Или так ли уж страшен черт, как его малюют?](files/article_content1328103598205340file.pdf) 2010. № 5.
- [Библиотеки в культурном пространстве Санкт-Петербурга](files/article_content1327509134232419file.pdf). 2010. № 3.
- [Культурная жизнь Петербурга в период экономического кризиса](files/article_content1326732281386799file.pdf). 2010. № 1.
- [Петербуржцы и культурная жизнь города : динамика изменений - 1991-2007 гг.](files/article_content1234351274145361file.pdf) 2008. № 1.
- [Петербург читающий](files/article_content1226750595425621file.pdf). 2007. № 5.
- [Активность петербуржцев в потреблении художественной культуры](files/article_content1218780500350625file.pdf). 2007. № 2.
- [Динамика доходов, социально-психологическое самочувствие и политические предпочтения населения Петербурга](files/article_content1209827229369335file.pdf). 2006. № 4.
- [Петербуржцы в пространстве художественной культуры города](files/article_content1208529823296840file.pdf). 2006. № 2.
- [Петербургский рынок водки](files/article_content120585549515067file.pdf). 2005. № 4.
- [Динамика уровня доходов населения Петербурга](files/article_content1204703628253917file.pdf). 2005. № 3.
- [Эссе о смене эпох](files/article_content119061869145642file.pdf). 2005. № 1.
- [Петербургский рынок водки](files/article_content1201257624239790file.pdf). 2004. № 6.
- [Доходы и социально-психологическое самочувствие населения Петербурга](files/article_content119808327225273file.pdf). 2004. № 3.
- [Книжный рынок Петербурга](files/article_content1190619649348431file.pdf). 2004. № 1.
- [Выборы в Государственную Думу](files/article_content1193061825429064file.pdf). 2003. № 5.
- [Динамика петербургского рынка водки](files/article_content1194269227119143file.pdf). 2003. № 3.
- [Петербург: образ и стиль в прошлом и настоящем](files/article_content1190100499219075file.pdf). 2003. № 3.
- [Культутрный уровень петербуржцев](files/article_content1190013469130588file.pdf). 2002. № 5.
- [Идеальные петербуржцы и москвичи в представлении жителей двух столиц](files/article_content1190013322260198file.pdf). 2002. № 3.
- [Петербуржцы. Откуда мы родом?](files/article_content1190100341278931file.pdf) 2002. № 1.
- [Выдающиеся петербуржцы](files/article_content119009998176616file.pdf). 2001. № 4.
- [Много ли человеку денег надо?](files/2001-1-05.pdf) 2001. № 1.
- [Петербуржцы и культурная жизнь города: десять лет наблюдений](files/article_content1190618035348678file.pdf). 2000. № 5.
- [Пушкин в нашей жизни](files/article_content1190012901337985file.pdf). 1999. № 2.
- Петербуржцы в театрах, на концертах и выставках. 1998. № 5.
- Должен ли Б. Ельцин уйти в отставку? 1997. № 1.

**Ильин В.** (6)

- [Анатомия социального успеха в географическом пространстве](files/article_content1447317770224198file.pdf). 2014. № 6.
- [Интервью с социологом как исследование](files/article_content1328103414220046file.pdf). 2010. № 5.
- [Повседневная жизнь молодежи Санкт Петербурга в период кризиса](files/article_content1327333695359788file.pdf). 2010. № 2.
- [Ночной клуб: драматургический подход](files/article_content1213794855239307file.pdf). 2007. № 1.
- [Товар как социальный конструкт](files/article_content1197471444159166file.pdf). 2004. № 2.
- [Драматургия повседневности](files/article_content1190013631106909file.pdf). 2003. № 2.

**Ипатова А.** (3)

- [Неправильные решения интервьюеров при коммуникативных сбоях в стандартизированном телефонном интервью](files/2018-4-05.pdf). 2018. № 4.
- [Использование параданных в анализе телефонных опросов](files/article_content1447317841249983file.pdf). 2014. № 6.
- [Схемы выдвижения в стандартизированном интервью](files/article_content1380213060383346file.pdf). 2012. № 4.

**Исаев С.** (8)

- [Парламентские выборы 2011 года: петербургский аспект](files/article_content1356939975140702file.pdf). 2011. № 5.
- [Петербургский электорат накануне парламентских выборов декабря 2007 года](files/article_content122675043313423file.pdf). 2007. № 5.
- [Итоги 2005 года глазами жителей Петербурга](files/article_content120792236589988file.pdf). 2006. № 1.
- [Либералиссимусы наших дней](files/article_content1203755683252487file.pdf). 2004. № 4.
- [Унесенные ветром](files/article_content1196672945445655file.pdf). 2004. № 1.
- [Парламентские выборы - по-российски](files/article_content119426910766488file.pdf). 2003. № 3.
- Аудитория газет. 2001. № 2.
- Выборы 99: первый прогноз результатов голосования петербуржцев по партийным спискам. 1999. № 5.

### К


**Кавторин В.** (1)

- [Нужна ли социологии "большая теория"?](files/article_content1195575677412366file.pdf) 2003. № 1.

**Казанцев А.** (3)

- [Трансформация политического ландшафта Петербурга: новый ландшафт](files/article_content1203675394384717file.pdf). 2005. № 1.
- Компьютеры и Интернет в домозозяйствах СПб. 2002. № 5.
- [Телевизионная реклама: к вопросу об эффективности](files/2001_1_Kazantsev.pdf). 2002. № 1.

**Калачева О.** (1)

- [Празднование как индикатор социальных изменений: старые и новые праздники постсоветской России](files/article_content119557296895943file.pdf). 2003. № 1.

**Калинина П.** (1)

- [Образ Петербурга глазами молодежи](files/article_content135694029335472file.pdf). 2011. № 4.

**Кальной И.** (1)

- [Общество рассчитывает на социологию. Социология — на общество](files/2017-1-09.pdf). 2017. № 1.

**Канаев Д.** (2)

- Мифы информационного рынка. 2002. № 5.
- [Золотой слой Петербурга](files/2001-1-04.pdf). 2001. № 1.

**Каневский Е.** (1)

- [Контексты эмпирического познания в социологии и возможности программы ВЕГА](files/article_content1260464166454700file.pdf). 2008. № 6.

**Каныгин Г.** (1)

- [Аппарат научного знания в социологии: постановка задачи](files/2019-1-05.pdf). 2019. № 1.

**Карапетян Р.** (1)

- [О прошедшей в Санкт-Петербурге Всероссийской научно-практической конференции "Современное общество и труд"](files/article_content1444125406217809file.pdf). 2014. № 2.

**Карасев В.** (1)

- К вопросу о сегментации политического рынка и позиционирования В. Яковлева и В. Матвиенко на выборах губернатора СПб. 2000. № 2.

**Кашина М.** (1)

- [Актуальные проблемы реформы государственной власти](files/2002_2_Kluev.pdf). 2002. № 2.

**Кесельман Л.** (8)

- [Палестино-израильский конфликт в представлении россиян](files/article_content1208530006229813file.pdf). 2006. № 2.
- [Петербург правеет?](files/article_content1193061571381788file.pdf) 2003. № 5.
- [Давайте разберемся](files/article_content1193064194392816file.pdf). 2003. № 5.
- Поколенческая трансформация политического сознания. 2002. № 6.
- Социально-структурные координаты политического сознания жителей СПб. 2002. № 3.
- [Социальные координаты наркотизма в Петербурге](files/2001-1-02.pdf). 2001. № 1.
- Субъективная защищенность от насилия. 2000. № 6.
- Социально-структурные координаты губернаторской кампании в СПб. 2000. № 2.

**Кинчарова А.** (1)

- [Симптомы кризиса и антикризисные меры на предприятиях Санкт-Петербурга](files/article_content1296914336227300file.pdf). 2009. № 3.

**Клюев А.** (2)

- [Проблема опережающего развития и научное прогнозирование в системе национальной безопасности России](files/article_content1381307318477000file.pdf). 2012. № 5.
- [Актуальные проблемы реформы государственной власти](files/2002_2_Kluev.pdf). 2002. № 2.

**Князева Е.** (2)

- [Структура крымской идентичности: опыт применения бинарной логистической регрессии для построения идентификационных моделей крымчан (на материалах исследования «Открытое мнение - Крым 2016»)](files/2017-2-02.pdf). 2017. № 2.
- [Влияние Интернета на социально-политические ориентации и социальное самочувствие молодежи (одесский опыт)](files/2016-1-04.pdf). 2016. № 1.

**Козлова Л.** (4)

- [Биографии российских социологов: самопознание и образ социологии](files/article_content138130734228397file.pdf). 2012. № 5.
- [К 60-летию со дня рождения Батыгина Геннадия Семеновича](files/article_content1356760850220790file.pdf). 2011. № 1.
- [«Телескоп» смотрит в прошлое. Беседа об изучении истории современной российской социологии](files/article_content1296208499123748file.pdf). 2009. № 1.
- [О реконструкции истории послереволюционной социологии. Комментарий к диалогу Б. Докторова и В. Ядова](files/article_content1216017643422436file.pdf). 2008. № 3.

**Копытов Д.** (1)

- [Проблема опережающего развития и научное прогнозирование в системе национальной безопасности России](files/article_content1381307318477000file.pdf). 2012. № 5.

**Кордонский С.** (1)

- [Картины мира и информационная герменевтика](files/2018-3-03.pdf). 2018. № 3.

**Корнев Н.** (10)

- [Социо-пространственное измерение Санкт-Петербурга: жилищная картография](files/article_content1220712840230721file.pdf). 2008. № 3.
- [Коготок - увяз... (эссе о явлении синергетики в социальное пространство)](files/article_content1220973124122233file.pdf). 2008. № 2.
- [Товарищество собственников жилья: опыты создания. Семь случаев вне центра Петербурга](files/article_content120982706087524file.pdf). 2006. № 4.
- [Экспертиза социального измерения](files/article_content1205855576122260file.pdf). 2005. № 4.
- [Жилищная стратификация в центре Санкт-Петербурга](files/article_content120367507160235file.pdf). 2005. № 1.
- [Сегрегация по-петербургски – поиски реальности](files/article_content1197390715339144file.pdf). 2004. № 2.
- Доступность жилищной компенсации семьям с низким доходом и развитие ситуации с их задолженностью за жилье в 2000 г. 2001. № 2.
- Долг петербуржцев за жилье продолжает расти. Кто виноват и что делать? 2000. № 3.
- Мониторинг доступности жилищной компенсации нуждающимся семьям в СПб: многодетные семьи, май 1999 г. 1999. № 4.
- Жилищные компенсации и задолженность населения по оплате жилья и коммунальных услуг в СПб. 1999. № 2.

**Корниенко А.** (2)

- [Слова года в непрямом диалоге с властью](files/2018-2-03.pdf). 2018. № 2.
- [Отклик на книгу «Театр и публика: опыт социологического исследования 1960-1970-х годов»](files/article_content1404811209216597file.pdf). 2013. № 4.

**Коровяковский Ю.** (1)

- [Социо-пространственное измерение Санкт-Петербурга: жилищная картография](files/article_content1220712840230721file.pdf). 2008. № 3.

**Королева Т.** (1)

- [Онлайновый архив Ирвинга Гофмана](files/article_content1328103754153574file.pdf). 2010. № 5.

**Корсаков Д.** (1)

- Как увеличить прибыль с помощью рекламы. 1998. № 6.

**Косатая О.** (1)

- [Социальное производство рисков в сфере потребления (на примере рынка алкоголя)](files/article_content1205855250250184file.pdf). 2005. № 4.

**Костюковский Я.** (1)

- [«Милиция и этнические мигранты. Практики взаимодействия». Рецензия на книгу](files/article_content135693964896910file.pdf). 2011. № 5.

**Костюшев В.** (1)

- Санкт-Петербургская ассоциация социологов: итоги-1999, проекты-2000. 2000. № 1.

**Кравец Н.** (3)

- [Итоги конкурса публикаций](files/article_content1218781029204054file.pdf). 2007. № 2.
- [Отчетно-выборное собрание Санкт-Петербургской ассоциации социологов](files/article_content1204705326288120file.pdf). 2005. № 3.
- [Итоги конкурса публикаций](files/article_content1196671559129878file.pdf). 2003. № 1.

**Кравченко В.** (2)

- [«Управляемая демократия» в России – миф или реальность?](files/article_content1203675443227516file.pdf) 2005. № 1.
- [Информационный сервис – специальность 21 века](files/article_content1197391671340545file.pdf). 2004. № 2.

**Краснов Р.** (6)

- [Корпоративные мероприятия в компаниях Санкт-Петербурга](files/article_content120429940739050file.pdf). 2005. № 2.
- [Пользователи интернет в Петербурге](files/article_content1201258033354366file.pdf). 2004. № 6.
- [Частные пользователи Интернет в Санкт-Петербурге](files/2002_2_Krasnov.pdf). 2002. № 2.
- [Рынок оливок в Санкт-Петербурге](files/2001_1_Krasnov.pdf). 2002. № 1.
- Рынок соков СПб. 2001. № 2.
- Почему мы пьем сок? – обзор рынка сока СПб. 1999. № 4.

**Крастынь С.** (1)

- ["Человек-масса" в коммуникативных ситуациях](files/article_content1230370227116861file.pdf). 2007. № 6.

**Кривошеев Ю.** (1)

- [Университетские петербургские чтения](files/2001_1_Krivosheev.pdf). 2002. № 1.

**Крокинская О.** (1)

- [«Практика — это то, что я могу понять»](files/article_content1447317952249923file.pdf). 2014. № 6.

**Кропотов А.** (4)

- Петербургский рынок пельменей. 2002. № 4.
- Рынок соков СПб. 2000. № 6.
- Пельмени – символ возрождения российского производителя (обзор рынка пельменей СПб). 2000. № 4.
- Рынок маргарина СПб. 1999. № 2.

**Кузнецова Е.** (4)

- [Итоги медиа-года в Санкт-Петербурге: 2011 г. (обзор составлен на основе данных TNS Россия)](files/article_content1379923898454861file.pdf). 2012. № 2.
- [Кисломолочная продукция в России: особенности потребления категории и тенденции развития](files/article_content1379519362477942file.pdf). 2012. № 1.
- [Всемирная паутина в цифрах. Аудитория Интернета в России](files/article_content1356760573370325file.pdf). 2011. № 3.
- [Чемпионат мира по футболу-2010: итоги телесмотрения](files/article_content1327768133161226file.pdf). 2010. № 4.

**Кулясов И.** (1)

- [Устойчивость и трансформация поморских и вепсских сообществ](files/article_content1356761293384430file.pdf). 2011. № 1.

**Кулясова А.** (1)

- [Устойчивость и трансформация поморских и вепсских сообществ](files/article_content1356761293384430file.pdf). 2011. № 1.

**Куприянов Л.** (1)

- [Отдельные аспекты кадровой политики здравоохранения России и европейских стран](files/2018-5-07.pdf). 2018. № 5.

**Кучина М.** (1)

- [Аспекты институционального функционирования социального предпринимательства](files/article_content1446551092483228file.pdf). 2014. № 4.

### Л


**Лапина В.** (1)

- [Летняя школа факультета политических наук и социологии Европейского университета в Санкт-Петербурге «Университет без Профессоров» как новый образовательный формат](files/article_content1446720780288227file.pdf). 2014. № 5.

**Лебедев Д.** (1)

- [Как снять квартиру в Петербурге: правила сделки на рынке арендного жилья](files/article_content1211646093390228file.pdf). 2006. № 6.

**Лежикова А.** (1)

- [Социальное партнерство: какое оно сегодня, и каким оно может быть завтра](files/article_content1205855968477406file.pdf). 2005. № 4.

**Лейбин В.** (1)

- [Неодинокое одиночество](files/article_content1379923165237862file.pdf). 2012. № 2.

**Лейбина Н.** (1)

- [Как создавался портрет И. С. Кона](files/article_content1379923182275523file.pdf). 2012. № 2.

**Лехциер В.** (1)

- [Собственным голосом: опыт социолого-поэтического освоения нарративов](files/article_content1478173105176319file.pdf). 2015. № 6.

**Лисовский А.** (1)

- [Кто сильнее – кит или слон? Или рассуждения о количественной и качественной социологии](files/article_content1200639033343359file.pdf). 2004. № 5.

**Лобанова А.** (1)

- [«Безалкогольное пиво» или Европа по Йошкар-Олински: институциональный изоморфизм креативного пространства](files/article_content1446720657303021file.pdf). 2014. № 5.

**Локша А.** (1)

- [О необходимости повышения социальной составляющей молодежного туризма в России](files/article_content1404986246161147file.pdf). 2013. № 5.

**Ломоносова М.** (1)

- [Бороноеву Асалхану Ользоновичу 80 лет!](files/2017-3-01.pdf) 2017. № 3.

**Лурье С.** (1)

- [Плач по оскудевающей родине…(рецензия)](files/2018-1-07.pdf). 2018. № 1.

**Ляшев К.** (1)

- [Интерпретация формальных и содержательных показателей в произведениях изобразительного искусства: результаты социально)психологического исследования произведений современной украинской живописи](files/article_content1356940415302876file.pdf). 2011. № 6.

### М


**Мазлумянова Н.** (1)

- [Рекламист в Америке – больше чем рекламист](files/article_content1208529504390814file.pdf). 2006. № 2.

**Майор М.** (3)

- [Война как экзистенциал социального поля](files/article_content1477987246119853file.pdf). 2015. № 3.
- [Социология права Г. Д. Гурвича](files/article_content132733382041319file.pdf). 2010. № 2.
- ["Человек-масса" в коммуникативных ситуациях](files/article_content1230370227116861file.pdf). 2007. № 6.

**Максимов Б.** (11)

- [Звездные часы питерской социологии](files/article_content1328194768239548file.pdf). 2010. № 6.
- [Диалог о рабочих](files/article_content1327509182183989file.pdf). 2010. № 3.
- [Динамика занятости, доходов, социально-психологического самочувствия и ориентаций рабочих в Петербурге](files/article_content1230370334277454file.pdf). 2007. № 6.
- [Крупное промышленное предприятие в процессе реформ](files/article_content120913564753583file.pdf). 2006. № 3.
- [Когда народ безмолвствует](files/article_content1208530128289041file.pdf). 2006. № 2.
- [Новое общественное движение «за иной мир» или всеевропейская тусовка социальных романтиков?](files/article_content1207922238276278file.pdf) 2006. № 1.
- [Рефлексии социолога на проявления быстротекущей жизни](files/article_content120534304283631file.pdf). 2005. № 5.
- [Рабочие в Петербурге](files/article_content1204298805479519file.pdf). 2005. № 2.
- [Авангард шахтерского движения на финише преобразования отрасли](files/article_content1203675156473872file.pdf). 2005. № 1.
- [Картинки из жизни петербуржцев](files/article_content1195573418378728file.pdf). 2003. № 1.
- Жизнь рабочих на питерском предприятии. 2002. № 4.

**Макушева М.** (1)

- [Реализация исследований на заказ: о проблеме противоречия между логикой социологического исследования и сложившихся практик их проведения](files/article_content1476967958251221file.pdf). 2015. № 2.

**Малышев А.** (1)

- Контент – анализ предвыборных обещаний кандидатов в депутаты в органы местного самоуправления. 1997. № 6.

**Мальцева Д.** (3)

- [Сетевой анализ биографических интервью: кейс Т.И. Заславской](files/2018-2-02.pdf). 2018. № 2.
- [Сетевой анализ биографических интервью: возможности и ограничения](files/2017-1-06.pdf). 2017. № 1.
- [Исследование информационной культуры и профессиональной коммуникации в социологическом сообществе ](files/article_content1404810013281844file.pdf). 2013. № 3.

**Мамаева С.** (2)

- [Практика пользования электронными ресурсами в Российской национальной библиотеке](files/article_content1245479477378322file.pdf). 2008. № 2.
- [Читатели газет в Российской национальной библиотеке](files/article_content1223472097490482file.pdf). 2007. № 4.

**Мамраева Д.** (2)

- [Оценка деятельности интернет-магазинов глазами казахстанских покупателей](files/2016-4-07.pdf). 2016. № 4.
- [Оценка аттрактивности казахских туристических сайтов](files/article_content1477989726321094file.pdf). 2015. № 4.

**Манаев О.** (1)

- [«Острова в океане»: проблемы массовой коммуникации в социальной теории](files/article_content1380212261138832file.pdf). 2012. № 3.

**Манаева Н.** (1)

- [«Острова в океане»: проблемы массовой коммуникации в социальной теории](files/article_content1380212261138832file.pdf). 2012. № 3.

**Манзанова Г.** (1)

- [Особенности трансформации национального приграничного региона в условиях глобализации](files/article_content14043794878323file.pdf). 2013. № 2.

**Мануильская К.** (3)

- [Тенденции развития рынка маркетинговых исследований в России (обзор профессиональной выставки research expo 2018)](files/2018-3-05.pdf). 2018. № 3.
- [Как правильно задавать вопросы об изменениях цен? Методические особенности измерения инфляционных ожиданий](files/article_content1404986203111939file.pdf). 2013. № 5.
- [Документарный и гуманитарный подходы к операционализации уровня образования в опросах общественного мнения](files/article_content1230370098243159file.pdf). 2007. № 6.

**Манько Ю.** (1)

- Варианты экономического поведения и социально-психологическая адаптация групп населения Санкт-Петербурга, связанных с оборонным комплексом. 2002. № 6.

**Мацкевич М.** (9)

- [Между солидарностью и протестом](files/article_content1207062782154833file.pdf). 2005. № 6.
- [Профилактика наркотизма как социальная проблема](files/article_content1198083668298467file.pdf). 2004. № 3.
- [Петербург правеет?](files/article_content1193061571381788file.pdf) 2003. № 5.
- Поколенческая трансформация политического сознания. 2002. № 6.
- Социально-структурные координаты политического сознания жителей СПб. 2002. № 3.
- Локализация ответственности и адаптация к постсоветской действительности. 2001. № 3.
- [Социальные координаты наркотизма в Петербурге](files/2001-1-02.pdf). 2001. № 1.
- Субъективная защищенность от насилия. 2000. № 6.
- Социально-структурные координаты губернаторской кампании в СПб. 2000. № 2.

**Мельник И.** (1)

- [Guten tag, Европа! Опыт международного социологического исследования](files/article_content1194267918358066file.pdf). 2003. № 3.

**Мельник М.** (1)

- Политическое сознание пожилых петербуржцев: опровержение стереотипа единообразия. 2000. № 5.

**Мендус А.** (2)

- [Служба 77: доставка товаров на дом](files/2002_2_Andreeva.pdf). 2002. № 2.
- Перспективы использования нетрадиционных строительных материалов на рынке СПб. 2000. № 5.

**Меркулова Д.** (2)

- [Образ волжских городов в массовом сознании их жителей](files/article_content1478172233390042file.pdf). 2015. № 5.
- [Материальный достаток как фактор самоидентификации профессиональной принадлежности российского врача](files/article_content1476364718428205file.pdf). 2015. № 1.

**Меркурьева Ю.** (2)

- [Кластерный анализ профессионального поля Петербурга](files/article_content1192622248437810file.pdf). 2003. № 6.
- [Профессиональные статусы петербуржцев: в поисках новой системы координат](files/article_content1193835797235663file.pdf). 2003. № 4.

**Минаков А.** (1)

- Политическое сознание пожилых петербуржцев: опровержение стереотипа единообразия. 2000. № 5.

**Минина В.** (2)

- [Рынок мясной продукции в Санкт-Петербурге: проблемы формирования и функционирования](files/article_content1204703916107711file.pdf). 2005. № 3.
- Анализ потребительского поведения населения СПб на рынке продовольственных товаров. 1999. № 6.

**Минкус И.** (2)

- [Общественное мнение о местном самоуправлении города](files/article_content1201256910251274file.pdf). 2004. № 6.
- [Исследование интернет-аудитории Санкт-Петербурга](files/article_content119262276364418file.pdf). 2003. № 6.

**Миронов Б.** (1)

- [Галина Старовойтова - продолжение жизни](files/article_content1193837847214860file.pdf). 2003. № 6.

**Мирошниченко Н.** (1)

- [Крупное промышленное предприятие в процессе реформ](files/article_content120913564753583file.pdf). 2006. № 3.

**Могилевский О.** (3)

- [Выборы в Законадательное собрание: политический смысл организационных решений](files/article_content1356761174119682file.pdf). 2011. № 1.
- [Исследования общественного мнения в современной информационно-коммуникативной среде](files/article_content1297504947395244file.pdf). 2009. № 4.
- [Петербург стремится к мировым стандартам исследований](files/article_content1255522067487248file.pdf). 2008. № 5.

**Могилевский Р.** (6)

- [Минимизация рисков при работе «по правилам». Поведение исследователя в опасной среде](files/2016-4-05.pdf). 2016. № 4.
- [Административная реформа в России: все могут короли?](files/article_content1201256707262424file.pdf) 2004. № 5.
- [Прекрасный новый мир или опрос об опросах](files/article_content1200639142115372file.pdf). 2004. № 5.
- [Петербургские семьи: между прошлым и будущим](files/article_content1193835567443756file.pdf). 2003. № 4.
- [Guten tag, Европа! Опыт международного социологического исследования](files/article_content1194267918358066file.pdf). 2003. № 3.
- Социологическая поддержка избирательной кампании: условия эффективности. 1999. № 4.

**Моисеев С.** (2)

- [Сетевой анализ биографических интервью: кейс Т.И. Заславской](files/2018-2-02.pdf). 2018. № 2.
- [Сетевой анализ биографических интервью: возможности и ограничения](files/2017-1-06.pdf). 2017. № 1.

**Моор В.** (1)

- [Поэтические зарисовки к «афоризмам житейской мудрости» Артура Шопенгауэра](files/2018-6-06.pdf). 2018. № 6.

**Москаленко Е.** (1)

- [Мариинский театр: публичность и коммуникация](files/article_content1195573771224150file.pdf). 2003. № 1.

**Москвина В.** (18)

- [Пользователи социальных сетей](files/article_content1327333874323807file.pdf). 2010. № 2.
- [Посетители заведений быстрого питания](files/article_content1297505621432615file.pdf). 2009. № 6.
- [Основные тенденции развития радиоэфира Петербурга](files/article_content1296208674193798file.pdf). 2009. № 1.
- [Газеты - изменения за 2007 год](files/article_content1245479152134692file.pdf). 2008. № 2.
- [Основные тенденции развития радиоэфира Петербурга](files/article_content1223472026467280file.pdf). 2007. № 4.
- [Проведение новогодних праздников петербуржцами в 2006 году](files/article_content1218780568485618file.pdf). 2007. № 2.
- [Мобильная связь: рынок приближается к насыщению](files/article_content1210867584167281file.pdf). 2006. № 5.
- [Аудитория радиостанций: что изменилось за год?](files/article_content1208529644444314file.pdf) 2006. № 2.
- [Кинорынок Петербурга](files/article_content1207921825349359file.pdf). 2006. № 1.
- [Основные тенденции развития FM-диапазона Петербурга в первом квартале 2005 года](files/article_content120470515224029file.pdf). 2005. № 3.
- [Основные тенденции развития FM диапазона Петербурга в 2004 году](files/article_content1201257911425369file.pdf). 2004. № 6.
- [Обзор радиопредпочтений петербуржцев в возрасте 25-54 лет](files/article_content1196675311422107file.pdf). 2004. № 1.
- [Радиорынок Петербурга: основные тенденции развития FM-диапазона](files/article_content119383644561400file.pdf). 2003. № 4.
- Радиостанции Санкт-Петербурга. 2002. № 5.
- Рынок прессы в Санкт-Петербурге. 2002. № 3.
- Радиостанции Петербурга. 10 лет спустя. 2001. № 6.
- [Радиорынок СПб](files/2001-1-06.pdf). 2001. № 1.
- Радиорынок Петербурга. 2000. № 4.

**Мохов С.** (1)

- [Рынок ритуальных услуг: опыт этнографии сенситивного поля](files/2017-1-05.pdf). 2017. № 1.

**Мухин А.** (1)

- [Отклики читателей на публикацию книги «Моя жилищная история. Автобиографические очерки и биографические интервью»](files/2019-1-10.pdf). 2019. № 1.

**Мухортова В.** (1)

- [Формирование идентичности будущих врачей: мотивы выбора профессии](files/article_content1207063197484332file.pdf). 2005. № 6.

**Мягков А.** (1)

- [Восприятие респондентами метода телефонного интервью](files/article_content1327767590282289file.pdf). 2010. № 4.

### Н


**Неймер Ю.** (1)

- ["Динамит в папильотках"](files/article_content1209135146171328file.pdf). 2006. № 3.

**Нестеров Ю.** (1)

- [Отклики читателей на публикацию книги «Моя жилищная история. Автобиографические очерки и биографические интервью»](files/2019-1-10.pdf). 2019. № 1.

**Никитина Б.** (1)

- [Роль населения в организации обращения с коммунальными отходами: сравнительный анализ российских и европейских тенденций](files/2017-6-05.pdf). 2017. № 6.

**Николаенко Г.** (1)

- [Прошлое через призму настоящего. VIII социологические чтения памяти В.Б. Голофаста](files/article_content1476364882122032file.pdf). 2015. № 1.

### О


**Оберемко О.** (1)

- [Влияние идентификации авторства и жанра на интерпретацию публицистического текста](files/article_content120792210861329file.pdf). 2006. № 1.

**Обухова К.** (7)

- [Покупательские предпочтения розничных продуктовых торговых сетей в Санкт-Петербурге](files/article_content1209135957154232file.pdf). 2006. № 3.
- [Петербургский рынок общеинформационной и деловой прессы](files/article_content120706305925680file.pdf). 2005. № 6.
- [Мы все такие разные …](files/article_content120429919078739file.pdf) 2005. № 2.
- [Телевизионные предпочтения петербуржцев](files/article_content1197391518332435file.pdf). 2004. № 2.
- [Пользование компьютером в Санкт-Петербурге](files/article_content119306347020233file.pdf). 2003. № 5.
- [Мобильная связь в Санкт-Петербурге](files/article_content1194855948376673file.pdf). 2003. № 2.
- И телевизор в каждый дом. 2002. № 6.

**Овруцкий А.** (1)

- [Социализация организации и коммуникативные процессы](files/article_content1404379624204057file.pdf). 2013. № 2.

**Овчинников А.** (1)

- [Устойчивость и трансформация поморских и вепсских сообществ](files/article_content1356761293384430file.pdf). 2011. № 1.

**Озерова О.** (1)

- [Алкоголизация и смертность в современной России](files/article_content1296914111389206file.pdf). 2009. № 2.

**Олимпиева И.** (1)

- [Малый бизнес и рынок бюрократических услуг в Санкт-Петербурге](files/article_content1197390855219202file.pdf). 2004. № 2.

**Ольнова Т.** (1)

- [Комфортность социальной среды в восприятии современных школьников](files/article_content1218780865368113file.pdf). 2007. № 2.

**Осиик А.** (2)

- Рынок рыбных продуктов СПб. 2000. № 3.
- Компьютерная техника в петербургских фирмах. 1998. № 5.

**Османов Т.** (1)

- [Особенности реализации общероссийской выборки трудоспособного населения по мобильным телефонам](files/article_content1404809974409939file.pdf). 2013. № 3.

### П


**Павленко В.** (1)

- [К вопросу исследования аксиологических структур социальных субъектов](files/article_content1193063874423316file.pdf). 2003. № 5.

**Павлова С.** (1)

- [Ленинградский литературный андеграунд как культурный феномен: специфика формирования и функционирования](files/article_content1197391279190905file.pdf). 2004. № 2.

**Панакова Я.** (1)

- [Питерская Чукотка: от практики к образу](files/article_content1193836153268734file.pdf). 2003. № 4.

**Панова Л.** (5)

- [Отдельные аспекты кадровой политики здравоохранения России и европейских стран](files/2018-5-07.pdf). 2018. № 5.
- [Социальные неравенства в здоровье: тенденции в Санкт-Петербурге 1992 – 2006 гг.](files/article_content1250571211139983file.pdf) 2008. № 4.
- [Здоровье населения, неравенство доходов и инновационный потенциал регионов](files/article_content1211645984257954file.pdf). 2006. № 6.
- [Динамика осознаваемого здоровья петербуржцев за период реформ](files/article_content1207062639424345file.pdf). 2005. № 6.
- [Доступность первичной медицинской помощи в оценках петербуржцев](files/2002_2_Panova.pdf). 2002. № 2.

**Панюкова П.** (1)

- [Симптомы кризиса и антикризисные меры на предприятиях Санкт-Петербурга](files/article_content1296914336227300file.pdf). 2009. № 3.

**Петренко Е.** (1)

- [Социография: инновационная аналитическая стратегия](files/article_content1327333739127963file.pdf). 2010. № 2.

**Петрова М.** (1)

- [Рынок товаров для ремонта и строительства Санкт-Петербурга](files/article_content122000635651455file.pdf). 2007. № 3.

**Петрова О.** (1)

- [Телевизионная аудитория Санкт-Петербурга](files/article_content1194269410436497file.pdf). 2003. № 3.

**Петрунина Л.** (3)

- [Из истории социологических исследований в Третьяковской галерее](files/article_content140481098986859file.pdf). 2013. № 4.
- [Два лица одного музея. «Ночь музеев» в Третьяковской галерее](files/article_content138130769851613file.pdf). 2012. № 6.
- [Портрет посетителя Третьяковской галереи](files/article_content135676136867571file.pdf). 2011. № 3.

**Пиджаков А.** (1)

- [Социология права Г. Д. Гурвича](files/article_content132733382041319file.pdf). 2010. № 2.

**Пиевская Д.** (1)

- [Петербургские ресурсы интернет: эффективность, востребованность, запросы пользователей](files/2001-1-03.pdf). 2001. № 1.

**Пикулёва О.** (1)

- [К вопросу о маркетинге и брендинге территорий](files/article_content1381307741383035file.pdf). 2012. № 6.

**Погорелов Ф.** (2)

- [Социологическое распутье: меркантильный подход](files/article_content1198935175438879file.pdf). 2004. № 4.
- [Интеллектуальный ландшафт петербургской социологии: попытка картографии](files/article_content119667605189902file.pdf). 2004. № 1.

**Подгорная И.** (1)

- [Влияние формы обсуждения на обогащение образа проблемы в общественном мнении](files/article_content1380213031137892file.pdf). 2012. № 4.

**Подольская М.** (1)

- [Современная церковная лексика: проблема нормативного произношения и ее социальные последствия](files/article_content1328103630253135file.pdf). 2010. № 5.

**Подушко М.** (4)

- [Московский рынок товаров для ремонта и строительства](files/article_content1234351782362469file.pdf). 2008. № 1.
- [Рынок маркетинговых исследований Санкт-Петербурга](files/article_content1211646764455279file.pdf). 2006. № 6.
- [Покупательские предпочтения розничных продуктовых торговых сетей в Санкт-Петербурге](files/article_content1209135957154232file.pdf). 2006. № 3.
- Обзор рынка прессы в Санкт-Петербурге. 2002. № 2.

**Полтинникова М.** (1)

- [Аппарат научного знания в социологии: постановка задачи](files/2019-1-05.pdf). 2019. № 1.

**Поляков Л.** (1)

- [Социология и культура: порядок слов](files/article_content1404811190183871file.pdf). 2013. № 4.

**Попонов М.** (1)

- [Общая динамика телесмотрения: динамика и тенденции](files/article_content1209827341391983file.pdf). 2006. № 4.

**Порецкина Е.** (1)

- ["Челночный" бизнес. Краткая история вопроса и его особенности в Санкт-Петербурге](files/article_content1210867019357086file.pdf). 2006. № 5.

**Потемкин В.** (3)

- [Государство, общественные отношения и легитимность власти](files/2016-4-06.pdf). 2016. № 4.
- [Военная социология или социология войны](files/2016-2-04.pdf). 2016. № 2.
- [Социальное действие в системе общественных отношений](files/article_content144473442940052file.pdf). 2014. № 3.

**Преснякова Л.** (1)

- [Как правильно задавать вопросы об изменениях цен? Методические особенности измерения инфляционных ожиданий](files/article_content1404986203111939file.pdf). 2013. № 5.

**Пригожин А.** (1)

- [Воспоминания о Якове Самуиловиче Капелюше (1937-1990)](files/article_content1202893665366675file.pdf). 2005. № 2.

**Пронякин Д.** (1)

- [Христианская церковь в социально-политической эволюции Европы IV-XVII вв.](files/article_content1356761451258271file.pdf) 2011. № 2.

**Проскурина Н.** (1)

- [Повседневная жизнь молодежи Санкт Петербурга в период кризиса](files/article_content1327333695359788file.pdf). 2010. № 2.

**Протасенко Т.** (19)

- [Возможно ли качественное и профессиональное выполнение госзадания?](files/2018-4-03.pdf) 2018. № 4.
- [Моя жилищная история: от Читы до Ленинграда](files/2017-5-06.pdf). 2017. № 5.
- [Петербуржцы о теракте в метро 3 апреля 2017 г.](files/2017-3-08.pdf) 2017. № 3.
- [Что новенького? (Обзор новых практик в экономике, политике и культуре)](files/2016-6-04.pdf). 2016. № 6.
- [Петербуржцы и иногородние жители Петербурга: поиск путей бесконфликтного совместного проживания](files/article_content1446720703320816file.pdf). 2014. № 5.
- [Откуда вышли опросы общественного мнения?](files/article_content1444125424187890file.pdf) 2014. № 2.
- [Социология — не руководство к действию, не инструкция по применению, а лишь повод для размышления (Рецензия на книгу "От плебисцита — к выборам. Как и почему россияне голосовали на выборах 2011-2012 гг.»)](files/article_content1404986309331378file.pdf). 2013. № 5.
- [Политика: отвлекающие маневры](files/article_content138021308718624file.pdf). 2012. № 4.
- [Однополые браки — проблема в основном политическая](files/article_content1379519310139357file.pdf). 2012. № 1.
- [«Гляжу в себя как в зеркало эпохи» (история в документах о том, как не была допущена к печати книга «Семья в крупном городе», под редакцией В.Б. Голофаста)](files/article_content1202893457446877file.pdf). 2005. № 6.
- Российские журналисты – кто они? 2002. № 3.
- [Требуется идея для Петербурга. Лежалый товар не предлагать](files/article_content1190013029277416file.pdf). 2001. № 6.
- Прошу считать меня социологом. 2001. № 6.
- [Различия в уровне жизни и социальной атмосфере населения Северо-Запада России: к проблеме глобализационных трансформаций](files/2001_4_02.pdf). 2001. № 4.
- Некоторые аспекты восприятия населением «женской» темы в контексте социально-экономических изменений. 2000. № 6.
- Изменения в уровне жизни и социальная атмосфера. 2000. № 1.
- Год после кризиса: изменение политических симпатий петербуржцев. 1998. № 5.
- Динамика уровня жизни петербуржцев за шесть лет экономических реформ. 1998. № 2.
- Партийные симпатии жителей СПб. 1997. № 5.

**Путинцева К.** (1)

- [Ночной клуб: драматургический подход](files/article_content1213794855239307file.pdf). 2007. № 1.

### Р


**Рабжаева М.** (2)

- [Санкт-Петербургский международный книжный салон - нерыночный феномен на книжном рынке?](files/article_content1226750262255664file.pdf) 2007. № 5.
- [Петербургская идентичность в прошлом и настоящем](files/2002_2_Semenkov.pdf). 2002. № 4.

**Равинский Д.** (5)

- [Петербург — город на воде](files/2018-3-07.pdf). 2018. № 3.
- [К истории социальной типизации женщин. «Дочь бедных, но благородных родителей»: литературная формула и социальный тип](files/2017-3-07.pdf). 2017. № 3.
- [В поисках «красоты Петербурга»](files/article_content1478172253113656file.pdf). 2015. № 5.
- [«Street lit» — литературный жанр и социологический феномен](files/article_content1446720565254382file.pdf). 2014. № 5.
- ["Тайные памятники" Петербурга - Ленинграда](files/article_content1444734491158830file.pdf). 2014. № 3.

**Ревтова В.** (7)

- Российские журналисты – кто они? 2002. № 3.
- [Какой Петербург нам нужен?](files/2002_2_Revtova.pdf) 2002. № 2.
- [Требуется идея для Петербурга. Лежалый товар не предлагать](files/article_content1190013029277416file.pdf). 2001. № 6.
- [Различия в уровне жизни и социальной атмосфере населения Северо-Запада России: к проблеме глобализационных трансформаций](files/2001_4_02.pdf). 2001. № 4.
- Некоторые аспекты восприятия населением «женской» темы в контексте социально-экономических изменений. 2000. № 6.
- Изменения в уровне жизни и социальная атмосфера. 2000. № 1.
- Год после кризиса: изменение политических симпатий петербуржцев. 1998. № 5.

**Решетников М.** (8)

- [Социальный активизм и терроризм в Европе](files/article_content1205342789285296file.pdf). 2005. № 5.
- [О концепции и стратегии борьбы с наркоманиями в России](files/article_content1205855073304514file.pdf). 2005. № 4.
- [Демократия, терроризм и гражданское общество: тенденции, противоречия, исторические иллюзии](files/article_content1201257054119026file.pdf). 2004. № 6.
- [Клинический метод в изучении и разрешении межнациональных конфликтов](files/article_content1198083820113272file.pdf). 2004. № 3.
- [Нас ждут нескучные времена или «проблема 2004-2008»](files/article_content1197391065274050file.pdf). 2004. № 2.
- [Бедность в современной России – анализ проблемы](files/article_content119306094098121file.pdf). 2003. № 5.
- [Что происходит с парламентаризмом?](files/article_content12598597504427file.pdf) 2002. № 6.
- [Глобализация – самый общий взгляд](files/article_content1259859663230221file.pdf). 2002. № 2.

**Рогозин Д.** (26)

- [Неправильные решения интервьюеров при коммуникативных сбоях в стандартизированном телефонном интервью](files/2018-4-05.pdf). 2018. № 4.
- [Формальная процедура определения этнографического интервью](files/2018-3-04.pdf). 2018. № 3.
- [Зачем социологу изучать фабрикации](files/2017-5-02.pdf). 2017. № 5.
- [Неочевидные последствия стандартизации массовых опросов](files/2017-4-02.pdf). 2017. № 4.
- [Иллюзорная прямота стандартизации в стандартизированных интервью](files/2017-3-05.pdf). 2017. № 3.
- [Дискурсивные штреки и квершлаги Бурибая: социология слухов](files/2016-4-04.pdf). 2016. № 4.
- [Социальный порядок в российской исполнительной власти](files/2016-1-03.pdf). 2016. № 1.
- [Семь уроков христианского старения](files/article_content1478172303118311file.pdf). 2015. № 5.
- [Методология публичности Майкла Буравого](files/article_content1476967838493080file.pdf). 2015. № 2.
- [Диссолюция бюрократии как основа коррупции](files/article_content1444734394274384file.pdf). 2014. № 3.
- [Как возможен осмысленный разговор о смерти](files/article_content144369481635001file.pdf). 2014. № 1.
- [Актуальность непрерывного профессионального образования для российского бизнеса](files/article_content1404986130158999file.pdf). 2013. № 5.
- [Особенности реализации общероссийской выборки трудоспособного населения по мобильным телефонам](files/article_content1404809974409939file.pdf). 2013. № 3.
- [Кто добровольно перераспределит накопительный тариф, или долгосрочная финансовая активность населения в новых условиях пенсионных отчислений](files/article_content1404379478387211file.pdf). 2013. № 2.
- [Схемы выдвижения в стандартизированном интервью](files/article_content1380213060383346file.pdf). 2012. № 4.
- [Постпросмотровый синдром](files/article_content1380212299448717file.pdf). 2012. № 3.
- [«Сейчас я никуда не хожу»: Разговорная картография Торжка и его окрестностей](files/article_content1379519194382810file.pdf). 2012. № 1.
- [Оценка погружения в кинопросмотр: «Добро пожаловать в Зомбиленд» (Рубен Флейшер, 2009)](files/article_content1356940740207515file.pdf). 2011. № 5.
- [Целостность восприятия фильма-катастрофы: "2012" (Роланд Эммерих, 2009)](files/article_content1356760327104284file.pdf). 2011. № 3.
- [Подростковый фильм глазами зрелого зрителя: "История одного вампира" (Пол Вайц, 2009)](files/article_content1356760231487973file.pdf). 2011. № 1.
- [Некоммуникативные порядки в разговорах о теплоснабжении](files/article_content1296914409463840file.pdf). 2009. № 3.
- [В поисках уральской интеллигенции](files/article_content129620856160769file.pdf). 2009. № 1.
- [Разговоры с учителями о реформах в образовании: социологическая экспедиция в школы Екатеринбурга](files/article_content1245479438338609file.pdf). 2008. № 2.
- [Уровень неответов при организации конформной выборки в торговых центрах](files/article_content1234351114183970file.pdf). 2008. № 1.
- [Документарный и гуманитарный подходы к операционализации уровня образования в опросах общественного мнения](files/article_content1230370098243159file.pdf). 2007. № 6.
- [Фальсификация экспертности экспертного интервью](files/article_content1223472150276408file.pdf). 2007. № 4.

**Родионова А.** (9)

- [Новые надежды (Выборы правления Санкт-Петербургской ассоциации социологов)](files/article_content1381307839150890file.pdf). 2012. № 6.
- [Продолжение следует... в октябре](files/article_content1380213113102008file.pdf). 2012. № 4.
- [Социологи между Сциллой и Харибдой](files/article_content1328103794229151file.pdf). 2010. № 5.
- [К итогам отчетно-выборного собрания СПАС](files/article_content1226749955240967file.pdf). 2007. № 5.
- [Итоги работы Санкт-Петербургской ассоциации социологов в 2005-2006 гг.](files/article_content1210867999308933file.pdf) 2006. № 5.
- [Товарищество собственников жилья: опыты создания. Базовый случай](files/article_content1209827116356206file.pdf). 2006. № 4.
- Об итогах конкурса студенческих работ "Галатея". 2000. № 6.
- Собрание Санкт-Петербургской ассоциации социологов. 2000. № 3.
- Социология и выборы. 2000. № 1.

**Родионова Е.** (1)

- Политическая толерантность жителей Санкт-Петербурга. 2001. № 5.

**Рождественский А.** (1)

- Оценка существующего состояния и перспектив развития розничной торговли в СПб. 2000. № 5.

**Романович Н.** (1)

- [Платоновский фестиваль и роль личности в истории города](files/2018-5-06.pdf). 2018. № 5.

**Рунов А.** (1)

- [Выборы в Законадательное собрание: политический смысл организационных решений](files/article_content1356761174119682file.pdf). 2011. № 1.

**Русалинова А.** (2)

- [Из истории советской социологии эпохи «развитого социализма». Проблема образа жизни трудового коллектива как социальный заказ в СССР 60-80-х годов XX века](files/2016-5-02.pdf). 2016. № 5.
- [В.А. Ядов как яркий представитель поколения «пятидесятников» или провозвестник Ренессанса в социологии?](files/2016-2-02.pdf) 2016. № 2.

**Русинова Н.** (6)

- [Социальные неравенства в здоровье и психологические ресурсы личности: проект сравнительного исследования в странах Европы и России](files/2018-1-03.pdf). 2018. № 1.
- [Социальные особенности здоровья в Европе и России: влияние индивидуальных и контекстуальных факторов ](files/article_content1404809952190703file.pdf). 2013. № 3.
- [Здоровье населения России: динамика в социальных срезах, 1994-2009 гг.](files/article_content1379923807393227file.pdf) 2012. № 2.
- [Социальные неравенства в здоровье: тенденции в Санкт-Петербурге 1992 – 2006 гг.](files/article_content1250571211139983file.pdf) 2008. № 4.
- [Здоровье населения, неравенство доходов и инновационный потенциал регионов](files/article_content1211645984257954file.pdf). 2006. № 6.
- [Динамика осознаваемого здоровья петербуржцев за период реформ](files/article_content1207062639424345file.pdf). 2005. № 6.

**Рыбина Е.** (1)

- [Петербуржцы о частной собственности на землю: идеологические штампы, политико-экономические ориентации, хозяйственные практики](files/2001_1_Rybina.pdf). 2002. № 1.

**Рыйгас Е.** (3)

- [Колокольное дворянство против аристократии духа](files/2017-2-04.pdf). 2017. № 2.
- [Храм как рынок. XVI Всероссийская выставка «Православная Русь»](files/article_content1328194876471611file.pdf). 2010. № 6.
- [Синагогальный ритуал: реконструкция смысла](files/article_content120125753745820file.pdf). 2004. № 6.

**Рылин С.** (1)

- [Корпоративные мероприятия в компаниях Санкт-Петербурга](files/article_content120429940739050file.pdf). 2005. № 2.

### С


**Савин С.** (1)

- [Легитимность власти как фактор стабильности современного российского общества](files/article_content1194853873381665file.pdf). 2003. № 2.

**Саганенко Г.** (4)

- [Контексты эмпирического познания в социологии и возможности программы ВЕГА](files/article_content1260464166454700file.pdf). 2008. № 6.
- [Потенциал общественных потребностей в развитии образования взрослых в современной российской ситуации](files/article_content122675050667729file.pdf). 2007. № 5.
- [Наркомания в российском обществе: взгляд на проблему глазами родительской организации «Азария»](files/article_content1201256297229655file.pdf). 2004. № 6.
- [Интеграционный процесс в европейском высшем образовании](files/article_content1198935444429804file.pdf). 2004. № 4.

**Салкуцан С.** (4)

- Особенности потребительского спроса на мебельном рынке. 2000. № 2.
- Интернет-провайдеры. Какие они? 2000. № 1.
- Особенности национального рынка одежды. 1999. № 6.
- Рынок строительных материалов СПб. 1999. № 4.

**Санина А.** (2)

- [«В стране – кризес, а в душе весна: когнитивное конструирование кризиса](files/article_content1296914380325865file.pdf). 2009. № 3.
- ["От Восстания до Мужества – 15 минут ужаса". Петербургские маршрутки как социальный и культурный феномен](files/article_content1209827376193437file.pdf). 2006. № 4.

**Сафонова А.** (3)

- [Проблемы профориентационной деятельности в образовательных учреждениях Санкт-Петербурга](files/article_content121379476866644file.pdf). 2007. № 1.
- [Ленинградская область: в поисках путей развития трудовых ресурсов региона](files/article_content1205342836405668file.pdf). 2005. № 5.
- [Административная реформа в России: все могут короли?](files/article_content1201256707262424file.pdf) 2004. № 5.

**Сафонова Т.** (2)

- [Обольщение профессией (исследование рекрутирования молодых петербургских социологов)](files/article_content1198482757273873file.pdf). 2004. № 4.
- [Мариинский театр: публичность и коммуникация](files/article_content1195573771224150file.pdf). 2003. № 1.

**Сафронов В.** (20)

- [Голосование за радикальные правые партии в Европе: роль культурного изменения и партийной поляризации (Часть II)](files/2019-1-01.pdf). 2019. № 1.
- [Голосование за радикальные правые партии в Европе: роль культурного изменения и партийной поляризации (Часть I)](files/2018-6-02.pdf). 2018. № 6.
- [Социальные неравенства в здоровье и психологические ресурсы личности: проект сравнительного исследования в странах Европы и России](files/2018-1-03.pdf). 2018. № 1.
- [Демократический протест в странах Европы: ценностные мотивации и социетальные условия](files/2016-6-02.pdf). 2016. № 6.
- [Неудовлетворенность граждан демократией и протест: Россия в европейском контексте](files/2016-2-05.pdf). 2016. № 2.
- [Политическое участие в странах Европы: общественный контекст и социально,культурные неравенства](files/article_content1476364672202438file.pdf). 2015. № 1.
- [Внимание граждан к политике в Европе и России: социальное структурирование и институциональный контекст](files/article_content1404987249423172file.pdf). 2013. № 6.
- [Социальные особенности здоровья в Европе и России: влияние индивидуальных и контекстуальных факторов ](files/article_content1404809952190703file.pdf). 2013. № 3.
- [Здоровье населения России: динамика в социальных срезах, 1994-2009 гг.](files/article_content1379923807393227file.pdf) 2012. № 2.
- [Поддержка политической системы в России: взгляды элиты и массовой публики (окончание)](files/article_content1326732214401603file.pdf). 2010. № 1.
- [Поддержка политической системы в России: взгляды элиты и массовой публики](files/article_content1297505517395129file.pdf). 2009. № 6.
- [Политическая культура Санкт-Петербурга: поддержка демократии элитой и массовой публикой](files/article_content12604642923090file.pdf). 2008. № 6.
- [Социальные неравенства в здоровье: тенденции в Санкт-Петербурге 1992 – 2006 гг.](files/article_content1250571211139983file.pdf) 2008. № 4.
- [Отношение к демократии в России: конец эпохи Ельцина](files/article_content1220006265194file.pdf). 2007. № 3.
- [Здоровье населения, неравенство доходов и инновационный потенциал регионов](files/article_content1211645984257954file.pdf). 2006. № 6.
- [Социальный капитал и демократия: исследования в Санкт-Петербурге](files/article_content119667265718059file.pdf). 2004. № 1.
- [Демократическая культура в Санкт-Петербурге: исследование политической терпимости](files/article_content1193062013246879file.pdf). 2003. № 5.
- [В поисках либеральной культуры. Санкт-Петербург в посткоммунистический период](files/article_content1195643756388055file.pdf). 2003. № 2.
- К проблеме консолидации политической демократии в России. 2002. № 5.
- Советская система или рынок и демократия. 2001. № 5.

**Свечников В.** (2)

- [Лекция в дистанционном обучении — какой ей быть?](files/2017-4-05.pdf) 2017. № 4.
- [Социальное конструирование виртуальных реальностей: опыт взаимодействия с vip-персонами](files/2017-1-07.pdf). 2017. № 1.

**Седова М.** (1)

- [Дискаунтеры - это мода или будущее розничной торговли?](files/2001_4_03.pdf) 2001. № 4.

**Седова Н.** (1)

- [Обзор III международной социологической конференции «продолжая Грушина»](files/article_content1404379677225033file.pdf). 2013. № 2.

**Семак И.** (3)

- [Производители мебели в Санкт-Петербурге](files/article_content1197391367125145file.pdf). 2004. № 2.
- [Универсамы Санкт-Петербурга](files/article_content1192622639185102file.pdf). 2003. № 6.
- Российский рынок алкогольных напитков: проблема измерения. 1998. № 4.

**Семашко Л.** (5)

- [Социология детства во всех аспектах](files/article_content1205343139419351file.pdf). 2005. № 5.
- [Избирательное право детей, исполняемое родителями: социокультурный институт антитеррористического иммунитета](files/article_content1204298909412357file.pdf). 2005. № 2.
- [Манифест сферной демократии: нелиберальный проект](files/article_content1200638503237172file.pdf). 2004. № 5.
- [Пекин. Всемирный социологический конгресс. Мосты между Востоком и Западом. Гармония идет с Востока](files/article_content1198935981108277file.pdf). 2004. № 4.
- [Смыслы культурной социологии (Рецензия на книгу Д. Александера. Смыслы социальной жизни. Культурная социология)](files/article_content119739217415666file.pdf). 2004. № 2.

**Семенков В.** (10)

- [О парадоксе научной активности преподавателей гуманитарной кафедры в техническом вузе](files/article_content1444125369287369file.pdf). 2014. № 2.
- [Два взгляда на ситуацию в среднем образовании США: полевое исследование Джона Гудлэда против статистического анализа Марка Пена](files/article_content1381307215439014file.pdf). 2012. № 5.
- [О дефамилизации в семейно-демографической политике Российской Федерации](files/article_content1297505464143423file.pdf). 2009. № 5.
- [Санкт-Петербургский международный книжный салон - нерыночный феномен на книжном рынке?](files/article_content1226750262255664file.pdf) 2007. № 5.
- [О задачах культурной политики в современном обществе](files/article_content119808337243398file.pdf). 2004. № 3.
- [Мусаев В. И. Преступность в Петрограде в 1917-1921 гг. и борьба с ней](files/article_content1193838835436770file.pdf). 2003. № 4.
- [Многонациональный Петербург. История. Религия. Народы](files/article_content1196672208460831file.pdf). 2003. № 3.
- [Рок-фестиваль «Окна открой»](files/article_content1195573985365478file.pdf). 2003. № 1.
- [Петербургская идентичность в прошлом и настоящем](files/2002_2_Semenkov.pdf). 2002. № 4.
- [Рецензия на книгу Б. Хазард. Рядом с Невским проспектом. Моя жизнь среди неофициальных художников Ленинграда](files/2001_4_08.pdf). 2001. № 4.

**Семенов В.** (1)

- [Выражение российской полиментальности в наименованиях и архитектуре Петербурга](files/article_content120429904262500file.pdf). 2005. № 2.

**Сербина С.** (1)

- Физическое здоровье и бедность: функциональное взаимодействие или механизм сегрегации? 2002. № 3.

**Сергеев В.** (10)

- [Пасьянс Перентратора -2. Перентратор против Гудмена](files/article_content1296913939158542file.pdf). 2009. № 2.
- [Пасьянс Перентратора или социолог как электрик](files/article_content129620875298309file.pdf). 2009. № 1.
- [Краеугольный камень и дом на песке. Краткое введение в теорию конструктов четвертого порядка](files/article_content1237220062283955file.pdf). 2008. № 5.
- [Социальная дистанция и национальные установки](files/article_content124547934194294file.pdf). 2008. № 2.
- [Петербургский колбасный рынок](files/article_content120470374944196file.pdf). 2005. № 3.
- [Компьютеры в семьях петербуржцев](files/article_content1198084306181394file.pdf). 2004. № 3.
- [Выборы в Государственную Думу](files/article_content1193061825429064file.pdf). 2003. № 5.
- [Петербургский потребительский рынок сока](files/article_content1195574206188586file.pdf). 2003. № 1.
- Компьютеры и Интернет в домозозяйствах СПб. 2002. № 5.
- Домашние компьютеры и пользование сетью Интернет. 2001. № 2.

**Сережина В.** (3)

- [Немного об истории развития мирового информационного рынка на примере корпорации D&B](files/article_content1193062813120848file.pdf). 2003. № 5.
- Рейтинги лидеров бизнеса Санкт-Петербурга. 2000. № 6.
- Рейтинги лидеров бизнеса Санкт-Петербурга. 2000. № 6.

**Сидорин А.** (1)

- [Представления молодежи о практиках и ценности здоровья: анализ эмпирических данных](files/article_content1476364742372087file.pdf). 2015. № 1.

**Симанова Н.** (1)

- [Образ Петербурга глазами молодежи](files/article_content135694029335472file.pdf). 2011. № 4.

**Скворцов Н.** (1)

- [Теперь вместе](files/2001-1-01.pdf). 2001. № 1.

**Сланова З.** (1)

- Ночь пожирателей рекламы. 2002. № 4.

**Смирнов А.** (1)

- [«Петербуржцы» и «ленинградцы» в культурном пространстве города](files/article_content1204299118218600file.pdf). 2005. № 2.

**Смирнова Е.** (3)

- [Борис Докторов. Современная российская социология. История в биографиях и биографии в истории](files/article_content1443694950391992file.pdf). 2014. № 1.
- [Рецензия на книгу Г.И. Саганенко «Многообразие возможностей социологического изучения сферы образования»](files/article_content1204299312206228file.pdf). 2005. № 2.
- [Качественные и количественные стратегии: поле деятельности или система предпочтений?](files/article_content1200638877143226file.pdf) 2004. № 5.

**Смирнова Л.** (1)

- Туризм 2001: подводя итоги. 2002. № 4.

**Создателев А.** (1)

- Пользователи сети интернет как особая потребительская группа. 1999. № 5.

**Соколов М.** (4)

- [Студенческая культура, образовательные институты и политическая социализация: Беннингтонские исследования Ньюкомба](files/article_content140498737735730file.pdf). 2013. № 6.
- [Интеллектуальный ландшафт петербургской социологии: попытка картографии](files/article_content119667605189902file.pdf). 2004. № 1.
- [Академический турист как социальный тип](files/article_content1195643995374312file.pdf). 2003. № 6.
- [Наступающий кризис социологического теоретизирования](files/article_content1261130053234409file.pdf). 2002. № 5.

**Соколов Н.** (21)

- [Нужен ли хорошему социологу внешний аудит качества?](files/article_content1327767650229652file.pdf) 2010. № 4.
- [Петербургские домохозяйства: социальные сети и социальный капитал](files/article_content124655023540677file.pdf). 2008. № 3.
- [Семейные деньги: бюджеты петербургских домохозяйств в 2000-2004 гг.](files/article_content1210867335390779file.pdf) 2006. № 5.
- [Петербургские домохозяйства в начале 21 века](files/article_content1203675297413108file.pdf). 2005. № 1.
- [Кластерный анализ профессионального поля Петербурга](files/article_content1192622248437810file.pdf). 2003. № 6.
- [Профессиональные статусы петербуржцев: в поисках новой системы координат](files/article_content1193835797235663file.pdf). 2003. № 4.
- Физическое здоровье и бедность: функциональное взаимодействие или механизм сегрегации? 2002. № 3.
- [Петербуржцы о частной собственности на землю: идеологические штампы, политико-экономические ориентации, хозяйственные практики](files/2001_1_Rybina.pdf). 2002. № 1.
- Досуговые практики Санкт-Петербургской элиты. 2001. № 6.
- Политическая толерантность жителей Санкт-Петербурга. 2001. № 5.
- [Петербургские ресурсы интернет: эффективность, востребованность, запросы пользователей](files/2001-1-03.pdf). 2001. № 1.
- Политическое сознание пожилых петербуржцев: опровержение стереотипа единообразия. 2000. № 5.
- Петербуржец как дачник и огородник – штрихи к портрету владельцев загородной недвижимости. 2000. № 3.
- Массовое сознание против народной мудрости или чего не хватает петербуржцам для полного счастья? 2000. № 1.
- Кто решит судьбу думских выборов в СПб? Эскиз портрета потенциального электората. 1999. № 5.
- Ю. Лужков и В. Яковлев: социальные позиции в СПб, сравнительный анализ. 1999. № 4.
- Готовность к насилию в Санкт-Петербурге. 1999. № 2.
- Бизнес и предпринимательство в зеркале свободных высказываний петербуржцев. 1999. № 1.
- Сторонники и противники губернатора Санкт-Петербурга В. Яковлева: наброски социальных портретов. 1998. № 5.
- Российский рынок алкогольных напитков: проблема измерения. 1998. № 4.
- Конец 1997 г.: позиции губернатора СПб достаточно устойчивы. 1998. № 1.

**Соколов Р.** (1)

- [Университетские петербургские чтения](files/2001_1_Krivosheev.pdf). 2002. № 1.

**Сократилин В.** (4)

- [Когда зацветет соломенный рейтинг, или по каким причинам не сбудутся прогнозы социологов на выборах осенью 2016 года?](files/2016-3-03.pdf) 2016. № 3.
- [Загадки «Больших данных» или From Big Data to Куда-то…](files/2016-1-05.pdf) 2016. № 1.
- [Песня про on-line панели](files/article_content13813072386866file.pdf). 2012. № 5.
- ["Боржоми" улетел, но обещал вернуться](files/article_content1209135900190979file.pdf). 2006. № 3.

**Соловьева Ю.** (2)

- [Образ волжских городов в массовом сознании их жителей](files/article_content1478172233390042file.pdf). 2015. № 5.
- [Материальный достаток как фактор самоидентификации профессиональной принадлежности российского врача](files/article_content1476364718428205file.pdf). 2015. № 1.

**Спиридонова В.** (1)

- [Адаптация иногородних студентов к культуре Санкт-Петербурга](files/article_content1209135793417793file.pdf). 2006. № 3.

**Старовойтова О.** (1)

- [Конкурс «Галатея» памяти Г.В. Старовойтовой](files/2018-1-08.pdf). 2018. № 1.

**Стенина Н.** (1)

- [Тайное оружие PR-специалистов fashion-рынка (обзор популярных PR-инструментов на примере анализа информационной активности джинсовых брендов)](files/article_content1380212509328124file.pdf). 2012. № 3.

**Степанова Е.** (2)

- [Обсуждение успешности Болонской реформы в российском образовании](files/article_content1250571079413133file.pdf). 2008. № 4.
- [Интеграционный процесс в европейском высшем образовании](files/article_content1198935444429804file.pdf). 2004. № 4.

**Столович Л.** (5)

- [Слово, которое было в конце. Конкурс слов 2011 года и десятилетия 2001-2011 как материал для социологических раздумий](files/article_content1379519234295973file.pdf). 2012. № 1.
- [А.З. Штейнберг и М.М. Бахтин. К истории идеи диалога](files/article_content1356940309103357file.pdf). 2011. № 4.
- [Игорь Кон. Из переписки](files/article_content1356760697151527file.pdf). 2011. № 3.
- [Есть ли душа Петербурга в «Ленинградской социологической школе»?](files/article_content1328194692116213file.pdf) 2010. № 6.
- [Социологи в Кяэрику](files/article_content1326732139365524file.pdf). 2010. № 1.

**Сунгуров А.** (1)

- [Публичная политика и общественное мнение](files/article_content1200638340213805file.pdf). 2004. № 5.

**Сухачев В.** (1)

- [Война как экзистенциал социального поля](files/article_content1477987246119853file.pdf). 2015. № 3.

**Сымонович Ч.** (15)

- [Российские ровесники Войны /РВ/ — участники социальных изменений на последнем этапе советского социализма (1970-е — 1980-е гг.)](files/2018-5-08.pdf). 2018. № 5.
- [Советские российские ровесники Войны в культурном пространстве «зрелого социализма» (1970-е — 1980-е гг.)](files/2018-2-04.pdf). 2018. № 2.
- [Российские ровесники Войны в политической жизни СССР 1970-х — середины 1980-х гг.](files/2017-6-06.pdf) 2017. № 6.
- [Российские ровесники Войны /РВ/ в 1970-е - 1980-е гг.: работники и потребители](files/2017-4-03.pdf). 2017. № 4.
- [Общественно-политические аспекты облика и истории российских ровесников Войны (РВ) в 1960-е годы](files/2016-4-08.pdf). 2016. № 4.
- [Российские ровесники Войны в 1960-е годы](files/2016-3-05.pdf). 2016. № 3.
- [Оттепель и молодёжь — российские ровесники Войны в конце 1950-х - начале 1960-х гг.](files/article_content1478172213484727file.pdf) 2015. № 5.
- [Российские ровесники Войны /РВ/ в средних классах школы (вторая половина 1950-х гг.)](files/article_content1476967930446263file.pdf). 2015. № 2.
- [Российские ровесники Войны в младшем школьном возрасте (конец 1940-х - первая половина 1950-х годов)](files/article_content1444125298498750file.pdf). 2014. № 2.
- [К начальной истории ровесников Войны](files/article_content1404378666379919file.pdf). 2013. № 1.
- [К 50-му материалу рубрики Б. Докторова](files/article_content1404378739408706file.pdf). 2013. № 1.
- [Об изучении возрастной когорты российских ровесников Великой Отечественной войны](files/article_content1379923769300527file.pdf). 2012. № 2.
- [Диалог о рабочих](files/article_content1327509182183989file.pdf). 2010. № 3.
- [Отечественная социология за полвека (заинтересованный взгляд извне)](files/article_content1296913684375764file.pdf). 2009. № 3.
- [Об интересе к исламу среди населения Санкт-Петербурга](files/article_content1223471936151009file.pdf). 2007. № 4.

### Т


**Тайц Д.** (1)

- [Туннель в Европу на Фурштатской зарос чертополохом](files/article_content1478173201226076file.pdf). 2015. № 6.

**Тарасенко А.** (1)

- [История одного успеха: почему некоторым общественным организациям удается участие в законотворческом процессе?](files/article_content120585586031799file.pdf) 2005. № 4.

**Тарусин М.** (2)

- [Типично нетипичная история](files/article_content1380212185216965file.pdf). 2012. № 3.
- [Смотреть на все, не насилуя наблюдательности](files/article_content132750925139998file.pdf). 2010. № 3.

**Ташенова Л.** (2)

- [Оценка деятельности интернет-магазинов глазами казахстанских покупателей](files/2016-4-07.pdf). 2016. № 4.
- [Оценка аттрактивности казахских туристических сайтов](files/article_content1477989726321094file.pdf). 2015. № 4.

**Тертерян Р.** (1)

- Информационно-аналитическая составляющая рыночных исследований. Принципы работы с информацией. 2002. № 5.

**Тетерина Д.** (1)

- [Отношение молодежной аудитории к ребрендингу компании «МТС»](files/article_content1260464350398723file.pdf). 2008. № 6.

**Тимофеева И.** (1)

- Структура спроса на книги. 1998. № 4.

**Тимофеева М.** (1)

- [Социально-экономическое положение и самочувствие молодежи в Санкт-Петербурге](files/article_content1327333615213372file.pdf). 2010. № 2.

**Тихонов А.** (1)

- [О ситуации в Социологическом институте РАН и перспективах его развития](files/article_content1195574546340987file.pdf). 2003. № 1.

**Тихонова А.** (1)

- Рынок растительных масел. 1999. № 3.

**Тишин Е.** (1)

- Жилищно-коммунальная реформа в общественном мнении петербуржцев. 1997. № 5.

**Толстокорова А.** (2)

- [«Cнова между нами города»: эмоциональные вызовы трансграничного родительства](files/2017-2-03.pdf). 2017. № 2.
- [Полевые исследования гендерных аспектов трудовой миграции: этические и методологические вызовы](files/2016-2-07.pdf). 2016. № 2.

**Травин И.** (3)

- [М.Б. Глотов. Структурный анализ общества](files/article_content132733395625413file.pdf). 2010. № 2.
- [Социологические чтения памяти В. Б. Голофаста](files/article_content1218781005395824file.pdf). 2007. № 2.
- Варианты экономического поведения и социально-психологическая адаптация групп населения Санкт-Петербурга, связанных с оборонным комплексом. 2002. № 6.

**Тукумцев Б.** (2)

- [Новые требования к работнику промышленного производства в условиях современной модернизации (социологический анализ)](files/article_content1477987408404132file.pdf). 2015. № 3.
- [Возможно ли сократить бедность среди работающих в сфере производства?](files/article_content1250571178224967file.pdf) 2008. № 4.

**Тульская М.** (1)

- [Петербургский рынок печатных СМИ](files/article_content1198483721214153file.pdf). 2004. № 4.

**Туманова Н.** (1)

- Обзор рынка прессы в СПб. 2001. № 3.

**Тупахина О.** (2)

- [Межконфессиональные особенности практической составляющей структуры религиозного жизненного мира](files/article_content1404987315451225file.pdf). 2013. № 6.
- [Общины православных домовых храмов петербургских вузов как объект социологического изучения](files/article_content1328194900258049file.pdf). 2010. № 6.

**Турчик А.** (1)

- [Разговоры с учителями о реформах в образовании: социологическая экспедиция в школы Екатеринбурга](files/article_content1245479438338609file.pdf). 2008. № 2.

### У


**Уткин В.** (2)

- Духовность общества и качество жизни. 2002. № 4.
- [К вопросу о создания интегрированной системы информационно-аналитического обеспечения деятельности администрации Санкт-Петербурга](files/2001-1-10.pdf). 2001. № 1.

### Ф


**Фадеева О.** (2)

- Динамика уровня жизни петербуржцев за шесть лет экономических реформ. 1998. № 2.
- Партийные симпатии жителей СПб. 1997. № 5.

**Фарахутдинов Ш.** (2)

- [Изучение отношения россиян к реформе образования методом анализа комментариев](files/article_content147696785799989file.pdf). 2015. № 2.
- [Профессиональные респонденты — камень преткновения качества онлайн-опросов в современной России](files/article_content1356760642275899file.pdf). 2011. № 2.

**Федоров В.** (1)

- [После выборов – перед реформой: власть и общественное мнение в современной России](files/article_content1200638245373870file.pdf). 2004. № 5.

**Федорова Н.** (3)

- [Антинаркотические НКО Санкт-Петербурга](files/article_content1193835934205174file.pdf). 2003. № 4.
- Роль общественных организаций в решении проблем реабилитации и адаптации наркозависимых в Санкт-Петербурге. 2001. № 5.
- Качество жизни в оценках городского населения России. 1999. № 3.

**Федотова Л.** (4)

- [От Гэллапа к Грушину: приглашение к размышлениям](files/article_content1207063297417485file.pdf). 2005. № 6.
- [Реклама в обществе - зоны риска](files/article_content1204705036393913file.pdf). 2005. № 3.
- [Воспоминания о Якове Самуиловиче Капелюше (1937-1990)](files/article_content1202893665366675file.pdf). 2005. № 2.
- [Реклама в фильмах](files/article_content1201257762472451file.pdf). 2004. № 6.

**Фетисов В.** (12)

- [Русская революция 1917 года и становление нового типа деятельности общества](files/2017-5-04.pdf). 2017. № 5.
- [Современная эпоха: взгляд сквозь призму конвергентных процессов](files/2016-6-05.pdf). 2016. № 6.
- [Социология: продолжение рефлексии относительно основных понятий](files/article_content1476967802443208file.pdf). 2015. № 2.
- [Эволюция социологии: обретение новых смыслов и функций](files/article_content1476364634202711file.pdf). 2015. № 1.
- [Раскрытие социальных функций социологии — необходимое условие ее самоидентификации](files/article_content1443694782377033file.pdf). 2014. № 1.
- [Конвергенция социальных систем - веление времени](files/article_content1381307130267149file.pdf). 2012. № 5.
- [Деятельность как предмет исследования социологии и ее интегративный принцип](files/article_content1356939569159528file.pdf). 2011. № 6.
- [Между Сциллой и Харибдой: проблема обретения социальной идентичности российским обществом](files/article_content1328194803274265file.pdf). 2010. № 6.
- [Сохранение через развитие - императив нашего времени](files/article_content1297505293496833file.pdf). 2009. № 5.
- [Социальная стабильность российского общества: состояние и перспективы](files/article_content1255522158158300file.pdf). 2008. № 5.
- [Октябрь, социализм и современность](files/article_content1226750370403693file.pdf). 2007. № 5.
- [Социология: продолжение поисков идентичности](files/article_content1190618586307702file.pdf). 2005. № 5.

**Филиппов Г.** (2)

- [Из прошлого ленинградской социологии](files/2018-1-10.pdf). 2018. № 1.
- [Изучение эффективности деятельности аппарата КПСС. Мало известные страницы истории ленинградской социологии](files/article_content140481096774373file.pdf). 2013. № 4.

**Фирсов Б.** (7)

- [Как наводились мосты между советской и зарубежной социологией, или "self-made Sociologists" (глава из книги «История советской социологии: 1950-1980-е годы. Очерки»)](files/article_content1404378550377155file.pdf). 2013. № 1.
- [История социологии «в лицах»: Биография и/или биокритика](files/article_content1356939895440829file.pdf). 2011. № 6.
- [Борису Зусмановичу Докторову 70 лет — поздравляем!](files/article_content1356760939228942file.pdf) 2011. № 3.
- [Ментальные миры современного российского населения (статья третья)](files/article_content1230370767108339file.pdf). 2007. № 6.
- [Ментальные миры современного российского населения (статья 2)](files/article_content1190618411427934file.pdf). 2004. № 5.
- [Два клипа к юбилею мэтра друга](files/article_content1198935665354303file.pdf). 2004. № 4.
- [Ментальные миры современного российского населения](files/article_content1190013836428430file.pdf). 2003. № 4.

**Фомин Э.** (1)

- Качество жизни в оценках городского населения России. 1999. № 3.

**Француз Ю.** (1)

- [Академическая карьера в США: правила игры и мотивы осуществления](files/article_content1205855713418823file.pdf). 2005. № 4.

**Фрумкина Р.** (1)

- [К 60-летию со дня рождения Батыгина Геннадия Семеновича](files/article_content1356760850220790file.pdf). 2011. № 1.

### Х


**Халлисте О.** (1)

- [Обучение в высшем учебном заведении глазами современного студента: на примере Технологического института](files/article_content138130767010256file.pdf). 2012. № 6.

**Хохлова А.** (1)

- [Город как целостность – город как подпространства: Петербург в восприятии мигрантов](files/article_content1201257329155761file.pdf). 2004. № 6.

**Хохлова М.** (1)

- [Компетенции конкурентоспособного молодого специалиста: мнение работодателей и выпускников](files/article_content1444125343296635file.pdf). 2014. № 2.

### Ц


**Цветаева Н.** (1)

- [Мотивация достижения в эпоху перемен](files/article_content1192622536361754file.pdf). 2003. № 6.

**Цветова Е.** (1)

- [Контент-анализ рекламы автомобильных компаний в глянцевых ежемесячных журналах в 2008 году](files/article_content1297505414262960file.pdf). 2009. № 5.

### Ч


**Чагин А.** (6)

- [Петербургский рынок пельменей](files/article_content1198482223333966file.pdf). 2004. № 4.
- [Создание ценности для потребителя](files/article_content1193836716114013file.pdf). 2003. № 4.
- Петербургский рынок майонеза. 2002. № 3.
- Рынок лимонада в Свнкт-Петербурге. 2001. № 6.
- Аудитория СМИ. 2000. № 1.
- Аудитория газет и радиостанций. 1999. № 3.

**Черемушкин А.** (3)

- [Потребление хлебцев жителями Санкт-Петербурга](files/article_content1205342878173627file.pdf). 2005. № 5.
- [Обзор рынка шоколадных изделий в плитках в Петербурге](files/article_content119808403390484file.pdf). 2004. № 3.
- [Общие характеристики покупателей мороженого в Санкт-Петербурге](files/article_content119306239549977file.pdf). 2003. № 5.

**Чикунова А.** (1)

- [Симптомы кризиса и антикризисные меры на предприятиях Санкт-Петербурга](files/article_content1296914336227300file.pdf). 2009. № 3.

**Чугунов А.** (1)

- [Развитие «электронного правительства» на российском и региональном уровнях: индикаторы и возможности мониторинга](files/article_content1213795666291410file.pdf). 2007. № 1.

### Ш


**Шадрин А.** (1)

- Социология на российском Интернете: в начале долгого пути. 1999. № 6.

**Шалин Д.** (5)

- [Проблемы мемуарной этики и достоверности биоинтервью](files/article_content138021221548918file.pdf). 2012. № 3.
- [Дискуссия через океан. Проблемы этики натурного эксперимента: Ответ Андрею Алексееву](files/article_content1379923739468589file.pdf). 2012. № 2.
- [В поисках нарративной идентичности: К диалогу Андрея Алексеева и Дмитрия Шалина](files/article_content1356760968391295file.pdf). 2011. № 3.
- [«По мере созревания нравственная конфронтация становится политической» Интервью Д. Шалина с А. Алексеевым, О. Божковым, Г. Саганенко, Л.Кесельманом](files/article_content132776753370521file.pdf). 2010. № 4.
- [Галина Саганенко и Валерий Голофаст: Гарвардское интервью](files/article_content1208530926195084file.pdf). 2008. № 2.

**Шанкина А.** (1)

- [Сравнительный анализ восприятия столиц семи федеральных округов](files/article_content1194268424426768file.pdf). 2003. № 3.

**Шарыгина О.** (2)

- [Производители мебели в Санкт-Петербурге](files/article_content1197391367125145file.pdf). 2004. № 2.
- [Универсамы Санкт-Петербурга](files/article_content1192622639185102file.pdf). 2003. № 6.

**Шахаева Е.** (1)

- [Встречают по фасаду... (обзор рынка фасадных красок СПб)](files/2001-1-09.pdf). 2001. № 1.

**Шевченко Е.** (1)

- [Музыка в интернете или на музыкальных телевизионных каналах? Каков выбор современного подростка?](files/article_content1327767688260677file.pdf) 2010. № 4.

**Шереги Ф.** (1)

- [Размышления о книге Владимира Шляпентоха «Современная Россия как феодальное общество»](files/article_content1326732024396674file.pdf). 2010. № 1.

**Шерстнев Г.** (1)

- [Можно ли пить заводскую водку?](files/2001-1-08.pdf) 2001. № 1.

**Шинко В.** (1)

- [Усвоение русского языка с помощью самостоятельного использования СМИ и современныхтехнологий в свободное время](files/2018-1-05.pdf). 2018. № 1.

**Широканова А.** (1)

- [Сетевой анализ биографических интервью: возможности и ограничения](files/2017-1-06.pdf). 2017. № 1.

**Шляпентох В.** (3)

- [Можно ли бестрепетно доверять автобиографиям видных людей и даже массовым опросам?](files/article_content135693909876067file.pdf) 2011. № 4.
- [Элиты, а не массы — главный хранитель консерватизма и главный мотор социальных изменений в России ](files/article_content1327508993311018file.pdf). 2010. № 3.
- [Грушин – идеальный кандидат](files/article_content1198483313337097file.pdf). 2004. № 4.

**Шмитран Э.** (1)

- [Усвоение русского языка с помощью самостоятельного использования СМИ и современныхтехнологий в свободное время](files/2018-1-05.pdf). 2018. № 1.

**Штейнберг И.** (1)

- [Использование метафор и ассоциаций в полевых социологических исследованиях (по результатам экспедиции в городах-хозяевах Чемпионата мира по футболу 2018 года)](files/article_content147696789168249file.pdf). 2015. № 2.

### Щ


**Щелкин А.** (7)

- [Современность как откровенно социологический текст. Для его чтения надо только поменять «малое» сознание на «большое»](files/2018-1-02.pdf). 2018. № 1.
- [Повседневность с «неповседневной» точки зрения](files/2016-5-06.pdf). 2016. № 5.
- [Социум в поисках собственной модальности: между самопотворством и самодисциплиной](files/article_content1478173035101777file.pdf). 2015. № 6.
- [ДОИГРАЛИСЬ — лозунг дня:"Даешь гламурную социологию!"](files/article_content1356939234161543file.pdf). 2011. № 4.
- [Российская цивилизация предполагает дискуссию о российской цивилизации](files/article_content1356760753301667file.pdf). 2011. № 1.
- [Берегите цивилизацию от... социологов](files/article_content1327509282113016file.pdf). 2010. № 3.
- [«Есть русская интеллигенция. Вы думали - нет?»](files/article_content129750564245013file.pdf). 2009. № 6.

**Щербо И.** (1)

- [Возможности вторичного анализа эмпирических данных](files/article_content1260464106308891file.pdf). 2008. № 6.

### Ю


**Юран Д.** (1)

- [«Острова в океане»: проблемы массовой коммуникации в социальной теории](files/article_content1380212261138832file.pdf). 2012. № 3.

**Юхнева Н.** (1)

- [Письмо по поводу рецензии на книгу "Многонациональный Петербург. История. Религии. Народы"](files/article_content1198483612373361file.pdf). 2004. № 4.
