---
title: "Рубрики"
---



## Современная история российской социологии

- Докторов Б. [Нариман Аитов. Основатель социологии в Башкортостане](files/2018-6-01.pdf). 2018. №&nbsp;6.
- [Роману Семеновичу Могилевскому — 80 лет!](files/2018-5-01.pdf) 2018. №&nbsp;5.
- [Л.А. Седов: «Я родился в 1934 в Москве, на Арбате»](files/2018-5-02.pdf). 2018. №&nbsp;5.
- Гофман А. [Несколько слов о Леониде Александровиче Седове](files/2018-5-03.pdf). 2018. №&nbsp;5.
- Докторов Б. [Уникальное историко-биографическое наследие А.Н. Алексеева](files/2018-5-09.pdf). 2018. №&nbsp;5.
- [Н.П. Попов: «Я думаю, Джордж Гэллап был бы нами доволен»](files/2018-4-01.pdf). 2018. №&nbsp;4.
- Докторов Б. [Юло Вооглайд: социолог, политик, гражданин](files/2018-4-04.pdf). 2018. №&nbsp;4.
- [Ю. А. Француз: «Я описал только малую толику всего пережитого и пройденного»](files/2018-3-01.pdf). 2018. №&nbsp;3.
- Докторов Б. [Разговоры с Валерием Голофастом: мысленные и реальные](files/2018-2-01.pdf). 2018. №&nbsp;2.
- [«1990 год. Я покинул кипящую перестроечными страстями страну и оказался в Нью-Йорке»](files/2018-1-01.pdf). 2018. №&nbsp;1.
- [«И одним из первых моих слов было: «Но!», что означало "новости"»](files/2017-6-01.pdf). 2017. №&nbsp;6.
- [«В Космосе, который мы называем Человеком, должно оставаться место для человеческого»](files/2017-5-01.pdf). 2017. №&nbsp;5.
- [«Так что главное — найти баланс»](files/2017-4-01.pdf). 2017. №&nbsp;4.
- Богомягкова Е., Ломоносова М. [Бороноеву Асалхану Ользоновичу 80 лет!](files/2017-3-01.pdf) 2017. №&nbsp;3.
- [«Для Щедровицкого содержательный конфликт был чем-то обыденным...»](files/2017-3-02.pdf). 2017. №&nbsp;3.
- [В поисках смыслов. К 90-летию со дня рождения В.Б. Ольшанского](files/2017-2-01.pdf). 2017. №&nbsp;2.
- [Наш коллега, сотрудник Социологического института РАН Будимир Гвидонович Тукумцев отметил свой 90-летний юбилей](files/2017-1-01.pdf). 2017. №&nbsp;1.
- [Файнбург З.И.: «Идти вперед!»](files/2017-1-03.pdf). 2017. №&nbsp;1.
- Докторов Б. [История науки присваивает себе право, в котором люди отказывают богам: она меняет прошлое](files/2017-1-04.pdf). 2017. №&nbsp;1.
- [Димке Д.В.: «Исследования — одно из самых интересных занятий на свете»](files/2016-6-01.pdf). 2016. №&nbsp;6.
- [Тихонов А.В.: «Мне самому интересно понять, как получилось, что я стал заниматься социологией»](files/2016-5-01.pdf). 2016. №&nbsp;5.
- Русалинова А. [Из истории советской социологии эпохи «развитого социализма». Проблема образа жизни трудового коллектива как социальный заказ в СССР 60-80-х годов XX века](files/2016-5-02.pdf). 2016. №&nbsp;5.
- Божков О. [Нацеленность на живой результат своего труда. Алле Александровне Русалиновой — 85](files/2016-4-01.pdf). 2016. №&nbsp;4.
- Докторов Б. [О жизнестойкости «Ленинградской социологической школы». Олегу Борисовичу Божкову — 75](files/2016-4-02.pdf). 2016. №&nbsp;4.
- Докторов Б. [И это все вместила одна жизнь ](files/2016-4-03.pdf). 2016. №&nbsp;4.
- Докторов Б. [И это все вместила одна жизнь](files/2016-3-01.pdf). 2016. №&nbsp;3.
- [«До моей поездки в ИС РАН я вообще не видел «живых» социологов»](files/2016-2-01.pdf). 2016. №&nbsp;2.
- Русалинова А. [В.А. Ядов как яркий представитель поколения «пятидесятников» или провозвестник Ренессанса в социологии?](files/2016-2-02.pdf) 2016. №&nbsp;2.
- [«Кто на мир смотрит разумно — на того и мир смотрит разумно» (Могилевский рассказывает о П. Лебедеве)](files/2016-1-01.pdf). 2016. №&nbsp;1.
- Докторов Б. [Я стою на берегу информационного океана](files/2016-1-02.pdf). 2016. №&nbsp;1.
- [«Мы были «морем молодых», которые «выползли из тьмы»](files/article_content1478173019143477file.pdf). 2015. №&nbsp;6.
- Божков О. [Патриархи уходят и все ложится на нас](files/article_content1478173265205278file.pdf). 2015. №&nbsp;6.
- Докторов Б. [История есть, если только она написана-2. После дороги продолжительностью в 11 лет](files/article_content1478172144344631file.pdf). 2015. №&nbsp;5.
- [Человек, владеющий секретами времени. К 80-летию Валентины Николаевны Ярской-Смирновой](files/article_content1477989504117066file.pdf). 2015. №&nbsp;4.
- [Рогозин Д.М.: «Быть рядом с наставником»](files/article_content1477989526188651file.pdf). 2015. №&nbsp;4.
- Бляхер Л. [Социология в регионе: это как?](files/article_content1477989558225826file.pdf) 2015. №&nbsp;4.
- Докторов Б., Илле М. [Мир Владимира Александровича Ядова. По страницам журнала «Телескоп»](files/article_content1477989840442348file.pdf). 2015. №&nbsp;4.
- Ядов В. [Мемуар о том, как разрабатывалась диспозиционная концепция](files/article_content1477989848471182file.pdf). 2015. №&nbsp;4.
- [Руткевич А.М.: «Историка радует не однообразие, а многообразие людей и идей»](files/article_content147798721561353file.pdf). 2015. №&nbsp;3.
- [Никулин А.М. : «Я странник междисциплинарных направлений, и не только аграрных...»](files/article_content1476967696304817file.pdf). 2015. №&nbsp;2.
- [Молодые социологи Сибири](files/article_content1476364597286209file.pdf). 2015. №&nbsp;1.
- Докторов Б. [О «загадочности Шереги»](files/article_content1447317636281765file.pdf). 2014. №&nbsp;6.
- Докторов Б. [Истинное творчество только и может быть биографичным. К 80-летию Жана Терентьевича Тощенко](files/article_content1447317663255815file.pdf). 2014. №&nbsp;6.
- [Он чувствовал себя человеком XIX в., эпохи революционного прогрессизма](files/article_content144731769312776file.pdf). 2014. №&nbsp;6.
- [Мой путь в социологию оказался долог и тернист](files/article_content144731772039860file.pdf). 2014. №&nbsp;6.
- [К 90-летию Самуила Ароновича Кугеля!](files/article_content1446720497455132file.pdf) 2014. №&nbsp;5.
- [Бляхер Л.Е.: «Испуганный этой перспективой, я кинулся читать учебник Ядова»](files/article_content14467205239384file.pdf). 2014. №&nbsp;5.
- [Зборовский Г.Е.: «Сейчас в истории отечественной социологии меня особенно волнуют ее отношения с политикой и властью»](files/article_content144672053479952file.pdf). 2014. №&nbsp;5.
- [Андрей Алексеев: «Прожитыми годами не горжусь, но вроде и не стыжусь их...»](files/article_content144655093322499file.pdf). 2014. №&nbsp;4.
- [Паутова Л. А.: «Я с радостью ожидаю изменений»](files/article_content1446550986197312file.pdf). 2014. №&nbsp;4.
- [Историко-биографическое исследование российской социологии: к десятилетию проекта](files/article_content1446551020224814file.pdf). 2014. №&nbsp;4.
- Алексеев А., Докторов Б., Ядов В. [Созидатель. По случаю 85-летия Бориса Максимовича Фирсова](files/article_content144473435137663file.pdf). 2014. №&nbsp;3.
- [Гилинский Я.И.: «Мое «лицо» — вроде профессионал, но все время куда-то заносит»](files/article_content1444734365406863file.pdf). 2014. №&nbsp;3.
- [В.А. Ядов: «Нам одно остается: честно делать свое дело»](files/article_content144354215412170file.pdf). 2014. №&nbsp;2.
- [Анна Темкина: «Социология — это не наука или искусство одиночек, вокруг должен кипеть академический бульон дискуссий»](files/article_content1443694727370413file.pdf). 2014. №&nbsp;1.
- [ Григорьева Л.И.: «В религиоведение я ниоткуда не приходила. Я в нем родилась, сформировалась и выросла». Часть II](files/article_content1404987195333892file.pdf). 2013. №&nbsp;6.
- [Григорьева Л.И.: «В религиоведение я ниоткуда не приходила. Я в нем родилась, сформировалась и выросла». Часть I](files/article_content1404986037206843file.pdf). 2013. №&nbsp;5.
- [Г.В. Осипов: «Такой истории социологии нет ни у одной из зарубежных стран. Это трагическая, драматическая история»](files/article_content1404810876124517file.pdf). 2013. №&nbsp;4.
- Здравомыслова А. [Записки о нашем детстве: из воспоминаний А.Г.Здравомысловой](files/article_content1404810859329164file.pdf). 2013. №&nbsp;4.
- Абрамова Л., Филиппов Г. [Изучение эффективности деятельности аппарата КПСС. Мало известные страницы истории ленинградской социологии](files/article_content140481096774373file.pdf). 2013. №&nbsp;4.
- Петрунина Л. [Из истории социологических исследований в Третьяковской галерее](files/article_content140481098986859file.pdf). 2013. №&nbsp;4.
- [В. В. Локосов: «Повседневность охлаждала накал романтического восприятия философии»](files/article_content1404809884301064file.pdf). 2013. №&nbsp;3.
- [О жизни и творчестве С. М. Василейского. Простые вопросы - непростые ответы ](files/article_content140480991218320file.pdf). 2013. №&nbsp;3.
- Докторов Б. [А.Г. Здравомыслов: его деятельность и наследие еще предстоит изучить. К 85-летию со дня рождения](files/article_content1404379381266300file.pdf). 2013. №&nbsp;2.
- [А.Г. Здравомыслов "О принципах социологического мышления" (несостоявшееся выступление на пленарной сессии всероссийского социологического конгресса 21.10.2008)](files/article_content1404379390320442file.pdf). 2013. №&nbsp;2.
- [Такого уровня люди приходили на "огонек", вели разговоры; это и были мои "университеты"](files/article_content140437849487490file.pdf). 2013. №&nbsp;1.
- Фирсов Б. [Как наводились мосты между советской и зарубежной социологией, или "self-made Sociologists" (глава из книги «История советской социологии: 1950-1980-е годы. Очерки»)](files/article_content1404378550377155file.pdf). 2013. №&nbsp;1.
- [Татарова Г. Г.: «Интеграция методологического знания — неизбежный этап в социологии»](files/article_content1381307499157931file.pdf). 2012. №&nbsp;6.
- Докторов Б. [Генеалогия четырех первых поколений советских/российских социологов](files/article_content1381307087129266file.pdf). 2012. №&nbsp;5.
- [Готлиб А. С. : «Моя потребность рассказать «свою историю» счастливо совпала с исследовательским интересом к автоэтнографии»](files/article_content1380212881454016file.pdf). 2012. №&nbsp;4.
- [Воспоминания о Люции Николаевне Лесохиной. Интервью с Владимиром Ядовым](files/article_content1380212902385944file.pdf). 2012. №&nbsp;4.
- Тарусин М. [Типично нетипичная история](files/article_content1380212185216965file.pdf). 2012. №&nbsp;3.
- [Давыдов А. А.: «Мои занятия «золотым сечением» воспринимали как чудачество научного маргинала](files/article_content137992311711851file.pdf). 2012. №&nbsp;2.
- [Толстова Ю.Н.: «Некорректно говорить о том, что математика «прикладывается» к социологии»](files/article_content1379519133349068file.pdf). 2012. №&nbsp;1.
- [Воронков В.М.: "Я осознал себя социологом в возрасте 43 лет"](files/article_content1356939852346409file.pdf). 2011. №&nbsp;6.
- Беляев Э. [Взгляд на биографические интервью: важность нахождения паттернов](files/article_content1356939879141238file.pdf). 2011. №&nbsp;6.
- Фирсов Б. [История социологии «в лицах»: Биография и/или биокритика](files/article_content1356939895440829file.pdf). 2011. №&nbsp;6.
- Докторов Б. [К семилетию рубрики «Современная история российской социологии»](files/article_content1356939805257404file.pdf). 2011. №&nbsp;5.
- [Божков О.Б.: «Каким я был, таким остался»](files/article_content1356939738120893file.pdf). 2011. №&nbsp;4.
- [Лариса Козлова: «Мы были маргиналами, только следующее поколение получило профессию &#8219;социолог“»](files/article_content1356939756280456file.pdf). 2011. №&nbsp;4.
- Алексеев А., Ядов В., Фирсов Б. [Борису Зусмановичу Докторову 70 лет — поздравляем!](files/article_content1356760939228942file.pdf) 2011. №&nbsp;3.
- Алексеев А. [30 лет "в строю" (Мое членство в КПСС)](files/article_content1356760952287504file.pdf). 2011. №&nbsp;3.
- Шалин Д. [В поисках нарративной идентичности: К диалогу Андрея Алексеева и Дмитрия Шалина](files/article_content1356760968391295file.pdf). 2011. №&nbsp;3.
- [Т.З. Протасенко: «Становление меня как социолога шло зигзагами»](files/article_content1356760892273001file.pdf). 2011. №&nbsp;2.
- [Беспалова Ю.М. «В социологии я оказалась и случайно и неслучайно»](files/article_content1356760837426188file.pdf). 2011. №&nbsp;1.
- Докторов Б., Козлова Л., Фрумкина Р., Богданова М. [К 60-летию со дня рождения Батыгина Геннадия Семеновича](files/article_content1356760850220790file.pdf). 2011. №&nbsp;1.
- [Виктория Семенова: «Мой долгий путь к профессии»](files/article_content1328194673225129file.pdf). 2010. №&nbsp;6.
- Столович Л., Докторов Б. [Есть ли душа Петербурга в «Ленинградской социологической школе»?](files/article_content1328194692116213file.pdf) 2010. №&nbsp;6.
- Максимов Б. [Звездные часы питерской социологии](files/article_content1328194768239548file.pdf). 2010. №&nbsp;6.
- [Галина Саганенко: «Дороги хватит на всех»](files/article_content1328103382312653file.pdf). 2010. №&nbsp;5.
- Шалин Д. [«По мере созревания нравственная конфронтация становится политической» Интервью Д. Шалина с А. Алексеевым, О. Божковым, Г. Саганенко, Л.Кесельманом](files/article_content132776753370521file.pdf). 2010. №&nbsp;4.
- [Э.В.Беляев: "Естественно-научные и социальные интересы — определяющая черта моей личности"](files/article_content1327508936311085file.pdf). 2010. №&nbsp;3.
- Докторов Б. [Как это было — 5. Кто перевел книгу У. Гуда и П. Хатта? И другое](files/article_content1327508955292328file.pdf). 2010. №&nbsp;3.
- [А.Ю. Мягков «Иной судьбы для себя я просто не представлял»](files/article_content1327333518252362file.pdf). 2010. №&nbsp;2.
- Докторов Б. [Борис Грушин. Человек идеалов и идей](files/article_content132733354967512file.pdf). 2010. №&nbsp;2.
- Майор М., Пиджаков А. [Социология права Г. Д. Гурвича](files/article_content132733382041319file.pdf). 2010. №&nbsp;2.
- [А.Е. Чирикова: «Мой профессиональный выбор был правильным»](files/article_content1326732119145096file.pdf). 2010. №&nbsp;1.
- Столович Л. [Социологи в Кяэрику](files/article_content1326732139365524file.pdf). 2010. №&nbsp;1.
- Докторов Б. [Как это было. Решение задачи с 42 неизвестными](files/article_content1326732435298183file.pdf). 2010. №&nbsp;1.
- [А.А. Русалинова: «Мы работали честно и видели хоть и скромные, но результаты своего труда»](files/article_content1297504546173677file.pdf). 2009. №&nbsp;6.
- [Е.А. Здравомыслова: «Моя профессиональная жизнь характеризуется «счастливым браком» гендерных исследований с качественной методологией»](files/article_content1297504591188379file.pdf). 2009. №&nbsp;6.
- [С.А. Кугель: «Развитие науки зависит от взаимодействия социальных и когнитивных факторов»](files/article_content1297504432219577file.pdf). 2009. №&nbsp;5.
- [Б.Г. Тукумцев: «То, что я оказался в социологии, связано со счастливой случайностью и с моим интересом к проблемам управления»](files/article_content129750447925769file.pdf). 2009. №&nbsp;5.
- Докторов Б. [Пессимист по наблюдениям и оптимист по убеждениям. Научные и нравственные основы "драматической социологии"](files/article_content1297504348133098file.pdf). 2009. №&nbsp;4.
- [Борису Максимовичу Фирсову – 80 лет](files/article_content1296913470356439file.pdf). 2009. №&nbsp;3.
- [Почти 40 лет спустя.](files/article_content1296913612278476file.pdf) 2009. №&nbsp;3.
- Сымонович Ч. [Отечественная социология за полвека (заинтересованный взгляд извне)](files/article_content1296913684375764file.pdf). 2009. №&nbsp;3.
- [Н. В. Ядов: «Хочется жить в нормальной либеральной стране»](files/article_content1296913350288960file.pdf). 2009. №&nbsp;2.
- [Юбилей В.А. Ядова](files/article_content1296913394141361file.pdf). 2009. №&nbsp;2.
- Докторов Б., Козлова Л. [«Телескоп» смотрит в прошлое. Беседа об изучении истории современной российской социологии](files/article_content1296208499123748file.pdf). 2009. №&nbsp;1.
- Докторов Б., Алексеев А. [Открытое письмо группы петербургских социологов коллегам-социологам России (июль 2007)](files/article_content1230124118295578file.pdf). 2008. №&nbsp;6.
- Докторов Б. [Как это было — 3. Об анатомии коллективного действия](files/article_content1230123535264416file.pdf). 2008. №&nbsp;6.
- Божков О. [15 лет социологического изучения театральной жизни Ленинграда](files/article_content1235725504131794file.pdf). 2008. №&nbsp;6.
- [В. А. Артемов: "Время было моим главным ресурсом..."](files/article_content1235725402450840file.pdf). 2008. №&nbsp;5.
- Артемов В. [Социальное время: предвидение, исследовательски-прикладная и планово-управленческая практика](files/article_content125552196469224file.pdf). 2008. №&nbsp;5.
- [Л. В. Панова: "Самые интересные мысли были упакованы в многослойную обертку партийных документов"](files/article_content1231944637153401file.pdf). 2008. №&nbsp;4.
- Докторов Б. [Полвека служения социологии. Андрею Григорьевичу Здравомыслову – 80 лет](files/article_content123194477735911file.pdf). 2008. №&nbsp;4.
- [А. В. Баранов: "А все-таки она вертится"](files/article_content1214931332377444file.pdf). 2008. №&nbsp;3.
- [Воспоминания друзей детства о В. Б. Голофасте](files/article_content1208530437310220file.pdf). 2008. №&nbsp;2.
- [Галина Саганенко, Валерий Голофаст "Беседа о русской интеллигенции"](files/article_content1208530395122716file.pdf). 2008. №&nbsp;2.
- Докторов Б. [Валерий Голофаст. Фрагменты истории российской социологии как истории с "человеческим лицом"](files/article_content1208530346289952file.pdf). 2008. №&nbsp;2.
- Шалин Д. [Галина Саганенко и Валерий Голофаст: Гарвардское интервью](files/article_content1208530926195084file.pdf). 2008. №&nbsp;2.
- [И. И. Травин: "В социологию я пришел совершенно сознательно"](files/article_content1203611700419046file.pdf). 2008. №&nbsp;1.
- [Г. Старовойтова: "Вы слишком хорошего мнения о нашей оппозиции.Они будут расстреливать на месте на этот раз"](files/article_content1230371008241762file.pdf). 2007. №&nbsp;6.
- Докторов Б. [Галина Старовойтова. Фрагменты истории российской социологии как истории с "человеческим лицом"](files/article_content1230371054493134file.pdf). 2007. №&nbsp;6.
- [Т. И. Заславская: "Глоток свободы был слишком основательным"](files/article_content1226749684184594file.pdf). 2007. №&nbsp;5.
- [Ф. Э. Шереги: "Тогда я пришел к выводу: СССР стоит перед распадом"](files/article_content1226749726451205file.pdf). 2007. №&nbsp;5.
- [Памяти Бориса Андреевича Грушина (1929-2007)](files/article_content1226749781112354file.pdf). 2007. №&nbsp;5.
- [Б. И. Максимов: "Социолог как лошадь, скачущая в стойле"](files/article_content1223472486363463file.pdf). 2007. №&nbsp;4.
- [Л. Г. Ионин: "Надо соглашаться с собственным выбором"](files/article_content1220006132193846file.pdf). 2007. №&nbsp;3.
- [А. Б. Гофман: "Социальная реальность... - это сфера свободы"](files/article_content1218780360130100file.pdf). 2007. №&nbsp;2.
- [М. Е. Илле: "За 10 лет "Телескоп" опубликовал не менее 500 статей не менее сотни авторов"](files/article_content1213796205123467file.pdf). 2007. №&nbsp;1.
- Докторов Б. [Биографии для истории](files/article_content1213796252400955file.pdf). 2007. №&nbsp;1.
- [В. Э. Шляпентох: «Только эмпирическая социология в СССР была ареной творчества для гуманитариев»](files/article_content1211644804185600file.pdf). 2006. №&nbsp;6.
- [Человек, всю жизнь искавший «настоящую правду»](files/article_content1211645690121536file.pdf). 2006. №&nbsp;6.
- [А. Г. Здравомыслов: «Если мы не можем объяснить нечто воздействием высших сил, значит – надо искать объяснения в мире людских отношений»](files/article_content1210866897380723file.pdf). 2006. №&nbsp;5.
- [Познание через действие (так что же такое «драматическая социология»)](files/article_content1210866939113785file.pdf). 2006. №&nbsp;5.
- [Д. Л. Константиновский: «Такие вот динамические ряды…»](files/article_content1209826936482168file.pdf). 2006. №&nbsp;4.
- [Б. З. Докторов: «Мне наиболее интересны методы познания и сам исследователь…»](files/article_content12091348519627file.pdf). 2006. №&nbsp;3.
- Неймер Ю. ["Динамит в папильотках"](files/article_content1209135146171328file.pdf). 2006. №&nbsp;3.
- [Р. С. Могилевский: «Я бы назвал себя социологом-консультантом»](files/article_content1208528857428781file.pdf). 2006. №&nbsp;2.
- [Е. Э. Смирнова: «…По профессиональной части претензий не было, но инкриминировалось распечатывание гороскопов»](files/article_content1207924673177951file.pdf). 2006. №&nbsp;1.
- Божков О., Протасенко Т. [«Гляжу в себя как в зеркало эпохи» (история в документах о том, как не была допущена к печати книга «Семья в крупном городе», под редакцией В.Б. Голофаста)](files/article_content1202893457446877file.pdf). 2005. №&nbsp;6.
- Докторов Б. [Как это было – 2. Анатомия закрытия](files/article_content1203348535107750file.pdf). 2005. №&nbsp;6.
- [Л. Е. Кесельман: «…Случайно у меня оказался блокнот в клеточку»](files/article_content1202893312221433file.pdf). 2005. №&nbsp;5.
- [В. А. Ядов: «...Надо по возможности влиять на движение социальных планет...»](files/article_content1203348361424318file.pdf). 2005. №&nbsp;4.
- Батыгин Г. [Социальные науки как текст](files/article_content1202893707276790file.pdf). 2005. №&nbsp;4.
- [Я. И. Гилинский: «...Я начинал как чистый «уголовник»](files/article_content1202893614165434file.pdf). 2005. №&nbsp;2.
- Грушин Б., Пригожин А., Докторов Б., Федотова Л. [Воспоминания о Якове Самуиловиче Капелюше (1937-1990)](files/article_content1202893665366675file.pdf). 2005. №&nbsp;2.
- [Б. М. Фирсов: «… О себе и своем разномыслии»](files/article_content1202893545365654file.pdf). 2005. №&nbsp;1.
- Докторов Б. [История есть, только если она написана](files/article_content1200639339303032file.pdf). 2004. №&nbsp;5.
- Докторов Б. [Б. А. Грушин. Четыре десятилетия изучения российского общественного мнения](files/article_content1198483131163958file.pdf). 2004. №&nbsp;4.
- [Б. Грушину в его 75-летие](files/article_content119848323630877file.pdf). 2004. №&nbsp;4.
- Фирсов Б. [Два клипа к юбилею мэтра друга](files/article_content1198935665354303file.pdf). 2004. №&nbsp;4.
- Шляпентох В. [Грушин – идеальный кандидат](files/article_content1198483313337097file.pdf). 2004. №&nbsp;4.

## Размышления

- Гилинский Я. [О главных противоречиях и главных проблемах общества постмодерна](files/2018-5-04.pdf). 2018. №&nbsp;5.
- Гилинский Я. [Человеческое, слишком человеческое. Human, toohuman](files/2018-3-02.pdf). 2018. №&nbsp;3.
- Щелкин А. [Современность как откровенно социологический текст. Для его чтения надо только поменять «малое» сознание на «большое»](files/2018-1-02.pdf). 2018. №&nbsp;1.
- Иванов О. [Социальное пространство России вчера, сегодня и завтра (штрихи к портрету)](files/2017-6-04.pdf). 2017. №&nbsp;6.
- Фетисов В. [Русская революция 1917 года и становление нового типа деятельности общества](files/2017-5-04.pdf). 2017. №&nbsp;5.
- Фетисов В. [Современная эпоха: взгляд сквозь призму конвергентных процессов](files/2016-6-05.pdf). 2016. №&nbsp;6.
- Щелкин А. [Повседневность с «неповседневной» точки зрения](files/2016-5-06.pdf). 2016. №&nbsp;5.
- Иванов Д., Асочаков Ю. [Будущее как предмет социологии](files/2016-3-02.pdf). 2016. №&nbsp;3.
- Щелкин А. [Социум в поисках собственной модальности: между самопотворством и самодисциплиной](files/article_content1478173035101777file.pdf). 2015. №&nbsp;6.
- Иванов Д. [Новые конфигурации неравенства: анклавы глобальности и структуры глэм-капитализма](files/article_content1477989585438534file.pdf). 2015. №&nbsp;4.
- Майор М., Сухачев В. [Война как экзистенциал социального поля](files/article_content1477987246119853file.pdf). 2015. №&nbsp;3.
- Фетисов В. [Эволюция социологии: обретение новых смыслов и функций](files/article_content1476364634202711file.pdf). 2015. №&nbsp;1.
- Потемкин В. [Социальное действие в системе общественных отношений](files/article_content144473442940052file.pdf). 2014. №&nbsp;3.
- Фетисов В. [Раскрытие социальных функций социологии — необходимое условие ее самоидентификации](files/article_content1443694782377033file.pdf). 2014. №&nbsp;1.
- Иванов Д. [Эволюция социологии и эволюционное метатеоретизирование](files/article_content1404810898464599file.pdf). 2013. №&nbsp;4.
- Илле М. [О развлечении в искусстве, демократии и культуре ](files/article_content1404810043428630file.pdf). 2013. №&nbsp;3.
- Воронин А. [Сдвиги в фундаментных основаниях самосознания: я не мыслю, значит, я существую](files/article_content140437942420975file.pdf). 2013. №&nbsp;2.
- Фетисов В. [Деятельность как предмет исследования социологии и ее интегративный принцип](files/article_content1356939569159528file.pdf). 2011. №&nbsp;6.
- Иванов Д. [Глэм-капитализм: логика сверхновой экономики](files/article_content1356939612241411file.pdf). 2011. №&nbsp;5.
- Фетисов В. [Между Сциллой и Харибдой: проблема обретения социальной идентичности российским обществом](files/article_content1328194803274265file.pdf). 2010. №&nbsp;6.
- Фетисов В. [Сохранение через развитие - императив нашего времени](files/article_content1297505293496833file.pdf). 2009. №&nbsp;5.
- Голофаст В. [Размышления о культуре](files/article_content1296913788318891file.pdf). 2009. №&nbsp;2.
- Сергеев В. [Краеугольный камень и дом на песке. Краткое введение в теорию конструктов четвертого порядка](files/article_content1237220062283955file.pdf). 2008. №&nbsp;5.
- Фирсов Б. [Ментальные миры современного российского населения (статья третья)](files/article_content1230370767108339file.pdf). 2007. №&nbsp;6.
- Крастынь С., Майор М. ["Человек-масса" в коммуникативных ситуациях](files/article_content1230370227116861file.pdf). 2007. №&nbsp;6.
- Фетисов В. [Октябрь, социализм и современность](files/article_content1226750370403693file.pdf). 2007. №&nbsp;5.
- Иванов Д. [В режиме гламура. Общество и социальные науки начала века](files/article_content1220006185873file.pdf). 2007. №&nbsp;3.
- Голофаст В. [Социально-культурные аспекты перестройки](files/article_content1218781130367904file.pdf). 2007. №&nbsp;2.
- Фетисов В. [Социология: продолжение поисков идентичности](files/article_content1190618586307702file.pdf). 2005. №&nbsp;5.
- Голофаст В. [Мегамашины и повседневность](files/article_content1190618489488146file.pdf). 2005. №&nbsp;1.
- Илле М. [Эссе о смене эпох](files/article_content119061869145642file.pdf). 2005. №&nbsp;1.
- Фирсов Б. [Ментальные миры современного российского населения (статья 2)](files/article_content1190618411427934file.pdf). 2004. №&nbsp;5.
- Голофаст В. [Глобализация и место морали](files/article_content1190618295315877file.pdf). 2004. №&nbsp;2.
- Фирсов Б. [Ментальные миры современного российского населения](files/article_content1190013836428430file.pdf). 2003. №&nbsp;4.
- Голофаст В. [Гибридизация и культурные смеси](files/article_content1190100709279505file.pdf). 2003. №&nbsp;3.
- Ильин В. [Драматургия повседневности](files/article_content1190013631106909file.pdf). 2003. №&nbsp;2.
- Голофаст В. [Разновидности экономики и экономизм](files/article_content1259859719189632file.pdf). 2002. №&nbsp;6.
- Решетников М. [Что происходит с парламентаризмом?](files/article_content12598597504427file.pdf) 2002. №&nbsp;6.
- Соколов М. [Наступающий кризис социологического теоретизирования](files/article_content1261130053234409file.pdf). 2002. №&nbsp;5.
- Иванов Д. [Эволюция концепции глобализации](files/article_content1261130754388117file.pdf). 2002. №&nbsp;4.
- Голофаст В. [Электронная среда или новые пещерные люди](files/article_content1207925582292684file.pdf). 2002. №&nbsp;2.
- Решетников М. [Глобализация – самый общий взгляд](files/article_content1259859663230221file.pdf). 2002. №&nbsp;2.
- Голофаст В. [Глобальное и локальное как контексты и как контрасты](files/article_content1207925519320603file.pdf). 2002. №&nbsp;1.
- Алексеев А. [Эстафета памяти. Ресурсы, нормы и эффекты автобиографического повествования](files/article_content1259144472190697file.pdf). 2001. №&nbsp;4.

## Методология и методы

- Ипатова А., Рогозин Д. [Неправильные решения интервьюеров при коммуникативных сбоях в стандартизированном телефонном интервью](files/2018-4-05.pdf). 2018. №&nbsp;4.
- Кордонский С., Бардин В. [Картины мира и информационная герменевтика](files/2018-3-03.pdf). 2018. №&nbsp;3.
- Рогозин Д. [Формальная процедура определения этнографического интервью](files/2018-3-04.pdf). 2018. №&nbsp;3.
- Мальцева Д., Моисеев С. [Сетевой анализ биографических интервью: кейс Т.И. Заславской](files/2018-2-02.pdf). 2018. №&nbsp;2.
- Вырская М. [Коммуникационные сбои в стандартизованном телефонном интервью](files/2017-6-02.pdf). 2017. №&nbsp;6.
- Рогозин Д. [Зачем социологу изучать фабрикации](files/2017-5-02.pdf). 2017. №&nbsp;5.
- Рогозин Д. [Неочевидные последствия стандартизации массовых опросов](files/2017-4-02.pdf). 2017. №&nbsp;4.
- Давыдов А. [Партийная принадлежность президентов США, 1852-2016: анализ и прогнозирование](files/2017-3-03.pdf). 2017. №&nbsp;3.
- Докторов Б. [Три мониторинга президентских избирательных кампаний: 2008, 2012 и 2016 годы. Технология. Главный историко-научный вывод](files/2017-3-04.pdf). 2017. №&nbsp;3.
- Рогозин Д. [Иллюзорная прямота стандартизации в стандартизированных интервью](files/2017-3-05.pdf). 2017. №&nbsp;3.
- Мохов С. [Рынок ритуальных услуг: опыт этнографии сенситивного поля](files/2017-1-05.pdf). 2017. №&nbsp;1.
- Мальцева Д., Моисеев С., Широканова А., Брик Т. [Сетевой анализ биографических интервью: возможности и ограничения](files/2017-1-06.pdf). 2017. №&nbsp;1.
- Докторов Б. [О сделанном и перспективах ](files/2016-6-03.pdf). 2016. №&nbsp;6.
- Рогозин Д. [Дискурсивные штреки и квершлаги Бурибая: социология слухов](files/2016-4-04.pdf). 2016. №&nbsp;4.
- Могилевский Р. [Минимизация рисков при работе «по правилам». Поведение исследователя в опасной среде](files/2016-4-05.pdf). 2016. №&nbsp;4.
- Сократилин В. [Когда зацветет соломенный рейтинг, или по каким причинам не сбудутся прогнозы социологов на выборах осенью 2016 года?](files/2016-3-03.pdf) 2016. №&nbsp;3.
- Толстокорова А. [Полевые исследования гендерных аспектов трудовой миграции: этические и методологические вызовы](files/2016-2-07.pdf). 2016. №&nbsp;2.
- Лехциер В., Готлиб А. [Собственным голосом: опыт социолого-поэтического освоения нарративов](files/article_content1478173105176319file.pdf). 2015. №&nbsp;6.
- Беспалова Ю. [Нарративный поворот в социологии и проблема сохранения семейно-родовой памяти](files/article_content1477987265126635file.pdf). 2015. №&nbsp;3.
- Гегер А., Гегер С. [Проблема изучения ценностных ориентаций: поворот к микс-методам](files/article_content147798728531286file.pdf). 2015. №&nbsp;3.
- Рогозин Д. [Методология публичности Майкла Буравого](files/article_content1476967838493080file.pdf). 2015. №&nbsp;2.
- Фарахутдинов Ш. [Изучение отношения россиян к реформе образования методом анализа комментариев](files/article_content147696785799989file.pdf). 2015. №&nbsp;2.
- Штейнберг И. [Использование метафор и ассоциаций в полевых социологических исследованиях (по результатам экспедиции в городах-хозяевах Чемпионата мира по футболу 2018 года)](files/article_content147696789168249file.pdf). 2015. №&nbsp;2.
- Ипатова А. [Использование параданных в анализе телефонных опросов](files/article_content1447317841249983file.pdf). 2014. №&nbsp;6.
- Беспалова Ю. [Экзистенциальная парадигма в социологии и новые возможности ее применения](files/article_content1443694853124126file.pdf). 2014. №&nbsp;1.
- Докторов Б. [Почему в 2012 году организация Гэллапа не предсказала победу Барака Обамы?](files/article_content1443694895267727file.pdf) 2014. №&nbsp;1.
- Гегер А. [Потенциал технологии открытых вопросов в выявлении индивидуальных и групповых ценностей](files/article_content14049861893691file.pdf). 2013. №&nbsp;5.
- Мануильская К., Преснякова Л. [Как правильно задавать вопросы об изменениях цен? Методические особенности измерения инфляционных ожиданий](files/article_content1404986203111939file.pdf). 2013. №&nbsp;5.
- Османов Т., Рогозин Д. [Особенности реализации общероссийской выборки трудоспособного населения по мобильным телефонам](files/article_content1404809974409939file.pdf). 2013. №&nbsp;3.
- Докторов Б. [13 ключей к Белому дому Алана Лихтмана. По следам мониторинга президентских выборов в США 2012 года](files/article_content140437858080708file.pdf). 2013. №&nbsp;1.
- Алексеев А. [Многообразие экспликаций и синонимический ряд "наблюдающего участия" (Опыт текстологического анализа, с тяготением к историко-научному)](files/article_content138130780821523file.pdf). 2012. №&nbsp;6.
- Сократилин В. [Песня про on-line панели](files/article_content13813072386866file.pdf). 2012. №&nbsp;5.
- Божков О. [Заметки о детстве и социологии детства](files/article_content1380212991105695file.pdf). 2012. №&nbsp;4.
- Алексеев А. [Социальный опыт, общая направленность и ценностный профиль личности](files/article_content1380213011264081file.pdf). 2012. №&nbsp;4.
- Подгорная И. [Влияние формы обсуждения на обогащение образа проблемы в общественном мнении](files/article_content1380213031137892file.pdf). 2012. №&nbsp;4.
- Вьюговская Е., Ипатова А., Рогозин Д. [Схемы выдвижения в стандартизированном интервью](files/article_content1380213060383346file.pdf). 2012. №&nbsp;4.
- Шалин Д. [Проблемы мемуарной этики и достоверности биоинтервью](files/article_content138021221548918file.pdf). 2012. №&nbsp;3.
- Алексеев А. [К дискуссии о соотношении «субъективного» и «объективного» в биографическом нарративе](files/article_content1380212231357946file.pdf). 2012. №&nbsp;3.
- Шалин Д. [Дискуссия через океан. Проблемы этики натурного эксперимента: Ответ Андрею Алексееву](files/article_content1379923739468589file.pdf). 2012. №&nbsp;2.
- Алексеев А. [Дискуссия через океан. Защита наблюдающего участника](files/article_content137992374928758file.pdf). 2012. №&nbsp;2.
- Сымонович Ч. [Об изучении возрастной когорты российских ровесников Великой Отечественной войны](files/article_content1379923769300527file.pdf). 2012. №&nbsp;2.
- Готлиб А. [Качественная методология, исторический нарратив или можно ли написать историю советской социологии «с человеческим лицом»](files/article_content1379519171284216file.pdf). 2012. №&nbsp;1.
- Алексеев А. [На стыке методологических и этических проблем (Читая Дмитрия Шалина. Продолжение диалога)](files/article_content1356939153366948file.pdf). 2011. №&nbsp;5.
- Шляпентох В. [Можно ли бестрепетно доверять автобиографиям видных людей и даже массовым опросам?](files/article_content135693909876067file.pdf) 2011. №&nbsp;4.
- Фарахутдинов Ш. [Профессиональные респонденты — камень преткновения качества онлайн-опросов в современной России](files/article_content1356760642275899file.pdf). 2011. №&nbsp;2.
- Ильин В. [Интервью с социологом как исследование](files/article_content1328103414220046file.pdf). 2010. №&nbsp;5.
- Мягков А. [Восприятие респондентами метода телефонного интервью](files/article_content1327767590282289file.pdf). 2010. №&nbsp;4.
- Докторов Б. [Биография и судьба](files/article_content1327767619127252file.pdf). 2010. №&nbsp;4.
- Соколов Н., Гавра Д., Задорин И. [Нужен ли хорошему социологу внешний аудит качества?](files/article_content1327767650229652file.pdf) 2010. №&nbsp;4.
- Тарусин М. [Смотреть на все, не насилуя наблюдательности](files/article_content132750925139998file.pdf). 2010. №&nbsp;3.
- Петренко Е., Галицкая Е., Галицкий Е. [Социография: инновационная аналитическая стратегия](files/article_content1327333739127963file.pdf). 2010. №&nbsp;2.
- Дивисенко К. [Биографическое исследование жизненного мира](files/article_content1297505374260527file.pdf). 2009. №&nbsp;5.
- Докторов Б. [Что произошло в Нью-Гэмпшире?](files/article_content1297504919189312file.pdf) 2009. №&nbsp;4.
- Могилевский О. [Исследования общественного мнения в современной информационно-коммуникативной среде](files/article_content1297504947395244file.pdf). 2009. №&nbsp;4.
- Сергеев В. [Пасьянс Перентратора -2. Перентратор против Гудмена](files/article_content1296913939158542file.pdf). 2009. №&nbsp;2.
- Сергеев В. [Пасьянс Перентратора или социолог как электрик](files/article_content129620875298309file.pdf). 2009. №&nbsp;1.
- Саганенко Г., Каневский Е., Боярский К. [Контексты эмпирического познания в социологии и возможности программы ВЕГА](files/article_content1260464166454700file.pdf). 2008. №&nbsp;6.
- Щербо И. [Возможности вторичного анализа эмпирических данных](files/article_content1260464106308891file.pdf). 2008. №&nbsp;6.
- [И. Ф. Петровская: "Эпоха – не исторический фон, а партнёр человека в драме его жизни".](files/article_content125057095671311file.pdf) 2008. №&nbsp;4.
- Докторов Б. [Биография — это рассказ о прошедшем, но написанный сегодня](files/article_content1250570983204393file.pdf). 2008. №&nbsp;4.
- Докторов Б., Ядов В. [Разговоры через океан: о поколениях отечественных социологов на протяжении полувека](files/article_content121601777511087file.pdf). 2008. №&nbsp;3.
- Козлова Л. [О реконструкции истории послереволюционной социологии. Комментарий к диалогу Б. Докторова и В. Ядова](files/article_content1216017643422436file.pdf). 2008. №&nbsp;3.
- Алексеев А. [Замечание об истории социологии "с человеческим лицом"](files/article_content1216017615146483file.pdf). 2008. №&nbsp;3.
- Сергеев В. [Социальная дистанция и национальные установки](files/article_content124547934194294file.pdf). 2008. №&nbsp;2.
- [Б. Докторов: "Работа над биографиями - это общение с моими героями"](files/article_content1208533220388169file.pdf). 2008. №&nbsp;1.
- Рогозин Д. [Уровень неответов при организации конформной выборки в торговых центрах](files/article_content1234351114183970file.pdf). 2008. №&nbsp;1.
- Рогозин Д., Мануильская К. [Документарный и гуманитарный подходы к операционализации уровня образования в опросах общественного мнения](files/article_content1230370098243159file.pdf). 2007. №&nbsp;6.
- Рогозин Д., Яшина А. [Фальсификация экспертности экспертного интервью](files/article_content1223472150276408file.pdf). 2007. №&nbsp;4.
- Алексеев А. [Письмо, дневник, автобиография: многообразие форм и сопряжение смыслов (теоретико-методологические заметки)](files/article_content122071303773076file.pdf). 2007. №&nbsp;4.
- Докторов Б. [Учителя и учителя учителей. К построению траектории преемственности](files/article_content1218780823163295file.pdf). 2007. №&nbsp;2.
- Корнев Н. [Экспертиза социального измерения](files/article_content1205855576122260file.pdf). 2005. №&nbsp;4.
- Дудченко В. [Прогноз социальных реакций на планируемое социальное изменение и прикладные аспекты позиции исследователя](files/article_content1204705509306879file.pdf). 2005. №&nbsp;3.
- Алексеев А. [От синкретизма – через дифференциацию – к синтезу (об эпистемологической структуре и логике развития социологического знания)](files/article_content12012582035821file.pdf). 2004. №&nbsp;6.
- Божков О. [Век живи, век учись…](files/article_content1201258134486193file.pdf). 2004. №&nbsp;6.
- Смирнова Е. [Качественные и количественные стратегии: поле деятельности или система предпочтений?](files/article_content1200638877143226file.pdf) 2004. №&nbsp;5.
- Воронков В. [От объяснения к пониманию: в развитие дискуссии](files/article_content120063896443531file.pdf). 2004. №&nbsp;5.
- Лисовский А. [Кто сильнее – кит или слон? Или рассуждения о количественной и качественной социологии](files/article_content1200639033343359file.pdf). 2004. №&nbsp;5.
- Павленко В. [К вопросу исследования аксиологических структур социальных субъектов](files/article_content1193063874423316file.pdf). 2003. №&nbsp;5.
- Докторов Б. [Из XVII столетия в наступивший век: к становления пост-гэллаповских опросных технологий](files/article_content1194854593310773file.pdf). 2003. №&nbsp;2.
- Тертерян Р. Информационно-аналитическая составляющая рыночных исследований. Принципы работы с информацией. 2002. №&nbsp;5.
- Канаев Д. Мифы информационного рынка. 2002. №&nbsp;5.
- Уткин В., Захаров Ю., Гуца А. Духовность общества и качество жизни. 2002. №&nbsp;4.
- Уткин В., Захаров Ю., Гуца А. [К вопросу о создания интегрированной системы информационно-аналитического обеспечения деятельности администрации Санкт-Петербурга](files/2001-1-10.pdf). 2001. №&nbsp;1.
- Алексеев А. [Драматическая социология и социологическая ауторефлексия](files/article_content1225556519121396file.pdf). 2000. №&nbsp;6.

## Социально-политические исследования

- Сафронов В. [Голосование за радикальные правые партии в Европе: роль культурного изменения и партийной поляризации (Часть I)](files/2018-6-02.pdf). 2018. №&nbsp;6.
- Илле А. [Футбольные фанаты в поле политики](files/2018-3-06.pdf). 2018. №&nbsp;3.
- Горный М. [Гражданское общество в Санкт-Петербурге с 2012 г. до осени 2017 г.](files/2018-1-04.pdf) 2018. №&nbsp;1.
- Горный М. [Гражданское общество в Санкт-Петербурге: взаимодействие с властями после дефолта 1998 г. до «закручивания гаек» (до 2013 г.).](files/2017-6-03.pdf) 2017. №&nbsp;6.
- Горный М. [Гражданское общество в Санкт-Петербурге: становление и развитие коалиций некоммерческих организаций до 1998 г.](files/2017-5-03.pdf) 2017. №&nbsp;5.
- Князева Е. [Структура крымской идентичности: опыт применения бинарной логистической регрессии для построения идентификационных моделей крымчан (на материалах исследования «Открытое мнение - Крым 2016»)](files/2017-2-02.pdf). 2017. №&nbsp;2.
- Сафронов В. [Демократический протест в странах Европы: ценностные мотивации и социетальные условия](files/2016-6-02.pdf). 2016. №&nbsp;6.
- Потемкин В. [Государство, общественные отношения и легитимность власти](files/2016-4-06.pdf). 2016. №&nbsp;4.
- Воронин А. [Советский человек](files/2016-2-03.pdf). 2016. №&nbsp;2.
- Потемкин В. [Военная социология или социология войны](files/2016-2-04.pdf). 2016. №&nbsp;2.
- Сафронов В. [Неудовлетворенность граждан демократией и протест: Россия в европейском контексте](files/2016-2-05.pdf). 2016. №&nbsp;2.
- Рогозин Д. [Социальный порядок в российской исполнительной власти](files/2016-1-03.pdf). 2016. №&nbsp;1.
- Алексеев А. [О мере легитимности Правителя](files/article_content1478173144142810file.pdf). 2015. №&nbsp;6.
- Горный М. [«Ленсовету-21» — 25 лет](files/article_content1477987371293798file.pdf). 2015. №&nbsp;3.
- Сафронов В. [Политическое участие в странах Европы: общественный контекст и социально,культурные неравенства](files/article_content1476364672202438file.pdf). 2015. №&nbsp;1.
- Горный М. [Взаимоотношения институтов гражданского общества и органов власти на примере Санкт-Петербурга в начале XXI века](files/article_content144369492134491file.pdf). 2014. №&nbsp;1.
- Сафронов В. [Внимание граждан к политике в Европе и России: социальное структурирование и институциональный контекст](files/article_content1404987249423172file.pdf). 2013. №&nbsp;6.
- Докторов Б. [Президентские выборы в США 2012 года. Социологические заметки](files/article_content138130752198401file.pdf). 2012. №&nbsp;6.
- Фетисов В. [Конвергенция социальных систем - веление времени](files/article_content1381307130267149file.pdf). 2012. №&nbsp;5.
- Манаев О., Манаева Н., Юран Д. [«Острова в океане»: проблемы массовой коммуникации в социальной теории](files/article_content1380212261138832file.pdf). 2012. №&nbsp;3.
- Исаев С. [Парламентские выборы 2011 года: петербургский аспект](files/article_content1356939975140702file.pdf). 2011. №&nbsp;5.
- Горный М. [Общественные консультативные структуры при органах власти: опыт Санкт-Петербурга](files/article_content1356761233457816file.pdf). 2011. №&nbsp;2.
- Могилевский О., Рунов А. [Выборы в Законадательное собрание: политический смысл организационных решений](files/article_content1356761174119682file.pdf). 2011. №&nbsp;1.
- Сафронов В. [Поддержка политической системы в России: взгляды элиты и массовой публики (окончание)](files/article_content1326732214401603file.pdf). 2010. №&nbsp;1.
- Сафронов В. [Поддержка политической системы в России: взгляды элиты и массовой публики](files/article_content1297505517395129file.pdf). 2009. №&nbsp;6.
- Сафронов В. [Политическая культура Санкт-Петербурга: поддержка демократии элитой и массовой публикой](files/article_content12604642923090file.pdf). 2008. №&nbsp;6.
- Докторов Б. [Мониторинг президентской избирательной кампании 2008 года в США. Общие вопросы и первые результаты](files/article_content1260464242168155file.pdf). 2008. №&nbsp;6.
- Исаев С. [Петербургский электорат накануне парламентских выборов декабря 2007 года](files/article_content122675043313423file.pdf). 2007. №&nbsp;5.
- Сафронов В. [Отношение к демократии в России: конец эпохи Ельцина](files/article_content1220006265194file.pdf). 2007. №&nbsp;3.
- [Женщины в российской политике постсоветской эпохи](files/article_content1218780435122646file.pdf). 2007. №&nbsp;2.
- Кесельман Л. [Палестино-израильский конфликт в представлении россиян](files/article_content1208530006229813file.pdf). 2006. №&nbsp;2.
- Семашко Л. [Избирательное право детей, исполняемое родителями: социокультурный институт антитеррористического иммунитета](files/article_content1204298909412357file.pdf). 2005. №&nbsp;2.
- Казанцев А. [Трансформация политического ландшафта Петербурга: новый ландшафт](files/article_content1203675394384717file.pdf). 2005. №&nbsp;1.
- Кравченко В. [«Управляемая демократия» в России – миф или реальность?](files/article_content1203675443227516file.pdf) 2005. №&nbsp;1.
- Решетников М. [Демократия, терроризм и гражданское общество: тенденции, противоречия, исторические иллюзии](files/article_content1201257054119026file.pdf). 2004. №&nbsp;6.
- Федоров В. [После выборов – перед реформой: власть и общественное мнение в современной России](files/article_content1200638245373870file.pdf). 2004. №&nbsp;5.
- Сунгуров А. [Публичная политика и общественное мнение](files/article_content1200638340213805file.pdf). 2004. №&nbsp;5.
- Семашко Л. [Манифест сферной демократии: нелиберальный проект](files/article_content1200638503237172file.pdf). 2004. №&nbsp;5.
- Исаев С. [Либералиссимусы наших дней](files/article_content1203755683252487file.pdf). 2004. №&nbsp;4.
- Решетников М. [Нас ждут нескучные времена или «проблема 2004-2008»](files/article_content1197391065274050file.pdf). 2004. №&nbsp;2.
- Сафронов В. [Социальный капитал и демократия: исследования в Санкт-Петербурге](files/article_content119667265718059file.pdf). 2004. №&nbsp;1.
- Алексеев А. [Социологический комментарий к итогам выборов в Госдуму-2003](files/article_content1196672860360215file.pdf). 2004. №&nbsp;1.
- Исаев С. [Унесенные ветром](files/article_content1196672945445655file.pdf). 2004. №&nbsp;1.
- Алексеев А. [Президент третьего тысячелетия. «Желаю веселья!» (заметки о феномене талантливого патриотизма и народной любви)](files/article_content1196673144479555file.pdf). 2004. №&nbsp;1.
- Кесельман Л., Мацкевич М. [Петербург правеет?](files/article_content1193061571381788file.pdf) 2003. №&nbsp;5.
- Сафронов В. [Демократическая культура в Санкт-Петербурге: исследование политической терпимости](files/article_content1193062013246879file.pdf). 2003. №&nbsp;5.
- Илле М., Сергеев В. [Выборы в Государственную Думу](files/article_content1193061825429064file.pdf). 2003. №&nbsp;5.
- [Исследование электоральных предпочтений населения Санкт-Петербурга](files/article_content1193836033421277file.pdf). 2003. №&nbsp;4.
- Исаев С. [Парламентские выборы - по-российски](files/article_content119426910766488file.pdf). 2003. №&nbsp;3.
- Сафронов В. [В поисках либеральной культуры. Санкт-Петербург в посткоммунистический период](files/article_content1195643756388055file.pdf). 2003. №&nbsp;2.
- Савин С. [Легитимность власти как фактор стабильности современного российского общества](files/article_content1194853873381665file.pdf). 2003. №&nbsp;2.
- Кесельман Л., Мацкевич М., Васильев Г. Поколенческая трансформация политического сознания. 2002. №&nbsp;6.
- Илле А. Российские консерваторы – кто они? 2002. №&nbsp;6.
- Сафронов В. К проблеме консолидации политической демократии в России. 2002. №&nbsp;5.
- Докторов Б. Начало 2000-х: отношение петербуржцев к Америке (США). 2002. №&nbsp;3.
- Кесельман Л., Мацкевич М. Социально-структурные координаты политического сознания жителей СПб. 2002. №&nbsp;3.
- Гавра Д., Соколов Н., Мельник М., Минаков А. Политическое сознание пожилых петербуржцев: опровержение стереотипа единообразия. 2000. №&nbsp;5.
- Кесельман Л., Мацкевич М. Социально-структурные координаты губернаторской кампании в СПб. 2000. №&nbsp;2.
- Карасев В. К вопросу о сегментации политического рынка и позиционирования В. Яковлева и В. Матвиенко на выборах губернатора СПб. 2000. №&nbsp;2.
- Гавра Д., Соколов Н. Кто решит судьбу думских выборов в СПб? Эскиз портрета потенциального электората. 1999. №&nbsp;5.
- Исаев С. Выборы 99: первый прогноз результатов голосования петербуржцев по партийным спискам. 1999. №&nbsp;5.
- Илле А. Выборы в Государственную Думу-99 на страницах петербургских СМИ. 1999. №&nbsp;5.
- Могилевский Р. Социологическая поддержка избирательной кампании: условия эффективности. 1999. №&nbsp;4.
- Гавра Д., Соколов Н. Ю. Лужков и В. Яковлев: социальные позиции в СПб, сравнительный анализ. 1999. №&nbsp;4.
- Расстановка сил накануне старта предвыборной гонки «Дума-99». 1999. №&nbsp;4.
- Гавра Д., Соколов Н. Готовность к насилию в Санкт-Петербурге. 1999. №&nbsp;2.
- Божков О. К портрету идеального кандидата в депутаты Законодательного собрания Петербурга образца 1998г. 1998. №&nbsp;5.
- Гавра Д., Соколов Н. Сторонники и противники губернатора Санкт-Петербурга В. Яковлева: наброски социальных портретов. 1998. №&nbsp;5.
- Протасенко Т., Ревтова В. Год после кризиса: изменение политических симпатий петербуржцев. 1998. №&nbsp;5.
- Никто не даст нам избавленья…(экономический кризис в общественном мнении петербуржцев). 1998. №&nbsp;4.
- Выборы в Законодательное собрание начинаются. 1998. №&nbsp;4.
- Гавра Д., Соколов Н. Конец 1997 г.: позиции губернатора СПб достаточно устойчивы. 1998. №&nbsp;1.
- Духовный М., Малышев А. Контент – анализ предвыборных обещаний кандидатов в депутаты в органы местного самоуправления. 1997. №&nbsp;6.
- Протасенко Т., Фадеева О. Партийные симпатии жителей СПб. 1997. №&nbsp;5.
- Илле М. Должен ли Б. Ельцин уйти в отставку? 1997. №&nbsp;1.

## Социальные проблемы

- Панова Л., Куприянов Л. [Отдельные аспекты кадровой политики здравоохранения России и европейских стран](files/2018-5-07.pdf). 2018. №&nbsp;5.
- Сафронов В., Русинова Н. [Социальные неравенства в здоровье и психологические ресурсы личности: проект сравнительного исследования в странах Европы и России](files/2018-1-03.pdf). 2018. №&nbsp;1.
- Никитина Б. [Роль населения в организации обращения с коммунальными отходами: сравнительный анализ российских и европейских тенденций](files/2017-6-05.pdf). 2017. №&nbsp;6.
- Протасенко Т., Божков О. [Петербуржцы о теракте в метро 3 апреля 2017 г.](files/2017-3-08.pdf) 2017. №&nbsp;3.
- Толстокорова А. [«Cнова между нами города»: эмоциональные вызовы трансграничного родительства](files/2017-2-03.pdf). 2017. №&nbsp;2.
- Богомягкова Е. [Новые конфигурации социального неравенства в контексте развития биотехнологий](files/2016-2-06.pdf). 2016. №&nbsp;2.
- Бочаров В., Тукумцев Б. [Новые требования к работнику промышленного производства в условиях современной модернизации (социологический анализ)](files/article_content1477987408404132file.pdf). 2015. №&nbsp;3.
- Звоновский В., Меркулова Д., Соловьева Ю. [Материальный достаток как фактор самоидентификации профессиональной принадлежности российского врача](files/article_content1476364718428205file.pdf). 2015. №&nbsp;1.
- Сидорин А. [Представления молодежи о практиках и ценности здоровья: анализ эмпирических данных](files/article_content1476364742372087file.pdf). 2015. №&nbsp;1.
- Протасенко Т. [Петербуржцы и иногородние жители Петербурга: поиск путей бесконфликтного совместного проживания](files/article_content1446720703320816file.pdf). 2014. №&nbsp;5.
- Бояркина С., Кучина М. [Аспекты институционального функционирования социального предпринимательства](files/article_content1446551092483228file.pdf). 2014. №&nbsp;4.
- Рогозин Д. [Диссолюция бюрократии как основа коррупции](files/article_content1444734394274384file.pdf). 2014. №&nbsp;3.
- Локша А. [О необходимости повышения социальной составляющей молодежного туризма в России](files/article_content1404986246161147file.pdf). 2013. №&nbsp;5.
- Русинова Н., Сафронов В. [Социальные особенности здоровья в Европе и России: влияние индивидуальных и контекстуальных факторов ](files/article_content1404809952190703file.pdf). 2013. №&nbsp;3.
- Рогозин Д. [Кто добровольно перераспределит накопительный тариф, или долгосрочная финансовая активность населения в новых условиях пенсионных отчислений](files/article_content1404379478387211file.pdf). 2013. №&nbsp;2.
- Манзанова Г. [Особенности трансформации национального приграничного региона в условиях глобализации](files/article_content14043794878323file.pdf). 2013. №&nbsp;2.
- Григорьева И. [Старение населения, пенсионная реформа и прочие кризисы российской жизни](files/article_content1404378603143913file.pdf). 2013. №&nbsp;1.
- Клюев А., Копытов Д. [Проблема опережающего развития и научное прогнозирование в системе национальной безопасности России](files/article_content1381307318477000file.pdf). 2012. №&nbsp;5.
- Божков О., Протасенко Т. [Политика: отвлекающие маневры](files/article_content138021308718624file.pdf). 2012. №&nbsp;4.
- Сафронов В., Русинова Н. [Здоровье населения России: динамика в социальных срезах, 1994-2009 гг.](files/article_content1379923807393227file.pdf) 2012. №&nbsp;2.
- Божков О., Протасенко Т. [Однополые браки — проблема в основном политическая](files/article_content1379519310139357file.pdf). 2012. №&nbsp;1.
- Гольбрайх В. [Почему произошел «сибирский Чернобыль»? Авария на Саяно-Шушенской ГЭС в российской блогосфере](files/article_content1356940146165846file.pdf). 2011. №&nbsp;6.
- Максимов Б., Сымонович Ч. [Диалог о рабочих](files/article_content1327509182183989file.pdf). 2010. №&nbsp;3.
- Загребина А. [Опыт исследования экономического поведения в сфере пенсионного обеспечения и межпоколенческих трансфертов на примере семей петербургских студентов](files/article_content1327509217125453file.pdf). 2010. №&nbsp;3.
- Аргунова Е., Тимофеева М. [Социально-экономическое положение и самочувствие молодежи в Санкт-Петербурге](files/article_content1327333615213372file.pdf). 2010. №&nbsp;2.
- Ильин В., Проскурина Н. [Повседневная жизнь молодежи Санкт Петербурга в период кризиса](files/article_content1327333695359788file.pdf). 2010. №&nbsp;2.
- Семенков В. [О дефамилизации в семейно-демографической политике Российской Федерации](files/article_content1297505464143423file.pdf). 2009. №&nbsp;5.
- Григорьев В. [Гендерный порядок в современной России](files/article_content1297505138385681file.pdf). 2009. №&nbsp;4.
- Жирнов В. [Мировой мировоззренческий кризис](files/article_content129691428633018file.pdf). 2009. №&nbsp;3.
- Герасимчук Ю. [Кризис как фактор роста](files/article_content1296914315433398file.pdf). 2009. №&nbsp;3.
- Балыбердина И., Горлина К., Панюкова П., Чикунова А., Кинчарова А. [Симптомы кризиса и антикризисные меры на предприятиях Санкт-Петербурга](files/article_content1296914336227300file.pdf). 2009. №&nbsp;3.
- Санина А. [«В стране – кризес, а в душе весна: когнитивное конструирование кризиса](files/article_content1296914380325865file.pdf). 2009. №&nbsp;3.
- Озерова О. [Алкоголизация и смертность в современной России](files/article_content1296914111389206file.pdf). 2009. №&nbsp;2.
- Фетисов В. [Социальная стабильность российского общества: состояние и перспективы](files/article_content1255522158158300file.pdf). 2008. №&nbsp;5.
- Тукумцев Б. [Возможно ли сократить бедность среди работающих в сфере производства?](files/article_content1250571178224967file.pdf) 2008. №&nbsp;4.
- Русинова Н., Панова Л., Сафронов В. [Социальные неравенства в здоровье: тенденции в Санкт-Петербурге 1992 – 2006 гг.](files/article_content1250571211139983file.pdf) 2008. №&nbsp;4.
- Корнев Н., Коровяковский Ю. [Социо-пространственное измерение Санкт-Петербурга: жилищная картография](files/article_content1220712840230721file.pdf). 2008. №&nbsp;3.
- Еремичева Г. [Социальное неравенство - проблема интегрирующейся Европы](files/article_content1246550326348216file.pdf). 2008. №&nbsp;3.
- Соколов Н. [Петербургские домохозяйства: социальные сети и социальный капитал](files/article_content124655023540677file.pdf). 2008. №&nbsp;3.
- Гладарев Б. [Условия службы и социальное положение рядовых сотрудников милиции: социологический очерк к юбилею](files/article_content1234351469236759file.pdf). 2008. №&nbsp;1.
- Максимов Б. [Динамика занятости, доходов, социально-психологического самочувствия и ориентаций рабочих в Петербурге](files/article_content1230370334277454file.pdf). 2007. №&nbsp;6.
- Саганенко Г. [Потенциал общественных потребностей в развитии образования взрослых в современной российской ситуации](files/article_content122675050667729file.pdf). 2007. №&nbsp;5.
- Бачинин В. [Что нам стоит "Содом-2" построить? Медиасреда как зеркало русской аномии](files/article_content122000647326663file.pdf). 2007. №&nbsp;3.
- Русинова Н., Сафронов В., Панова Л. [Здоровье населения, неравенство доходов и инновационный потенциал регионов](files/article_content1211645984257954file.pdf). 2006. №&nbsp;6.
- Порецкина Е. ["Челночный" бизнес. Краткая история вопроса и его особенности в Санкт-Петербурге](files/article_content1210867019357086file.pdf). 2006. №&nbsp;5.
- Соколов Н. [Семейные деньги: бюджеты петербургских домохозяйств в 2000-2004 гг.](files/article_content1210867335390779file.pdf) 2006. №&nbsp;5.
- Корнев Н. [Товарищество собственников жилья: опыты создания. Семь случаев вне центра Петербурга](files/article_content120982706087524file.pdf). 2006. №&nbsp;4.
- Родионова А. [Товарищество собственников жилья: опыты создания. Базовый случай](files/article_content1209827116356206file.pdf). 2006. №&nbsp;4.
- Илле М. [Динамика доходов, социально-психологическое самочувствие и политические предпочтения населения Петербурга](files/article_content1209827229369335file.pdf). 2006. №&nbsp;4.
- Максимов Б., Мирошниченко Н. [Крупное промышленное предприятие в процессе реформ](files/article_content120913564753583file.pdf). 2006. №&nbsp;3.
- Исаев С. [Итоги 2005 года глазами жителей Петербурга](files/article_content120792236589988file.pdf). 2006. №&nbsp;1.
- Бачинин В. [Социальная работа христиан в российских тюрьмах](files/article_content1207922451148201file.pdf). 2006. №&nbsp;1.
- Мацкевич М. [Между солидарностью и протестом](files/article_content1207062782154833file.pdf). 2005. №&nbsp;6.
- Русинова Н., Панова Л. [Динамика осознаваемого здоровья петербуржцев за период реформ](files/article_content1207062639424345file.pdf). 2005. №&nbsp;6.
- Андрюшкина И. [Что волнует лидеров профсоюзов в год юбилея?](files/article_content1207062863381971file.pdf) 2005. №&nbsp;6.
- Решетников М. [Социальный активизм и терроризм в Европе](files/article_content1205342789285296file.pdf). 2005. №&nbsp;5.
- Сафонова А. [Ленинградская область: в поисках путей развития трудовых ресурсов региона](files/article_content1205342836405668file.pdf). 2005. №&nbsp;5.
- Решетников М. [О концепции и стратегии борьбы с наркоманиями в России](files/article_content1205855073304514file.pdf). 2005. №&nbsp;4.
- Вейхер А. [Домохозяйства Петербурга - социологическое изучение экономической дифференциации](files/article_content1204703682425502file.pdf). 2005. №&nbsp;3.
- Илле М. [Динамика уровня доходов населения Петербурга](files/article_content1204703628253917file.pdf). 2005. №&nbsp;3.
- Максимов Б. [Рабочие в Петербурге](files/article_content1204298805479519file.pdf). 2005. №&nbsp;2.
- Корнев Н. [Жилищная стратификация в центре Санкт-Петербурга](files/article_content120367507160235file.pdf). 2005. №&nbsp;1.
- Максимов Б., Дудченко В. [Авангард шахтерского движения на финише преобразования отрасли](files/article_content1203675156473872file.pdf). 2005. №&nbsp;1.
- Соколов Н. [Петербургские домохозяйства в начале 21 века](files/article_content1203675297413108file.pdf). 2005. №&nbsp;1.
- Саганенко Г. [Наркомания в российском обществе: взгляд на проблему глазами родительской организации «Азария»](files/article_content1201256297229655file.pdf). 2004. №&nbsp;6.
- Минкус И. [Общественное мнение о местном самоуправлении города](files/article_content1201256910251274file.pdf). 2004. №&nbsp;6.
- Могилевский Р., Сафонова А. [Административная реформа в России: все могут короли?](files/article_content1201256707262424file.pdf) 2004. №&nbsp;5.
- Саганенко Г., Степанова Е. [Интеграционный процесс в европейском высшем образовании](files/article_content1198935444429804file.pdf). 2004. №&nbsp;4.
- Илле М. [Доходы и социально-психологическое самочувствие населения Петербурга](files/article_content119808327225273file.pdf). 2004. №&nbsp;3.
- Иванов А., Семенков В. [О задачах культурной политики в современном обществе](files/article_content119808337243398file.pdf). 2004. №&nbsp;3.
- Мацкевич М. [Профилактика наркотизма как социальная проблема](files/article_content1198083668298467file.pdf). 2004. №&nbsp;3.
- Корнев Н. [Сегрегация по-петербургски – поиски реальности](files/article_content1197390715339144file.pdf). 2004. №&nbsp;2.
- Олимпиева И. [Малый бизнес и рынок бюрократических услуг в Санкт-Петербурге](files/article_content1197390855219202file.pdf). 2004. №&nbsp;2.
- Войцеховский В. [Особенности социальной адаптации трудового населения Ленинградской области к изменениям на рынке труда](files/article_content1196673593244701file.pdf). 2004. №&nbsp;1.
- Соколов Н., Меркурьева Ю. [Кластерный анализ профессионального поля Петербурга](files/article_content1192622248437810file.pdf). 2003. №&nbsp;6.
- Решетников М. [Бедность в современной России – анализ проблемы](files/article_content119306094098121file.pdf). 2003. №&nbsp;5.
- Могилевский Р. [Петербургские семьи: между прошлым и будущим](files/article_content1193835567443756file.pdf). 2003. №&nbsp;4.
- Соколов Н., Меркурьева Ю. [Профессиональные статусы петербуржцев: в поисках новой системы координат](files/article_content1193835797235663file.pdf). 2003. №&nbsp;4.
- Федорова Н. [Антинаркотические НКО Санкт-Петербурга](files/article_content1193835934205174file.pdf). 2003. №&nbsp;4.
- Ядов В. [Современное состояние трудовых отношений в России](files/article_content1194268969219524file.pdf). 2003. №&nbsp;3.
- Ядов В. [Динамика самоопределения граждан. Кто Я и кто Мы? Признаки преодоления травмы идентичности](files/article_content1195572534341587file.pdf). 2003. №&nbsp;1.
- Калачева О. [Празднование как индикатор социальных изменений: старые и новые праздники постсоветской России](files/article_content119557296895943file.pdf). 2003. №&nbsp;1.
- Максимов Б. [Картинки из жизни петербуржцев](files/article_content1195573418378728file.pdf). 2003. №&nbsp;1.
- Травин И., Евдокимова Е., Игнатова С., Еремичева Г., Манько Ю. Варианты экономического поведения и социально-психологическая адаптация групп населения Санкт-Петербурга, связанных с оборонным комплексом. 2002. №&nbsp;6.
- Максимов Б. Жизнь рабочих на питерском предприятии. 2002. №&nbsp;4.
- Соколов Н., Сербина С. Физическое здоровье и бедность: функциональное взаимодействие или механизм сегрегации? 2002. №&nbsp;3.
- Клюев А., Кашина М., Древаль И. [Актуальные проблемы реформы государственной власти](files/2002_2_Kluev.pdf). 2002. №&nbsp;2.
- Панова Л. [Доступность первичной медицинской помощи в оценках петербуржцев](files/2002_2_Panova.pdf). 2002. №&nbsp;2.
- Рыбина Е., Вычик Т., Дамберг С., Соколов Н. [Петербуржцы о частной собственности на землю: идеологические штампы, политико-экономические ориентации, хозяйственные практики](files/2001_1_Rybina.pdf). 2002. №&nbsp;1.
- Сафронов В. Советская система или рынок и демократия. 2001. №&nbsp;5.
- Гавра Д., Соколов Н., Родионова Е. Политическая толерантность жителей Санкт-Петербурга. 2001. №&nbsp;5.
- Федорова Н. Роль общественных организаций в решении проблем реабилитации и адаптации наркозависимых в Санкт-Петербурге. 2001. №&nbsp;5.
- Протасенко Т., Ревтова В. [Различия в уровне жизни и социальной атмосфере населения Северо-Запада России: к проблеме глобализационных трансформаций](files/2001_4_02.pdf). 2001. №&nbsp;4.
- Мацкевич М. Локализация ответственности и адаптация к постсоветской действительности. 2001. №&nbsp;3.
- Корнев Н. Доступность жилищной компенсации семьям с низким доходом и развитие ситуации с их задолженностью за жилье в 2000 г. 2001. №&nbsp;2.
- Канаев Д. [Золотой слой Петербурга](files/2001-1-04.pdf). 2001. №&nbsp;1.
- Илле М. [Много ли человеку денег надо?](files/2001-1-05.pdf) 2001. №&nbsp;1.
- Кесельман Л., Мацкевич М. [Социальные координаты наркотизма в Петербурге](files/2001-1-02.pdf). 2001. №&nbsp;1.
- Кесельман Л., Мацкевич М. Субъективная защищенность от насилия. 2000. №&nbsp;6.
- Сережина В. Рейтинги лидеров бизнеса Санкт-Петербурга. 2000. №&nbsp;6.
- Сережина В. Рейтинги лидеров бизнеса Санкт-Петербурга. 2000. №&nbsp;6.
- Протасенко Т., Ревтова В. Некоторые аспекты восприятия населением «женской» темы в контексте социально-экономических изменений. 2000. №&nbsp;6.
- Гавра Д., Соколов Н. Петербуржец как дачник и огородник – штрихи к портрету владельцев загородной недвижимости. 2000. №&nbsp;3.
- Корнев Н., Евдокимова Е. Долг петербуржцев за жилье продолжает расти. Кто виноват и что делать? 2000. №&nbsp;3.
- Протасенко Т., Ревтова В. Изменения в уровне жизни и социальная атмосфера. 2000. №&nbsp;1.
- Соколов Н. Массовое сознание против народной мудрости или чего не хватает петербуржцам для полного счастья? 2000. №&nbsp;1.
- Васильев И., Вейхер А. Население СПб – детали социально-экономического портрета. 1999. №&nbsp;6.
- Доходы и расходы петербуржцев. 1999. №&nbsp;5.
- Бизнес-барометр: оценка руководителей предприятий экономической ситуации в России. 1999. №&nbsp;4.
- Корнев Н. Мониторинг доступности жилищной компенсации нуждающимся семьям в СПб: многодетные семьи, май 1999 г. 1999. №&nbsp;4.
- Федорова Н., Фомин Э. Качество жизни в оценках городского населения России. 1999. №&nbsp;3.
- Корнев Н. Жилищные компенсации и задолженность населения по оплате жилья и коммунальных услуг в СПб. 1999. №&nbsp;2.
- Безгодов А., Соколов Н. Бизнес и предпринимательство в зеркале свободных высказываний петербуржцев. 1999. №&nbsp;1.
- «Где деньги, Зин?» (отношение петербуржцев к коммунальной реформе). 1998. №&nbsp;5.
- Герасимова Е. Массовое жилищное строительство и изменения в повседневной жизни горожан. 1998. №&nbsp;3.
- Протасенко Т., Фадеева О. Динамика уровня жизни петербуржцев за шесть лет экономических реформ. 1998. №&nbsp;2.
- Год прожили - и ладно …(результаты опроса общественного мнения, посвященного итогам 1997 года). 1998. №&nbsp;2.
- Крупнейшие открытые акционерные компании СПб. 1997. №&nbsp;6.
- Состояние и тенденции развития инвестиционных процессов в экономике СПб. 1997. №&nbsp;5.
- Гавра Д., Тишин Е. Жилищно-коммунальная реформа в общественном мнении петербуржцев. 1997. №&nbsp;5.
- Портрет активных частных инвесторов. 1997. №&nbsp;3.
- Рынок страховых услуг. 1997. №&nbsp;2.
- Божков О. Реальные проблемы современной школы в восприятии учащихся и их родителей. 1997. №&nbsp;2.
- Петербургские жители и их доходы. 1997. №&nbsp;1.

## Социокультурные исследования

- Гуревич Ю. [Как мы находим дорогу?](files/2018-6-04.pdf) 2018. №&nbsp;6.
- Романович Н. [Платоновский фестиваль и роль личности в истории города](files/2018-5-06.pdf). 2018. №&nbsp;5.
- Сымонович Ч. [Российские ровесники Войны /РВ/ — участники социальных изменений на последнем этапе советского социализма (1970-е — 1980-е гг.)](files/2018-5-08.pdf). 2018. №&nbsp;5.
- Дуков Е. [Урбанизация и новая художественная культура](files/2018-4-06.pdf). 2018. №&nbsp;4.
- Корниенко А. [Слова года в непрямом диалоге с властью](files/2018-2-03.pdf). 2018. №&nbsp;2.
- Сымонович Ч. [Советские российские ровесники Войны в культурном пространстве «зрелого социализма» (1970-е — 1980-е гг.)](files/2018-2-04.pdf). 2018. №&nbsp;2.
- Дружинин А. [Дискуссии о гражданском оружии: между наукой и медиакоммуникациями](files/2018-2-05.pdf). 2018. №&nbsp;2.
- Сымонович Ч. [Российские ровесники Войны в политической жизни СССР 1970-х — середины 1980-х гг.](files/2017-6-06.pdf) 2017. №&nbsp;6.
- Ачильдиев С. [Русский интеллигент: опыт литературно0социологического портрета](files/2017-5-05.pdf). 2017. №&nbsp;5.
- Сымонович Ч. [Российские ровесники Войны /РВ/ в 1970-е - 1980-е гг.: работники и потребители](files/2017-4-03.pdf). 2017. №&nbsp;4.
- Илле М. [Образ «идеального» петербуржца и культурная жизнь города](files/2017-4-04.pdf). 2017. №&nbsp;4.
- Свечников В. [Лекция в дистанционном обучении — какой ей быть?](files/2017-4-05.pdf) 2017. №&nbsp;4.
- Вешнинский Ю. [Ментальные основания архаизации современной российской культуры и «выбросов архаики вверх»](files/2017-3-06.pdf). 2017. №&nbsp;3.
- Равинский Д. [К истории социальной типизации женщин. «Дочь бедных, но благородных родителей»: литературная формула и социальный тип](files/2017-3-07.pdf). 2017. №&nbsp;3.
- Рыйгас Е. [Колокольное дворянство против аристократии духа](files/2017-2-04.pdf). 2017. №&nbsp;2.
- Протасенко Т., Божков О. [Что новенького? (Обзор новых практик в экономике, политике и культуре)](files/2016-6-04.pdf). 2016. №&nbsp;6.
- Дуков Е. [Урбанизация и искусство](files/2016-5-03.pdf). 2016. №&nbsp;5.
- Илле М. [Участие жителей «культурной столицы» в культурной жизни Петербурга](files/2016-5-04.pdf). 2016. №&nbsp;5.
- Алексеев А. [Моя жилищная история. Опыт тематически фокусированного автобиографического повествования](files/2016-5-05.pdf). 2016. №&nbsp;5.
- Сымонович Ч. [Общественно-политические аспекты облика и истории российских ровесников Войны (РВ) в 1960-е годы](files/2016-4-08.pdf). 2016. №&nbsp;4.
- Сымонович Ч. [Российские ровесники Войны в 1960-е годы](files/2016-3-05.pdf). 2016. №&nbsp;3.
- Илле М. [Неравенство как ценность в культуре](files/2016-1-07.pdf). 2016. №&nbsp;1.
- Дуков Е. [Киберпространство артефактов](files/article_content1478173064141768file.pdf). 2015. №&nbsp;6.
- [«Значит тебя кулаки и враги народа одурачили»: формирование языка вражды в Советской Грузии](files/article_content147817317591233file.pdf). 2015. №&nbsp;6.
- Горный М. [Возвращение городу первоначального названия Санкт-Петербург](files/article_content1478172189196126file.pdf). 2015. №&nbsp;5.
- Сымонович Ч. [Оттепель и молодёжь — российские ровесники Войны в конце 1950-х - начале 1960-х гг.](files/article_content1478172213484727file.pdf) 2015. №&nbsp;5.
- Меркулова Д., Соловьева Ю. [Образ волжских городов в массовом сознании их жителей](files/article_content1478172233390042file.pdf). 2015. №&nbsp;5.
- Равинский Д. [В поисках «красоты Петербурга»](files/article_content1478172253113656file.pdf). 2015. №&nbsp;5.
- Илле М. [Образ петербуржца в массовом сознании горожан](files/article_content1477987334259708file.pdf). 2015. №&nbsp;3.
- Сымонович Ч. [Российские ровесники Войны /РВ/ в средних классах школы (вторая половина 1950-х гг.)](files/article_content1476967930446263file.pdf). 2015. №&nbsp;2.
- Дуков Е. [Компьютер и дивидуум](files/article_content144731775757533file.pdf). 2014. №&nbsp;6.
- Ильин В. [Анатомия социального успеха в географическом пространстве](files/article_content1447317770224198file.pdf). 2014. №&nbsp;6.
- Илле М. [Интересы и информационные потребности жителей Петербурга в области истории и культуры города](files/article_content144672073735357file.pdf). 2014. №&nbsp;5.
- Равинский Д. ["Тайные памятники" Петербурга - Ленинграда](files/article_content1444734491158830file.pdf). 2014. №&nbsp;3.
- Сымонович Ч. [Российские ровесники Войны в младшем школьном возрасте (конец 1940-х - первая половина 1950-х годов)](files/article_content1444125298498750file.pdf). 2014. №&nbsp;2.
- Рогозин Д. [Как возможен осмысленный разговор о смерти](files/article_content144369481635001file.pdf). 2014. №&nbsp;1.
- Докторов Б. [Аскольд Кузьминский: его творчество знакомо миллионам, его имя знают немногие](files/article_content1404987408155498file.pdf). 2013. №&nbsp;6.
- Вешнинский Ю. [Развитие градоведческой традиции И.М. Гревса в отечественной науке](files/article_content140437953156075file.pdf). 2013. №&nbsp;2.
- Овруцкий А. [Социализация организации и коммуникативные процессы](files/article_content1404379624204057file.pdf). 2013. №&nbsp;2.
- Сымонович Ч. [К начальной истории ровесников Войны](files/article_content1404378666379919file.pdf). 2013. №&nbsp;1.
- Петрунина Л. [Два лица одного музея. «Ночь музеев» в Третьяковской галерее](files/article_content138130769851613file.pdf). 2012. №&nbsp;6.
- Беспалова Ю. [Западносибирская семейная кухня: социологический подход](files/article_content1381307269467835file.pdf). 2012. №&nbsp;5.
- Дуков Е. [Новые размышления о публике](files/article_content1380212325370515file.pdf). 2012. №&nbsp;3.
- Дмитриевский В. [Художник и власть на сломе эпох. (Режиссер Марк Захаров и другие)](files/article_content1380212352415329file.pdf). 2012. №&nbsp;3.
- Рогозин Д. [«Сейчас я никуда не хожу»: Разговорная картография Торжка и его окрестностей](files/article_content1379519194382810file.pdf). 2012. №&nbsp;1.
- Беспалова Ю. [Устойчивые выражения западносибирской семьи («семейные слова»): социологический подход](files/article_content137951921134509file.pdf). 2012. №&nbsp;1.
- Столович Л. [Слово, которое было в конце. Конкурс слов 2011 года и десятилетия 2001-2011 как материал для социологических раздумий](files/article_content1379519234295973file.pdf). 2012. №&nbsp;1.
- Дмитриевский В. [Н. Акимов и Г. Товстоногов: взаимоотношения художника и власти](files/article_content1356940388268871file.pdf). 2011. №&nbsp;6.
- Ляшев К. [Интерпретация формальных и содержательных показателей в произведениях изобразительного искусства: результаты социально)психологического исследования произведений современной украинской живописи](files/article_content1356940415302876file.pdf). 2011. №&nbsp;6.
- Столович Л. [А.З. Штейнберг и М.М. Бахтин. К истории идеи диалога](files/article_content1356940309103357file.pdf). 2011. №&nbsp;4.
- Калинина П., Анушкова Ю., Симанова Н. [Образ Петербурга глазами молодежи](files/article_content135694029335472file.pdf). 2011. №&nbsp;4.
- Петрунина Л. [Портрет посетителя Третьяковской галереи](files/article_content135676136867571file.pdf). 2011. №&nbsp;3.
- Илеуова Г. [Восприятие населением Казахстана ситуации в сфере культуры](files/article_content1356761332491740file.pdf). 2011. №&nbsp;2.
- Кулясов И., Кулясова А., Овчинников А. [Устойчивость и трансформация поморских и вепсских сообществ](files/article_content1356761293384430file.pdf). 2011. №&nbsp;1.
- Шевченко Е. [Музыка в интернете или на музыкальных телевизионных каналах? Каков выбор современного подростка?](files/article_content1327767688260677file.pdf) 2010. №&nbsp;4.
- Шляпентох В. [Элиты, а не массы — главный хранитель консерватизма и главный мотор социальных изменений в России ](files/article_content1327508993311018file.pdf). 2010. №&nbsp;3.
- Дуков Е. [Зрелище как социальный феномен](files/article_content1327509073440309file.pdf). 2010. №&nbsp;3.
- Илле М. [Культурная жизнь Петербурга в период экономического кризиса](files/article_content1326732281386799file.pdf). 2010. №&nbsp;1.
- Демина Н. [Тестирование мертоновской концепции этоса науки: случай академика Виталия Гинзбурга](files/article_content129750556767442file.pdf). 2009. №&nbsp;6.
- Беспалова Ю. [Песни семьи: возможности социологического исследования](files/article_content1297505352253011file.pdf). 2009. №&nbsp;5.
- [Анализ положения культурного обмена между Россией и Республикой Корея](files/article_content129750479371709file.pdf). 2009. №&nbsp;4.
- Рогозин Д. [Некоммуникативные порядки в разговорах о теплоснабжении](files/article_content1296914409463840file.pdf). 2009. №&nbsp;3.
- Рогозин Д. [В поисках уральской интеллигенции](files/article_content129620856160769file.pdf). 2009. №&nbsp;1.
- Демина Н. [Этос российской философии 2002-2008 гг.: контент-анализ некрологов и юбилейных статей](files/article_content129620860498808file.pdf). 2009. №&nbsp;1.
- Дивисенко К. [Представления о будущей семейной жизни в биографических текстах школьников](files/article_content1255522214378890file.pdf). 2008. №&nbsp;5.
- [Сравнение сексуальности студентов Кореи и России](files/article_content1250571254144536file.pdf). 2008. №&nbsp;4.
- Ядова М. [Российское поколение Икс: "модернисты" и "традиционалисты" (опыт пилотажного исследования)](files/article_content1246550403423850file.pdf). 2008. №&nbsp;3.
- Ильин В., Путинцева К. [Ночной клуб: драматургический подход](files/article_content1213794855239307file.pdf). 2007. №&nbsp;1.
- Лебедев Д. [Как снять квартиру в Петербурге: правила сделки на рынке арендного жилья](files/article_content1211646093390228file.pdf). 2006. №&nbsp;6.
- Санина А. ["От Восстания до Мужества – 15 минут ужаса". Петербургские маршрутки как социальный и культурный феномен](files/article_content1209827376193437file.pdf). 2006. №&nbsp;4.
- Аронсон П. [Что русскому хорошо, то немцу смерть: русские студенты в Германии о русских и немецких нормах медицины](files/article_content1208529406388183file.pdf). 2006. №&nbsp;2.
- Желнина А. [Образ города и визуальные методы социологического исследования](files/article_content1201257414203593file.pdf). 2004. №&nbsp;6.
- Гопкало О. [Символическое потребление на рынке труда](files/article_content1196673434371409file.pdf). 2004. №&nbsp;1.
- Цветаева Н. [Мотивация достижения в эпоху перемен](files/article_content1192622536361754file.pdf). 2003. №&nbsp;6.
- Панакова Я. [Питерская Чукотка: от практики к образу](files/article_content1193836153268734file.pdf). 2003. №&nbsp;4.
- Мельник И., Могилевский Р. [Guten tag, Европа! Опыт международного социологического исследования](files/article_content1194267918358066file.pdf). 2003. №&nbsp;3.
- Шанкина А. [Сравнительный анализ восприятия столиц семи федеральных округов](files/article_content1194268424426768file.pdf). 2003. №&nbsp;3.
- Алексеев И., Семенков В. [Рок-фестиваль «Окна открой»](files/article_content1195573985365478file.pdf). 2003. №&nbsp;1.
- Белов С. [Сайгон – это судьба](files/article_content1195573552423600file.pdf). 2003. №&nbsp;1.
- Кривошеев Ю., Соколов Р. [Университетские петербургские чтения](files/2001_1_Krivosheev.pdf). 2002. №&nbsp;1.
- Протасенко Т., Ревтова В. [Требуется идея для Петербурга. Лежалый товар не предлагать](files/article_content1190013029277416file.pdf). 2001. №&nbsp;6.
- Гавра Д., Соколов Н. Досуговые практики Санкт-Петербургской элиты. 2001. №&nbsp;6.
- Голофаст В. [Люди и вещи. Заметки о социально-культурных изменениях](files/article_content1190099701387286file.pdf). 2000. №&nbsp;5.
- Илле А. Рейтинг продаж книг, аудио, видеокассет, компакт-дисков. 1998. №&nbsp;6.
- Дмитревская Н. Образ города: эссе к проблеме синтеза наук. 1998. №&nbsp;6.
- Тимофеева И. Структура спроса на книги. 1998. №&nbsp;4.
- Ялышева В. Юношество и библиотека: грани соприкосновения. 1997. №&nbsp;2.

## Культурная жизнь Петербурга

- Илле М. [Петербургская аудитория концертов музыки академических жанров](files/article_content137992386498194file.pdf). 2012. №&nbsp;2.
- Илле М. [Петербуржцы и культурная жизнь города : динамика изменений - 1991-2007 гг.](files/article_content1234351274145361file.pdf) 2008. №&nbsp;1.
- Илле М. [Активность петербуржцев в потреблении художественной культуры](files/article_content1218780500350625file.pdf). 2007. №&nbsp;2.
- Глотов М., Спиридонова В. [Адаптация иногородних студентов к культуре Санкт-Петербурга](files/article_content1209135793417793file.pdf). 2006. №&nbsp;3.
- Илле М. [Петербуржцы в пространстве художественной культуры города](files/article_content1208529823296840file.pdf). 2006. №&nbsp;2.
- Семенов В. [Выражение российской полиментальности в наименованиях и архитектуре Петербурга](files/article_content120429904262500file.pdf). 2005. №&nbsp;2.
- Дунаевская Д., Смирнов А. [«Петербуржцы» и «ленинградцы» в культурном пространстве города](files/article_content1204299118218600file.pdf). 2005. №&nbsp;2.
- Хохлова А. [Город как целостность – город как подпространства: Петербург в восприятии мигрантов](files/article_content1201257329155761file.pdf). 2004. №&nbsp;6.
- Илле М. [Петербург: образ и стиль в прошлом и настоящем](files/article_content1190100499219075file.pdf). 2003. №&nbsp;3.
- Сафонова Т., Москаленко Е. [Мариинский театр: публичность и коммуникация](files/article_content1195573771224150file.pdf). 2003. №&nbsp;1.
- Илле М., Ядов Н. [Культутрный уровень петербуржцев](files/article_content1190013469130588file.pdf). 2002. №&nbsp;5.
- Рабжаева М., Семенков В. [Петербургская идентичность в прошлом и настоящем](files/2002_2_Semenkov.pdf). 2002. №&nbsp;4.
- Илле М., Ядов Н. [Идеальные петербуржцы и москвичи в представлении жителей двух столиц](files/article_content1190013322260198file.pdf). 2002. №&nbsp;3.
- Ревтова В. [Какой Петербург нам нужен?](files/2002_2_Revtova.pdf) 2002. №&nbsp;2.
- Илле М., Ядов Н. [Петербуржцы. Откуда мы родом?](files/article_content1190100341278931file.pdf) 2002. №&nbsp;1.
- Илле М., Ядов Н. [Выдающиеся петербуржцы](files/article_content119009998176616file.pdf). 2001. №&nbsp;4.
- Дмитревская Н. [Санкт-Петербург: в поисках горожанина](files/article_content1190100199461532file.pdf). 2001. №&nbsp;3.
- Илле М. [Петербуржцы и культурная жизнь города: десять лет наблюдений](files/article_content1190618035348678file.pdf). 2000. №&nbsp;5.
- Илле М. Петербуржцы в театрах, на концертах и выставках. 1998. №&nbsp;5.
- Увлечения петербуржцев. 1998. №&nbsp;3.

## Социология литературы

- Городков О. [Книга в жизни петербуржцев](files/2017-2-06.pdf). 2017. №&nbsp;2.
- Белов С. [Имена и фамилии у Достоевского](files/article_content144731790198758file.pdf). 2014. №&nbsp;6.
- Равинский Д. [«Street lit» — литературный жанр и социологический феномен](files/article_content1446720565254382file.pdf). 2014. №&nbsp;5.
- Белов С. [Числа у Достоевского](files/article_content144473455511102file.pdf). 2014. №&nbsp;3.
- Белов С. [Ф. М. Достоевский и евреи](files/article_content1356761424487790file.pdf). 2011. №&nbsp;2.
- Илле М. [О литературе массовой и классической. Или так ли уж страшен черт, как его малюют?](files/article_content1328103598205340file.pdf) 2010. №&nbsp;5.
- Илле М. [Библиотеки в культурном пространстве Санкт-Петербурга](files/article_content1327509134232419file.pdf). 2010. №&nbsp;3.
- Рабжаева М., Семенков В. [Санкт-Петербургский международный книжный салон - нерыночный феномен на книжном рынке?](files/article_content1226750262255664file.pdf) 2007. №&nbsp;5.
- Дадали Н., Илле М. [Петербург читающий](files/article_content1226750595425621file.pdf). 2007. №&nbsp;5.
- Павлова С. [Ленинградский литературный андеграунд как культурный феномен: специфика формирования и функционирования](files/article_content1197391279190905file.pdf). 2004. №&nbsp;2.
- Илле М. [Книжный рынок Петербурга](files/article_content1190619649348431file.pdf). 2004. №&nbsp;1.
- Дадали Н. [Чтение подростков Санкт-Петербурга](files/article_content1194854402451778file.pdf). 2003. №&nbsp;2.
- Илле М. [Пушкин в нашей жизни](files/article_content1190012901337985file.pdf). 1999. №&nbsp;2.

## Социология образования

- Шинко В., Шмитран Э. [Усвоение русского языка с помощью самостоятельного использования СМИ и современныхтехнологий в свободное время](files/2018-1-05.pdf). 2018. №&nbsp;1.
- Хохлова М. [Компетенции конкурентоспособного молодого специалиста: мнение работодателей и выпускников](files/article_content1444125343296635file.pdf). 2014. №&nbsp;2.
- Семенков В. [О парадоксе научной активности преподавателей гуманитарной кафедры в техническом вузе](files/article_content1444125369287369file.pdf). 2014. №&nbsp;2.
- Соколов М. [Студенческая культура, образовательные институты и политическая социализация: Беннингтонские исследования Ньюкомба](files/article_content140498737735730file.pdf). 2013. №&nbsp;6.
- Рогозин Д. [Актуальность непрерывного профессионального образования для российского бизнеса](files/article_content1404986130158999file.pdf). 2013. №&nbsp;5.
- Ежов С., Халлисте О. [Обучение в высшем учебном заведении глазами современного студента: на примере Технологического института](files/article_content138130767010256file.pdf). 2012. №&nbsp;6.
- Семенков В. [Два взгляда на ситуацию в среднем образовании США: полевое исследование Джона Гудлэда против статистического анализа Марка Пена](files/article_content1381307215439014file.pdf). 2012. №&nbsp;5.
- Доровская Н. [Массовое высшее образование, или я б в рабочие пошел... Рефератный бизнес: деньги и этика](files/article_content1328103520495931file.pdf). 2010. №&nbsp;5.
- Степанова Е. [Обсуждение успешности Болонской реформы в российском образовании](files/article_content1250571079413133file.pdf). 2008. №&nbsp;4.
- Рогозин Д., Турчик А. [Разговоры с учителями о реформах в образовании: социологическая экспедиция в школы Екатеринбурга](files/article_content1245479438338609file.pdf). 2008. №&nbsp;2.
- Зимогорова И., Сафонова А. [Проблемы профориентационной деятельности в образовательных учреждениях Санкт-Петербурга](files/article_content121379476866644file.pdf). 2007. №&nbsp;1.
- Войцеховский В. [Социокультурная среда преобразований и институализирующая роль профессионального образования в условиях изменяющегося рынка труда](files/article_content1194853383443055file.pdf). 2003. №&nbsp;2.

## Социология религии

- Дивисенко К. [Апробация краткой версии методики «Религиозный копинг» (Brief RCOPE)](files/2018-5-05.pdf). 2018. №&nbsp;5.
- Дивисенко К., Белов А., Тупахина О. [Межконфессиональные особенности практической составляющей структуры религиозного жизненного мира](files/article_content1404987315451225file.pdf). 2013. №&nbsp;6.
- Белов А. [Переосмысление понятия «профессиональная деятельность» в современном евангельском сообществе: культурно-богословские предпосылки и современная ситуация](files/article_content1381307770361262file.pdf). 2012. №&nbsp;6.
- Белов А. [Культурная типология протестантских конфессий в культурно-историческом пространстве Санкт-Петербурга](files/article_content1356940470401980file.pdf). 2011. №&nbsp;5.
- Пронякин Д. [Христианская церковь в социально-политической эволюции Европы IV-XVII вв.](files/article_content1356761451258271file.pdf) 2011. №&nbsp;2.
- Рыйгас Е. [Храм как рынок. XVI Всероссийская выставка «Православная Русь»](files/article_content1328194876471611file.pdf). 2010. №&nbsp;6.
- Тупахина О. [Общины православных домовых храмов петербургских вузов как объект социологического изучения](files/article_content1328194900258049file.pdf). 2010. №&nbsp;6.
- Подольская М. [Современная церковная лексика: проблема нормативного произношения и ее социальные последствия](files/article_content1328103630253135file.pdf). 2010. №&nbsp;5.
- Сымонович Ч. [Об интересе к исламу среди населения Санкт-Петербурга](files/article_content1223471936151009file.pdf). 2007. №&nbsp;4.
- Рыйгас Е. [Синагогальный ритуал: реконструкция смысла](files/article_content120125753745820file.pdf). 2004. №&nbsp;6.

## Исследования кино

- Илле А. [«Околофутбола»](files/article_content1443695026192398file.pdf). 2014. №&nbsp;1.
- Рогозин Д. [Постпросмотровый синдром](files/article_content1380212299448717file.pdf). 2012. №&nbsp;3.
- Рогозин Д. [Оценка погружения в кинопросмотр: «Добро пожаловать в Зомбиленд» (Рубен Флейшер, 2009)](files/article_content1356940740207515file.pdf). 2011. №&nbsp;5.
- Васильева Е. [Спецэффекты в кино: от иллюзии чуда к иллюзии реальности](files/article_content1356938872324376file.pdf). 2011. №&nbsp;4.
- Рогозин Д. [Целостность восприятия фильма-катастрофы: "2012" (Роланд Эммерих, 2009)](files/article_content1356760327104284file.pdf). 2011. №&nbsp;3.
- Илле М. [Кинотеатр в культурном пространстве Санкт-Петербурга](files/article_content1356760283380687file.pdf). 2011. №&nbsp;2.
- Рогозин Д. [Подростковый фильм глазами зрелого зрителя: "История одного вампира" (Пол Вайц, 2009)](files/article_content1356760231487973file.pdf). 2011. №&nbsp;1.
- [«Ты всему свету показал, что ад мы несем в себе!»: беседа Вадима Семенкова с Александром Исаковым о фильме Павла Лунгина «Царь»](files/article_content132733389369642file.pdf). 2010. №&nbsp;2.
- Москвина В. [Кинорынок Петербурга](files/article_content1207921825349359file.pdf). 2006. №&nbsp;1.

## Социально-психологические исследования

- Решетников М. [Клинический метод в изучении и разрешении межнациональных конфликтов](files/article_content1198083820113272file.pdf). 2004. №&nbsp;3.
- Борисов Б. [Две зарисовки с натуры (опыт наблюдающего участия)](files/article_content1201863403437442file.pdf). 2004. №&nbsp;3.
- Голубева У. [Ненужная информация или дополнительные знания? Тестирование персонала – «За» и «Против»](files/article_content1198083903142382file.pdf). 2004. №&nbsp;3.

## Прошлое и настоящее в изучении общественного мнения и рекламы

- Докторов Б. [Джордж Гэллап как российский социокультурный феномен](files/2018-2-06.pdf). 2018. №&nbsp;2.
- Мамраева Д., Ташенова Л. [Оценка деятельности интернет-магазинов глазами казахстанских покупателей](files/2016-4-07.pdf). 2016. №&nbsp;4.
- Воронцов А. [Недвижимость на локальном рынке рекламы и покупательское поведение в категории](files/2016-3-04.pdf). 2016. №&nbsp;3.
- Мамраева Д., Ташенова Л. [Оценка аттрактивности казахских туристических сайтов](files/article_content1477989726321094file.pdf). 2015. №&nbsp;4.
- Пикулёва О. [К вопросу о маркетинге и брендинге территорий](files/article_content1381307741383035file.pdf). 2012. №&nbsp;6.
- Стенина Н., Глазова Л. [Тайное оружие PR-специалистов fashion-рынка (обзор популярных PR-инструментов на примере анализа информационной активности джинсовых брендов)](files/article_content1380212509328124file.pdf). 2012. №&nbsp;3.
- Кузнецова Е. [Чемпионат мира по футболу-2010: итоги телесмотрения](files/article_content1327768133161226file.pdf). 2010. №&nbsp;4.
- Цветова Е. [Контент-анализ рекламы автомобильных компаний в глянцевых ежемесячных журналах в 2008 году](files/article_content1297505414262960file.pdf). 2009. №&nbsp;5.
- Быльева Д., Тетерина Д. [Отношение молодежной аудитории к ребрендингу компании «МТС»](files/article_content1260464350398723file.pdf). 2008. №&nbsp;6.
- Докторов Б. [Наука приходит в рекламное агентство](files/article_content1230370016234053file.pdf). 2007. №&nbsp;6.
- Докторов Б. [Клод Хопкинс. Научная реклама](files/article_content1220006429146848file.pdf). 2007. №&nbsp;3.
- Докторов Б. [Джон Уонамейкер и Джон Пауэрс. Начало многих дорог](files/article_content1211646268223812file.pdf). 2006. №&nbsp;6.
- Докторов Б. [Дэвид Огилви: рекламист на все времена](files/article_content1209827280110033file.pdf). 2006. №&nbsp;4.
- Докторов Б., Мазлумянова Н. [Рекламист в Америке – больше чем рекламист](files/article_content1208529504390814file.pdf). 2006. №&nbsp;2.
- Докторов Б. [Оцифрованные голоса поколений](files/article_content120792124560587file.pdf). 2006. №&nbsp;1.
- Докторов Б. [Альберт Ласкер: « я – всего лишь апостол очевидности»](files/article_content1207062956338077file.pdf). 2005. №&nbsp;6.
- Докторов Б. [Реклама должна продавать](files/article_content1205342942379773file.pdf). 2005. №&nbsp;5.
- Федотова Л. [Реклама в обществе - зоны риска](files/article_content1204705036393913file.pdf). 2005. №&nbsp;3.
- Федотова Л. [Реклама в фильмах](files/article_content1201257762472451file.pdf). 2004. №&nbsp;6.
- Докторов Б. [Элмо Роупер: исследователь рынка, поллстер, общественный деятель](files/article_content1198084439274710file.pdf). 2004. №&nbsp;3.
- Докторов Б. [Арчибальд Кросли – первый в изучении радиоаудитории и общественного мнения](files/article_content1196675704479520file.pdf). 2004. №&nbsp;1.
- Докторов Б. [Хедли Кэнтрил: исследователь общественного мнения и консультант президента Рузвельта](files/article_content1192622057159644file.pdf). 2003. №&nbsp;6.
- Докторов Б. [Эмиль Хурья – волшебник политического анализа](files/article_content1257325794458470file.pdf). 2002. №&nbsp;5.
- Докторов Б. [Геллаповское наследие: прошлое и настоящее одного из наиболее известных социологических индексов. Статья вторая](files/article_content1257325305250693file.pdf). 2002. №&nbsp;1.
- Докторов Б. [Гэллаповское наследие: прошлое и настоящее одного из наиболее известных социологических индексов. Статья первая](files/article_content1257325281213799file.pdf). 2001. №&nbsp;6.
- Докторов Б. [Они сильнее других хотели знать, как работает реклама (Из истории становления исследований рынка в Америке)](files/article_content1259144351374472file.pdf). 2001. №&nbsp;4.
- Докторов Б. [Джордж Гэллап: «Мне всегда нравилось изучение рекламы»](files/article_content1257324392226875file.pdf). 2000. №&nbsp;6.
- Докторов Б. [Дж. Гэллап - наш современник: к 100 летию со дня рождения](files/article_content1257324236203949file.pdf). 2000. №&nbsp;2.

## Потребительский рынок

- Бекреев А. [Застройщик из черного списка и банковская аккредитация](files/2017-2-05.pdf). 2017. №&nbsp;2.
- Кузнецова Е. [Кисломолочная продукция в России: особенности потребления категории и тенденции развития](files/article_content1379519362477942file.pdf). 2012. №&nbsp;1.
- Москвина В. [Посетители заведений быстрого питания](files/article_content1297505621432615file.pdf). 2009. №&nbsp;6.
- Подушко М. [Московский рынок товаров для ремонта и строительства](files/article_content1234351782362469file.pdf). 2008. №&nbsp;1.
- Вейхер А., Даугавет Д. [Рынок аренды нежилых помещений: некоторые данные на фоне скрытого дефицита информации](files/article_content1220006318250348file.pdf). 2007. №&nbsp;3.
- Петрова М. [Рынок товаров для ремонта и строительства Санкт-Петербурга](files/article_content122000635651455file.pdf). 2007. №&nbsp;3.
- Даугавет Д. [Грозит ли монополизация розничному рынку продовольствия?](files/article_content12187806391600file.pdf) 2007. №&nbsp;2.
- Обухова К., Подушко М. [Покупательские предпочтения розничных продуктовых торговых сетей в Санкт-Петербурге](files/article_content1209135957154232file.pdf). 2006. №&nbsp;3.
- Сократилин В. ["Боржоми" улетел, но обещал вернуться](files/article_content1209135900190979file.pdf). 2006. №&nbsp;3.
- Черемушкин А. [Потребление хлебцев жителями Санкт-Петербурга](files/article_content1205342878173627file.pdf). 2005. №&nbsp;5.
- Косатая О. [Социальное производство рисков в сфере потребления (на примере рынка алкоголя)](files/article_content1205855250250184file.pdf). 2005. №&nbsp;4.
- Илле М. [Петербургский рынок водки](files/article_content120585549515067file.pdf). 2005. №&nbsp;4.
- Волчкова Л., Ганскау Е., Минина В. [Рынок мясной продукции в Санкт-Петербурге: проблемы формирования и функционирования](files/article_content1204703916107711file.pdf). 2005. №&nbsp;3.
- Сергеев В. [Петербургский колбасный рынок](files/article_content120470374944196file.pdf). 2005. №&nbsp;3.
- Илле М. [Петербургский рынок водки](files/article_content1201257624239790file.pdf). 2004. №&nbsp;6.
- Чагин А. [Петербургский рынок пельменей](files/article_content1198482223333966file.pdf). 2004. №&nbsp;4.
- Черемушкин А., Зарайская Е. [Обзор рынка шоколадных изделий в плитках в Петербурге](files/article_content119808403390484file.pdf). 2004. №&nbsp;3.
- Семак И., Шарыгина О. [Производители мебели в Санкт-Петербурге](files/article_content1197391367125145file.pdf). 2004. №&nbsp;2.
- Семак И., Шарыгина О. [Универсамы Санкт-Петербурга](files/article_content1192622639185102file.pdf). 2003. №&nbsp;6.
- Черемушкин А. [Общие характеристики покупателей мороженого в Санкт-Петербурге](files/article_content119306239549977file.pdf). 2003. №&nbsp;5.
- Илле М. [Динамика петербургского рынка водки](files/article_content1194269227119143file.pdf). 2003. №&nbsp;3.
- Сергеев В. [Петербургский потребительский рынок сока](files/article_content1195574206188586file.pdf). 2003. №&nbsp;1.
- Голумеев Д. [Рынок пельменей в Санкт-Петербурге](files/article_content1195574351396488file.pdf). 2003. №&nbsp;1.
- Вейхер А., Даугавет Д., Баденко Д. Оценка параметров деятельности в сфере коммерческих маршрутных пассажирских перевозок в СПб. 2002. №&nbsp;6.
- Кропотов А. Петербургский рынок пельменей. 2002. №&nbsp;4.
- Смирнова Л. Туризм 2001: подводя итоги. 2002. №&nbsp;4.
- Чагин А. Петербургский рынок майонеза. 2002. №&nbsp;3.
- Андреева Е., Мендус А. [Служба 77: доставка товаров на дом](files/2002_2_Andreeva.pdf). 2002. №&nbsp;2.
- Краснов Р. [Рынок оливок в Санкт-Петербурге](files/2001_1_Krasnov.pdf). 2002. №&nbsp;1.
- Чагин А. Рынок лимонада в Свнкт-Петербурге. 2001. №&nbsp;6.
- Голумеев Д. Рынок пельменей в Санкт-Петербурге. 2001. №&nbsp;5.
- Еремичева Н., Седова М. [Дискаунтеры - это мода или будущее розничной торговли?](files/2001_4_03.pdf) 2001. №&nbsp;4.
- Андреева Е., Евсикова И. Рынок хрустящей продукции (сухие завтраки и закуски). 2001. №&nbsp;3.
- Основные тенденции девелоперского рынка СПб. 2001. №&nbsp;3.
- Краснов Р. Рынок соков СПб. 2001. №&nbsp;2.
- Шерстнев Г. [Можно ли пить заводскую водку?](files/2001-1-08.pdf) 2001. №&nbsp;1.
- Андреева Е., Шахаева Е. [Встречают по фасаду... (обзор рынка фасадных красок СПб)](files/2001-1-09.pdf). 2001. №&nbsp;1.
- Кропотов А. Рынок соков СПб. 2000. №&nbsp;6.
- Горячева Н. Исследование алкогольного рынка СПб. 2000. №&nbsp;5.
- Андреева Е., Мендус А. Перспективы использования нетрадиционных строительных материалов на рынке СПб. 2000. №&nbsp;5.
- Андреева Е., Евсикова И. Люблю я макароны (обзор рынка макаронных изделий СПб). 2000. №&nbsp;4.
- Кропотов А. Пельмени – символ возрождения российского производителя (обзор рынка пельменей СПб). 2000. №&nbsp;4.
- Осиик А. Рынок рыбных продуктов СПб. 2000. №&nbsp;3.
- Результаты экспресс-опроса владельцев иномарок. 2000. №&nbsp;3.
- Салкуцан С. Особенности потребительского спроса на мебельном рынке. 2000. №&nbsp;2.
- Андреева Е., Добрин В. Рынок недвижимости СПб: планы и предпочтения потребителей. 2000. №&nbsp;1.
- Салкуцан С. Особенности национального рынка одежды. 1999. №&nbsp;6.
- Андреева Е., Добрин В. Готовы ли потребители к инновациям в медицинской промышленности? 1999. №&nbsp;5.
- Краснов Р. Почему мы пьем сок? – обзор рынка сока СПб. 1999. №&nbsp;4.
- Салкуцан С. Рынок строительных материалов СПб. 1999. №&nbsp;4.
- Тихонова А. Рынок растительных масел. 1999. №&nbsp;3.
- Андреева Е., Добрин В. Туристический рынок в ожидании нового сезона. 1999. №&nbsp;3.
- Кропотов А. Рынок маргарина СПб. 1999. №&nbsp;2.
- Андреева Е., Добрин В. Рынок меховых изделий СПб. 1999. №&nbsp;2.
- Васильев В. Рынок продуктов быстрого приготовления СПб. 1999. №&nbsp;1.
- Обзор рынка косметики СПб. 1999. №&nbsp;1.
- Андреева Е. Исследование рынка напольных покрытий. 1998. №&nbsp;6.
- Анализ покупательских предпочтений по мебели. 1998. №&nbsp;6.
- Состояние рынка овощей в СПб и Лен.области. 1998. №&nbsp;5.
- Соколов Н., Семак И. Российский рынок алкогольных напитков: проблема измерения. 1998. №&nbsp;4.
- Андреева Е., Добрин В. Обзор потребительского рынка готовых лекарственных средств СПб. 1998. №&nbsp;4.
- Состояние и перспективы рынка картофеля в СПб и Лен. области. 1998. №&nbsp;3.
- Рынок натурального кофе СПб. 1998. №&nbsp;3.
- Продажи и потребление рыбных полуфабрикатов в СПб. 1998. №&nbsp;2.
- Рынок товаров для ремонта квартир. 1998. №&nbsp;2.
- петербургский рынок стиральных порошков. 1998. №&nbsp;2.
- Рынок растительного масла СПб. 1998. №&nbsp;1.
- Обзор розничного рынка лекарственных средств СПб. 1998. №&nbsp;1.
- СПб рынок фасованной муки. 1997. №&nbsp;6.
- Международный туризм: вчера, сегодня, завтра. 1997. №&nbsp;6.
- Петербургский рынок пива. 1997. №&nbsp;5.
- Автомобилисты Санкт-Петербурга. 1997. №&nbsp;3.
- Рынок автомобильных свечей. 1997. №&nbsp;3.
- Рынок галстуков СПб. 1997. №&nbsp;3.
- Рынок газированных напитков. 1997. №&nbsp;2.
- Петербургский рынок рыбы. 1997. №&nbsp;2.
- [Петербургский рынок хлебобулочных изделий](files/article_content1180565780299588file.doc). 1997. №&nbsp;1.

## Поведение потребителей

- Лобанова А. [«Безалкогольное пиво» или Европа по Йошкар-Олински: институциональный изоморфизм креативного пространства](files/article_content1446720657303021file.pdf). 2014. №&nbsp;5.
- Ильин В. [Товар как социальный конструкт](files/article_content1197471444159166file.pdf). 2004. №&nbsp;2.
- Чагин А. [Создание ценности для потребителя](files/article_content1193836716114013file.pdf). 2003. №&nbsp;4.
- Волчкова Л., Ганскау Е. [Образцы семейного питания как фактор формирования социальных отношений и потребительских предпочтений на рынке продовольствия](files/2001-1-07.pdf). 2001. №&nbsp;1.
- Рождественский А. Оценка существующего состояния и перспектив развития розничной торговли в СПб. 2000. №&nbsp;5.
- Волчкова Л., Минина В., Ганскау Е., Волчков А. Анализ потребительского поведения населения СПб на рынке продовольственных товаров. 1999. №&nbsp;6.

## Анализ рынка масс-медиа

- Мануильская К. [Тенденции развития рынка маркетинговых исследований в России (обзор профессиональной выставки research expo 2018)](files/2018-3-05.pdf). 2018. №&nbsp;3.
- Воронцов А. [Как петербуржцы смотрели Евро-2016](files/2016-6-06.pdf). 2016. №&nbsp;6.
- Воронцов А. [Как петербуржцы смотрели XXII зимние Олимпийские Игры](files/article_content144655120018013file.pdf). 2014. №&nbsp;4.
- Воронцов А. [Итоги телесезона 2012-2013: что смотрят петербуржцы?](files/article_content1404986276120334file.pdf) 2013. №&nbsp;5.
- Кузнецова Е. [Итоги медиа-года в Санкт-Петербурге: 2011 г. (обзор составлен на основе данных TNS Россия)](files/article_content1379923898454861file.pdf). 2012. №&nbsp;2.
- Вехов И. [Самые популярные телепрограммы 2009 года в Санкт-Петербурге](files/article_content132673186314927file.pdf). 2010. №&nbsp;1.
- Вехов И. [Основные характеристики российской Интернет-аудитории](files/article_content1297505106238557file.pdf). 2009. №&nbsp;4.
- Вехов И. [Аудитория телевидения: итоги и тенденции](files/article_content1296914189134529file.pdf). 2009. №&nbsp;2.
- Москвина В. [Основные тенденции развития радиоэфира Петербурга](files/article_content1296208674193798file.pdf). 2009. №&nbsp;1.
- Москвина В. [Газеты - изменения за 2007 год](files/article_content1245479152134692file.pdf). 2008. №&nbsp;2.
- Вехов И. [Санкт-Петербург: особенности телесмотрения](files/article_content124547907012833file.pdf). 2008. №&nbsp;2.
- Васильев И., Мамаева С. [Читатели газет в Российской национальной библиотеке](files/article_content1223472097490482file.pdf). 2007. №&nbsp;4.
- Москвина В. [Основные тенденции развития радиоэфира Петербурга](files/article_content1223472026467280file.pdf). 2007. №&nbsp;4.
- Вехов И. [Телесмотрение жителей Санкт-Петербурга: изменения в 2006 году](files/article_content1213794653217904file.pdf). 2007. №&nbsp;1.
- Попонов М. [Общая динамика телесмотрения: динамика и тенденции](files/article_content1209827341391983file.pdf). 2006. №&nbsp;4.
- Москвина В. [Аудитория радиостанций: что изменилось за год?](files/article_content1208529644444314file.pdf) 2006. №&nbsp;2.
- Обухова К. [Петербургский рынок общеинформационной и деловой прессы](files/article_content120706305925680file.pdf). 2005. №&nbsp;6.
- Москвина В. [Основные тенденции развития FM-диапазона Петербурга в первом квартале 2005 года](files/article_content120470515224029file.pdf). 2005. №&nbsp;3.
- Обухова К. [Мы все такие разные …](files/article_content120429919078739file.pdf). 2005. №&nbsp;2.
- Москвина В. [Основные тенденции развития FM диапазона Петербурга в 2004 году](files/article_content1201257911425369file.pdf). 2004. №&nbsp;6.
- Тульская М. [Петербургский рынок печатных СМИ](files/article_content1198483721214153file.pdf). 2004. №&nbsp;4.
- Обухова К. [Телевизионные предпочтения петербуржцев](files/article_content1197391518332435file.pdf). 2004. №&nbsp;2.
- Москвина В. [Обзор радиопредпочтений петербуржцев в возрасте 25-54 лет](files/article_content1196675311422107file.pdf). 2004. №&nbsp;1.
- Москвина В. [Радиорынок Петербурга: основные тенденции развития FM-диапазона](files/article_content119383644561400file.pdf). 2003. №&nbsp;4.
- Петрова О. [Телевизионная аудитория Санкт-Петербурга](files/article_content1194269410436497file.pdf). 2003. №&nbsp;3.
- Обухова К. И телевизор в каждый дом. 2002. №&nbsp;6.
- Москвина В. Радиостанции Санкт-Петербурга. 2002. №&nbsp;5.
- Сланова З. Ночь пожирателей рекламы. 2002. №&nbsp;4.
- Протасенко Т., Ревтова В. Российские журналисты – кто они? 2002. №&nbsp;3.
- Москвина В. Рынок прессы в Санкт-Петербурге. 2002. №&nbsp;3.
- Подушко М. Обзор рынка прессы в Санкт-Петербурге. 2002. №&nbsp;2.
- Казанцев А. [Телевизионная реклама: к вопросу об эффективности](files/2001_1_Kazantsev.pdf). 2002. №&nbsp;1.
- Волков А., Жигулин В. [Реклама алкоголя в прессе](files/2001_1_Volkov.pdf). 2002. №&nbsp;1.
- Москвина В. Радиостанции Петербурга. 10 лет спустя. 2001. №&nbsp;6.
- Туманова Н. Обзор рынка прессы в СПб. 2001. №&nbsp;3.
- Исаев С. Аудитория газет. 2001. №&nbsp;2.
- Москвина В. [Радиорынок СПб](files/2001-1-06.pdf). 2001. №&nbsp;1.
- Аудитории СМИ в СПБ. 2000. №&nbsp;5.
- Москвина В. Радиорынок Петербурга. 2000. №&nbsp;4.
- Газеты и журналы как рекламоносители. 2000. №&nbsp;3.
- Чагин А. Аудитория СМИ. 2000. №&nbsp;1.
- Динамика развития рынка газет. 1999. №&nbsp;6.
- Чагин А. Аудитория газет и радиостанций. 1999. №&nbsp;3.
- Весь мир у ног женщин …! (информационные предпочтения женщин). 1999. №&nbsp;2.
- Алексеев А. [Новая российская газетная пресса: типологическая структура и ее изменения (1988 – 1997 гг.)](files/article_content1202497597234485file.pdf). 1999. №&nbsp;1.
- Объект исследования – рынок СМИ. 1998. №&nbsp;6.
- Корсаков Д. Как увеличить прибыль с помощью рекламы. 1998. №&nbsp;6.
- К вопросу о выборе издания для рекламы. 1998. №&nbsp;5.
- Рейтинги и характеристики аудитории деловых газет среди населения с душевым доходом 200 долларов и более. 1998. №&nbsp;3.
- Илле А. Контент-анализ художественных фильмов, демонстритуемых на общероссийских каналах. 1998. №&nbsp;2.
- Телевизионная аудитория СПб. 1998. №&nbsp;1.
- Рейтинг радиостанций. 1997. №&nbsp;6.
- Илле А. Тематический анализ программ телеканалов. 1997. №&nbsp;5.
- Рейтинг газет. 1997. №&nbsp;3.
- Рейтинг телевизионных программ среди населения СПб с душевым доходом 200 долларов и выше. 1997. №&nbsp;2.

## Компьютеры, средства связи и информационные технологии.

- Дивисенко К. [Сайта журнала «Телескоп» в 2017 году](files/2018-1-06.pdf). 2018. №&nbsp;1.
- Дивисенко К. [Посещаемость сайта журнала «Телескоп» в 2016 году](files/2017-1-08.pdf). 2017. №&nbsp;1.
- Князева Е. [Влияние Интернета на социально-политические ориентации и социальное самочувствие молодежи (одесский опыт)](files/2016-1-04.pdf). 2016. №&nbsp;1.
- Сократилин В. [Загадки «Больших данных» или From Big Data to Куда-то…](files/2016-1-05.pdf). 2016. №&nbsp;1.
- Дивисенко К. [Сайт журнала «Телескоп» в 2015 году: аудитория и статистика посещений](files/2016-1-06.pdf). 2016. №&nbsp;1.
- Звоновский В. [Самоидентификация пользователей в онлайн-пространстве. Виртуальные личности](files/article_content1477989633124273file.pdf). 2015. №&nbsp;4.
- Белоусов К. [Сайт Санкт-Петербургского центра девиантологии "deviantology.spb.ru"](files/article_content144473460272377file.pdf). 2014. №&nbsp;3.
- Дуков Е. [Компьютер и человек](files/article_content1404810928367414file.pdf). 2013. №&nbsp;4.
- Дивисенко К. [Сайт журнала "Телескоп" в 2012 году: статистика посещений](files/article_content1404811365488347file.pdf). 2013. №&nbsp;1.
- Быльева Д. [Оценка коммуникативных качеств виртуального собеседника на основании ника и аватара](files/article_content1380212444403485file.pdf). 2012. №&nbsp;3.
- Кузнецова Е. [Всемирная паутина в цифрах. Аудитория Интернета в России](files/article_content1356760573370325file.pdf). 2011. №&nbsp;3.
- Дивисенко К. [Интернет-аудитория журнала "Телескоп" в 2010 году](files/article_content1356760518465711file.pdf). 2011. №&nbsp;1.
- Москвина В. [Пользователи социальных сетей](files/article_content1327333874323807file.pdf). 2010. №&nbsp;2.
- Дивисенко К. [Сайт журнала «Телескоп» в 2009 году](files/article_content1326731765109907file.pdf). 2010. №&nbsp;1.
- Дивисенко К. [«Телескоп» в сети Internet: статистика посещений сайта журнала](files/article_content129621039016508file.pdf). 2009. №&nbsp;1.
- Мамаева С. [Практика пользования электронными ресурсами в Российской национальной библиотеке](files/article_content1245479477378322file.pdf). 2008. №&nbsp;2.
- Чугунов А. [Развитие «электронного правительства» на российском и региональном уровнях: индикаторы и возможности мониторинга](files/article_content1213795666291410file.pdf). 2007. №&nbsp;1.
- Москвина В. [Мобильная связь: рынок приближается к насыщению](files/article_content1210867584167281file.pdf). 2006. №&nbsp;5.
- Гладарев Б. [Информационно-коммуникационные технологии – между автономией и контролем](files/article_content1207921652207629file.pdf). 2006. №&nbsp;1.
- Краснов Р. [Пользователи интернет в Петербурге](files/article_content1201258033354366file.pdf). 2004. №&nbsp;6.
- Гладарев Б. [Повседневное пользование информационно-коммуникационными технологиями](files/article_content1200638785329094file.pdf). 2004. №&nbsp;5.
- Сергеев В. [Компьютеры в семьях петербуржцев](files/article_content1198084306181394file.pdf). 2004. №&nbsp;3.
- Кравченко В. [Информационный сервис – специальность 21 века](files/article_content1197391671340545file.pdf). 2004. №&nbsp;2.
- Минкус И. [Исследование интернет-аудитории Санкт-Петербурга](files/article_content119262276364418file.pdf). 2003. №&nbsp;6.
- Сережина В. [Немного об истории развития мирового информационного рынка на примере корпорации D&B](files/article_content1193062813120848file.pdf). 2003. №&nbsp;5.
- Дорогостайский В. [Использование и возможности развития информационных коммуникационных технологий в компаниях Санкт-Петербурга](files/article_content1193063236494200file.pdf). 2003. №&nbsp;5.
- Обухова К. [Пользование компьютером в Санкт-Петербурге](files/article_content119306347020233file.pdf). 2003. №&nbsp;5.
- Обухова К. [Мобильная связь в Санкт-Петербурге](files/article_content1194855948376673file.pdf). 2003. №&nbsp;2.
- [Число пользователей Интернет в Санкт-Петербурге](files/article_content1197996734246344file.pdf). 2003. №&nbsp;2.
- Казанцев А., Сергеев В. Компьютеры и Интернет в домозозяйствах СПб. 2002. №&nbsp;5.
- Краснов Р. [Частные пользователи Интернет в Санкт-Петербурге](files/2002_2_Krasnov.pdf). 2002. №&nbsp;2.
- К вопросу об использовании Инернет в практике социологических исследований. 2001. №&nbsp;5.
- Сергеев В. Домашние компьютеры и пользование сетью Интернет. 2001. №&nbsp;2.
- Жудина Н., Соколов Н., Пиевская Д. [Петербургские ресурсы интернет: эффективность, востребованность, запросы пользователей](files/2001-1-03.pdf). 2001. №&nbsp;1.
- Салкуцан С. Интернет-провайдеры. Какие они? 2000. №&nbsp;1.
- Докторов Б., Шадрин А. Социология на российском Интернете: в начале долгого пути. 1999. №&nbsp;6.
- Создателев А. Пользователи сети интернет как особая потребительская группа. 1999. №&nbsp;5.
- Осиик А. Компьютерная техника в петербургских фирмах. 1998. №&nbsp;5.
- Домашние персональные компьютеры и пользование сетью Интернет. 1998. №&nbsp;1.
- Васильев И. Запросы корпоративных потребителей на рынке персональных компьютеров в оценках руководителей предприятий, организаций и фирм Петербурга. 1997. №&nbsp;1.

## Проблемы профессионального сообщества

- Доровская Н. [Психологические трудности в работе интервьюеров социологических колл-центров (cati) и способы их преодоления](files/2018-6-03.pdf). 2018. №&nbsp;6.
- Гуревич Л. [Способна ли казахстанская социология выйти за рамки провинциальной эмпирики?](files/2018-4-02.pdf) 2018. №&nbsp;4.
- Божков О., Протасенко Т. [Возможно ли качественное и профессиональное выполнение госзадания?](files/2018-4-03.pdf) 2018. №&nbsp;4.
- Макушева М. [Реализация исследований на заказ: о проблеме противоречия между логикой социологического исследования и сложившихся практик их проведения](files/article_content1476967958251221file.pdf). 2015. №&nbsp;2.
- Белоусов К. [Социологический конгресс 2014 года в Йокогаме (Япония)](files/article_content1446551250338061file.pdf). 2014. №&nbsp;4.
- Задорин И., Мальцева Д. [Исследование информационной культуры и профессиональной коммуникации в социологическом сообществе ](files/article_content1404810013281844file.pdf). 2013. №&nbsp;3.
- Илле М. [Список ВАК: элитарный журнальный клуб или профанация качества научных публикаций?](files/article_content140437964857056file.pdf) 2013. №&nbsp;2.
- Алексеев А. [Два "Четвертых "Всероссийских социологических конгресса" и Социологическая ассоциация России](files/article_content1356939372119236file.pdf). 2011. №&nbsp;6.
- Родионова А. [Социологи между Сциллой и Харибдой](files/article_content1328103794229151file.pdf). 2010. №&nbsp;5.
- Губа К. [Коммуникативная структура локального академического сообщества: роль внутренних интеллектуальных ресурсов](files/article_content1326731975267724file.pdf). 2010. №&nbsp;1.
- Божков О. [Задача – возрождение профессионального сообщества](files/article_content1297505182406899file.pdf). 2009. №&nbsp;4.
- Горохов В. [Записки дилетанта](files/article_content129691422038434file.pdf). 2009. №&nbsp;2.
- Демина Н. [Этос науки в перспективе В. Голофаста](files/article_content1250571042244216file.pdf). 2008. №&nbsp;4.
- Бачинин В. [Неудачный роман социологии с государством](files/article_content1220713109472049file.pdf). 2007. №&nbsp;5.
- Могилевский Р. [Прекрасный новый мир или опрос об опросах](files/article_content1200639142115372file.pdf). 2004. №&nbsp;5.
- Погорелов Ф. [Социологическое распутье: меркантильный подход](files/article_content1198935175438879file.pdf). 2004. №&nbsp;4.
- Сафонова Т. [Обольщение профессией (исследование рекрутирования молодых петербургских социологов)](files/article_content1198482757273873file.pdf). 2004. №&nbsp;4.
- Погорелов Ф., Соколов М. [Интеллектуальный ландшафт петербургской социологии: попытка картографии](files/article_content119667605189902file.pdf). 2004. №&nbsp;1.
- Докторов Б. [Сентябрьский звонок](files/article_content1192623012112843file.pdf). 2003. №&nbsp;6.
- Кесельман Л. [Давайте разберемся](files/article_content1193064194392816file.pdf). 2003. №&nbsp;5.
- Алексеев А. ["Хотели хорошего, но... не успели!"](files/article_content1194269694373333file.pdf). 2003. №&nbsp;3.
- Голод С., Дука А., Быстрова А. [О "старой гвардии", академизме и групповых интересах](files/article_content1194855327170639file.pdf). 2003. №&nbsp;2.
- Винер Б. [Развитие Социологического института РАН: решения тактические или стратегические?](files/article_content1194855627474602file.pdf) 2003. №&nbsp;2.
- Тихонов А. [О ситуации в Социологическом институте РАН и перспективах его развития](files/article_content1195574546340987file.pdf). 2003. №&nbsp;1.
- Безрукова О. Обучение на факультете социологии университета глазами студентов. 2001. №&nbsp;6.
- Протасенко Т. Прошу считать меня социологом. 2001. №&nbsp;6.
- Винер Б. [Почему петербургским социологам сегодня не нужна профессиональная ассоциация](files/2001_4_06.pdf). 2001. №&nbsp;4.
- Алексеев А. [Письмо в редакцию: эпизод из жизни СПАС](files/2001_4_07.pdf). 2001. №&nbsp;4.
- Алексеев А. [О создании Социологического института РАН на базе Санкт-Петербургского филиала Института социологии РАН (аналитическая записка)](files/article_content1202482959491803file.pdf). 2000. №&nbsp;1.

## Эссе

- Равинский Д. [Петербург — город на воде](files/2018-3-07.pdf). 2018. №&nbsp;3.
- Божков О. [Эссе о прошлом и патриотизме](files/article_content1444734640234875file.pdf). 2014. №&nbsp;3.
- Ядов В. [Мемуаризмы или заметки о поездках за рубеж](files/article_content1443542112143923file.pdf). 2014. №&nbsp;2.
- Лейбин В. [Неодинокое одиночество](files/article_content1379923165237862file.pdf). 2012. №&nbsp;2.
- Лейбина Н. [Как создавался портрет И. С. Кона](files/article_content1379923182275523file.pdf). 2012. №&nbsp;2.
- Докторов Б. [Правый поворот на красный свет светофора](files/article_content1328194841245820file.pdf). 2010. №&nbsp;6.
- Ядов В. [Итальянское турне в начале нового тысячелетия](files/article_content1327768207189532file.pdf). 2010. №&nbsp;4.
- Щелкин А. [«Есть русская интеллигенция. Вы думали - нет?»](files/article_content129750564245013file.pdf). 2009. №&nbsp;6.
- Алексеев А. [Память семейная и историческая: точки пересечения и разрывы (гипотеза о влиянии семейной памяти на мировосприятие)](files/article_content1255522008101292file.pdf). 2008. №&nbsp;5.
- Корнев Н. [Коготок - увяз... (эссе о явлении синергетики в социальное пространство)](files/article_content1220973124122233file.pdf). 2008. №&nbsp;2.

## Полемические заметки

- Щелкин А. [ДОИГРАЛИСЬ — лозунг дня:"Даешь гламурную социологию!"](files/article_content1356939234161543file.pdf). 2011. №&nbsp;4.
- Щелкин А. [Российская цивилизация предполагает дискуссию о российской цивилизации](files/article_content1356760753301667file.pdf). 2011. №&nbsp;1.
- Браславский Р. [По поводу "полемических заметок" А. Щелкина](files/article_content1328103701104361file.pdf). 2010. №&nbsp;5.
- Щелкин А. [Берегите цивилизацию от... социологов](files/article_content1327509282113016file.pdf). 2010. №&nbsp;3.
- Гольберт В. [Инновационная маркетизация общества: российский вариант](files/article_content1234351327197017file.pdf). 2008. №&nbsp;1.
- Бачинин В. [Новый цезарепапизм, панихида по демократии и наше не состоявшееся духовное возрождение](files/article_content1220712908361685file.pdf). 2008. №&nbsp;1.

## Информация, сообщения

- Божков О. [33 экспедиционных дня 2018 года (заметки с социологического поля)](files/2018-6-05.pdf). 2018. №&nbsp;6.
- [Содержание 1-6 номеров журнала за 2018 год](files/2018-6-07.pdf). 2018. №&nbsp;6.
- Божков О. [XV международная научно-практическая конференция в Каргополе](files/2018-5-10.pdf). 2018. №&nbsp;5.
- Божков О. [Международному симпозиуму «Пути России» 25 лет](files/2018-3-08.pdf). 2018. №&nbsp;3.
- Божков О. [X социологические чтения памяти В.Б. Голофаста](files/2018-3-09.pdf). 2018. №&nbsp;3.
- Старовойтова О. [Конкурс «Галатея» памяти Г.В. Старовойтовой](files/2018-1-08.pdf). 2018. №&nbsp;1.
- [X чтения памяти Валерия Борисовича Голофаста](files/2018-1-09.pdf). 2018. №&nbsp;1.
- [«Социологи до нас ничего подобного в Украине не получали»](files/2017-5-07.pdf). 2017. №&nbsp;5.
- Божков О. [Социальные и пространственные измерения современного мегаполиса](files/2017-3-09.pdf). 2017. №&nbsp;3.
- Божков О. [Шестой Методологический семинар памяти Г.С. Батыгина. «Эвристический потенциал социального знания: потребности общества и возможности науки»](files/2017-3-10.pdf). 2017. №&nbsp;3.
- [Пятый Всероссийский социологический конгресс](files/2016-6-07.pdf). 2016. №&nbsp;6.
- [Стажировка в Гарвардском университете](files/2016-5-07.pdf). 2016. №&nbsp;5.
- Божков О. [Непростая география России](files/2016-3-06.pdf). 2016. №&nbsp;3.
- [Наш человек — в руководстве The Gallup International Association](files/2016-2-08.pdf). 2016. №&nbsp;2.
- Божков О. [О Всероссийских Чтениях памяти В.А. Ядова](files/2016-1-08.pdf). 2016. №&nbsp;1.
- [Содержание 1 - 6 номеров журнала за 2015 год](files/article_content1452598850152914file.pdf). 2015. №&nbsp;6.
- Божков О. [Социальные проблемы российского села и аграрных отношений](files/article_content1477987437323211file.pdf). 2015. №&nbsp;3.
- Дивисенко К. [Интернет-аудитория сайта журнала "Телескоп" в 2014 году](files/article_content1476365191444360file.pdf). 2015. №&nbsp;1.
- Николаенко Г., Евсикова Е. [Прошлое через призму настоящего. VIII социологические чтения памяти В.Б. Голофаста](files/article_content1476364882122032file.pdf). 2015. №&nbsp;1.
- [Содержание 1 - 6 номеров журнала за 2014 год](files/article_content141970140434562file.pdf). 2014. №&nbsp;6.
- Земнухова Л., Лапина В. [Летняя школа факультета политических наук и социологии Европейского университета в Санкт-Петербурге «Университет без Профессоров» как новый образовательный формат](files/article_content1446720780288227file.pdf). 2014. №&nbsp;5.
- Божков О. [7-е социологические чтения памяти В.Б. Голофаста. СПб, 26-29 марта 2014 г.](files/article_content1444734692448856file.pdf) 2014. №&nbsp;3.
- Божков О., Игнатова С. [Две конференции: пессимистично и немного оптимизма](files/article_content144473470356145file.pdf). 2014. №&nbsp;3.
- Карапетян Р. [О прошедшей в Санкт-Петербурге Всероссийской научно-практической конференции "Современное общество и труд"](files/article_content1444125406217809file.pdf). 2014. №&nbsp;2.
- Протасенко Т., Божков О. [Откуда вышли опросы общественного мнения?](files/article_content1444125424187890file.pdf) 2014. №&nbsp;2.
- Дивисенко К. [Сайт журнала "Телескоп" в 2013 году](files/article_content1443694983493587file.pdf). 2014. №&nbsp;1.
- [Содержание 1 - 6 номеров журнала за 2013 год](files/article_content1388148114202554file.pdf). 2013. №&nbsp;6.
- Божков О. [Кому (или чему) должна служить наука?](files/article_content140481115514825file.pdf) 2013. №&nbsp;4.
- Седова Н. [Обзор III международной социологической конференции «продолжая Грушина»](files/article_content1404379677225033file.pdf). 2013. №&nbsp;2.
- Сымонович Ч. [К 50-му материалу рубрики Б. Докторова](files/article_content1404378739408706file.pdf). 2013. №&nbsp;1.
- Родионова А. [Новые надежды (Выборы правления Санкт-Петербургской ассоциации социологов)](files/article_content1381307839150890file.pdf). 2012. №&nbsp;6.
- [Содержание 1 – 6 номеров журнала за 2012 год](files/article_content1356166677498284file.pdf). 2012. №&nbsp;6.
- Родионова А. [Продолжение следует... в октябре](files/article_content1380213113102008file.pdf). 2012. №&nbsp;4.
- Илле М., Дивисенко К. [Журналу «Телескоп» — 15 лет!](files/article_content1379519393195725file.pdf) 2012. №&nbsp;1.
- Глотов М. [V Голофастовские чтения](files/article_content1356760152330860file.pdf). 2011. №&nbsp;3.
- [Научно-практический семинар "Методы и технологии социологических и маркетинговых исследований](files/article_content1356760097158108file.pdf). 2011. №&nbsp;1.
- [Содержание 1 - 6 номеров журнала за 2010 год](files/article_content1297505923354630file.pdf). 2010. №&nbsp;6.
- Божков О. [Социология вчера, сегодня, завтра. Четвертые чтения памяти Валерия Голофаста](files/article_content1327333919182019file.pdf). 2010. №&nbsp;2.
- Божков О. [От юбилея до юбилея недалеко](files/article_content1297505802407351file.pdf). 2009. №&nbsp;6.
- [Содержание 1-6 номеров журнала за 2009 год ](files/article_content126096216653841file.pdf). 2009. №&nbsp;6.
- [Социологические чтения памяти Валерия Борисовича Голофаста](files/article_content129691450172540file.pdf). 2009. №&nbsp;3.
- [Содержание 1 — 6 номеров журнала за 2008 год](files/article_content1229078565245058file.pdf). 2008. №&nbsp;6.
- Могилевский О. [Петербург стремится к мировым стандартам исследований](files/article_content1255522067487248file.pdf). 2008. №&nbsp;5.
- Родионова А. [К итогам отчетно-выборного собрания СПАС](files/article_content1226749955240967file.pdf). 2007. №&nbsp;5.
- [Устав Санкт-Петербургской научной общественной организации социологов "СПАС"](files/article_content122347182618256file.pdf). 2007. №&nbsp;4.
- Травин И. [Социологические чтения памяти В. Б. Голофаста](files/article_content1218781005395824file.pdf). 2007. №&nbsp;2.
- Кравец Н. [Итоги конкурса публикаций](files/article_content1218781029204054file.pdf). 2007. №&nbsp;2.
- Родионова А. [Итоги работы Санкт-Петербургской ассоциации социологов в 2005-2006 гг.](files/article_content1210867999308933file.pdf) 2006. №&nbsp;5.
- [Положение о конкурсе публикаций ученых Северо-Запада в области социологии](files/article_content1207063403419853file.pdf). 2005. №&nbsp;6.
- Новинки и бестселлеры по социологии и маркетингу. 2005. №&nbsp;5.
- Семашко Л. [Социология детства во всех аспектах](files/article_content1205343139419351file.pdf). 2005. №&nbsp;5.
- [Положение о конкурсе студенческих работ](files/article_content1205343183463748file.pdf). 2005. №&nbsp;5.
- [Информация о конференции «Коммуникативные традиции, технологии, тенденции»](files/article_content120534323661826file.pdf). 2005. №&nbsp;5.
- Кравец Н. [Отчетно-выборное собрание Санкт-Петербургской ассоциации социологов](files/article_content1204705326288120file.pdf). 2005. №&nbsp;3.
- [Петербург глазами молодых ученых (по итогам конференции молодых ученых "Социальное и культурное пространство города")](files/article_content1201258383349859file.pdf). 2004. №&nbsp;6.
- [Международная научно-практическая конференция "Власть и общественное мнение"](files/article_content1198483907300235file.pdf). 2004. №&nbsp;4.
- Семашко Л. [Пекин. Всемирный социологический конгресс. Мосты между Востоком и Западом. Гармония идет с Востока](files/article_content1198935981108277file.pdf). 2004. №&nbsp;4.
- Докучаева И. [Санкт-Петербургская ассоциация социологов в цифрах](files/article_content1194270079308338file.pdf). 2003. №&nbsp;3.
- Еремичева Г. [Последнее собрание СПАС глазами очевидца](files/article_content1194270532249656file.pdf). 2003. №&nbsp;3.
- Кравец Н. [Итоги конкурса публикаций](files/article_content1196671559129878file.pdf). 2003. №&nbsp;1.
- [Информационный архив журнала "Телескоп"](files/2001_4_09.pdf). 2001. №&nbsp;4.
- Скворцов Н. [Теперь вместе](files/2001-1-01.pdf). 2001. №&nbsp;1.
- Родионова А. Об итогах конкурса студенческих работ "Галатея". 2000. №&nbsp;6.
- Родионова А. Собрание Санкт-Петербургской ассоциации социологов. 2000. №&nbsp;3.
- Родионова А. Социология и выборы. 2000. №&nbsp;1.
- Устав СПб ассоциации социологов. 2000. №&nbsp;1.
- Кодекс профессиональной этики СПб ассоциации социологов. 2000. №&nbsp;1.
- Положение о почетных членах СПАС. 2000. №&nbsp;1.
- Костюшев В. Санкт-Петербургская ассоциация социологов: итоги-1999, проекты-2000. 2000. №&nbsp;1.

## Рецензии

- Винер Б. [Приключения в поисках национальности](files/2018-4-07.pdf). 2018. №&nbsp;4.
- Долинина М. [О книге Дженнифер Хиллман «Сексуальность и старение»](files/2016-6-08.pdf). 2016. №&nbsp;6.
- Божков О. [Три грустных песни о том, как государство «сливало» промышленность и рабочий класс](files/2016-3-07.pdf). 2016. №&nbsp;3.
- Рогозин Д. [Семь уроков христианского старения](files/article_content1478172303118311file.pdf). 2015. №&nbsp;5.
- Докторов Б. [«Обращение к себе» и множество вопросов к себе](files/article_content1444736541221270file.pdf). 2014. №&nbsp;3.
- Протасенко Т. [Социология — не руководство к действию, не инструкция по применению, а лишь повод для размышления (Рецензия на книгу "От плебисцита — к выборам. Как и почему россияне голосовали на выборах 2011-2012 гг.»)](files/article_content1404986309331378file.pdf). 2013. №&nbsp;5.
- Божков О. [История нашей социологии — свидетельства действующих лиц](files/article_content1380212531373351file.pdf). 2012. №&nbsp;3.
- Костюковский Я. [«Милиция и этнические мигранты. Практики взаимодействия». Рецензия на книгу](files/article_content135693964896910file.pdf). 2011. №&nbsp;5.
- Докторов Б. [Борис Грушин: начало постбиографии](files/article_content1328103922294913file.pdf). 2010. №&nbsp;5.
- Докторов Б. [Юрий Левада. Портрет для потомков. В связи с выходом книги «Воспоминания и дискуссии о Юрии Александровиче Леваде»](files/article_content1327768603125548file.pdf). 2010. №&nbsp;4.
- Травин И. [М.Б. Глотов. Структурный анализ общества](files/article_content132733395625413file.pdf). 2010. №&nbsp;2.
- Шереги Ф. [Размышления о книге Владимира Шляпентоха «Современная Россия как феодальное общество»](files/article_content1326732024396674file.pdf). 2010. №&nbsp;1.
- Гусман Л. [Рецензия на книгу Веременко В. А. "Дворянская семья и государственная политика России (вторая половина XIX - начало XX вв.)"](files/article_content1230370266395065file.pdf). 2007. №&nbsp;6.
- Юхнева Н. [Письмо по поводу рецензии на книгу "Многонациональный Петербург. История. Религии. Народы"](files/article_content1198483612373361file.pdf). 2004. №&nbsp;4.
- Семашко Л. [Смыслы культурной социологии (Рецензия на книгу Д. Александера. Смыслы социальной жизни. Культурная социология)](files/article_content119739217415666file.pdf). 2004. №&nbsp;2.
- Миронов Б. [Галина Старовойтова - продолжение жизни](files/article_content1193837847214860file.pdf). 2003. №&nbsp;6.
- Семенков В. [Мусаев В. И. Преступность в Петрограде в 1917-1921 гг. и борьба с ней](files/article_content1193838835436770file.pdf). 2003. №&nbsp;4.
- Семенков В., Евстигнеев Ю., Дамберг С. [Многонациональный Петербург. История. Религия. Народы](files/article_content1196672208460831file.pdf). 2003. №&nbsp;3.
- Кавторин В. [Нужна ли социологии "большая теория"?](files/article_content1195575677412366file.pdf) 2003. №&nbsp;1.
- Семенков В. [Рецензия на книгу Б. Хазард. Рядом с Невским проспектом. Моя жизнь среди неофициальных художников Ленинграда](files/2001_4_08.pdf). 2001. №&nbsp;4.

## Книжная полка

- Докторов Б. [Григорьева Е.И., Ситдиков И.М. Электронные издания. Технология подготовки: учебное пособие для бакалавриата и специалиста.](files/2018-3-11.pdf) 2018. №&nbsp;3.
- Лурье С. [Плач по оскудевающей родине…(рецензия)](files/2018-1-07.pdf). 2018. №&nbsp;1.
- Божков О. [Куда идет современная социология?](files/2017-5-08.pdf) 2017. №&nbsp;5.
- [Книжная полка](files/2017-4-06.pdf). 2017. №&nbsp;4.
- Кальной И. [Общество рассчитывает на социологию. Социология — на общество](files/2017-1-09.pdf). 2017. №&nbsp;1.
- [Социум рождается ежедневно и как бы заново…](files/2017-1-10.pdf). 2017. №&nbsp;1.
- Алексеев А. [Историко-биографические поиски и открытия Бориса Докторова](files/article_content1476364857275833file.pdf). 2015. №&nbsp;1.
- Крокинская О. [«Практика — это то, что я могу понять»](files/article_content1447317952249923file.pdf). 2014. №&nbsp;6.
- Докторов Б. [Ориентир — классика. Без алармизма об очень важном](files/article_content1447317978157228file.pdf). 2014. №&nbsp;6.
- Докторов Б. [«Социологи России». Книга новая, необходимая, но трудно доступная](files/article_content1446551567420025file.pdf). 2014. №&nbsp;4.
- [К 85-летию со дня рождения Б. А. Грушина](files/article_content1444125450342952file.pdf). 2014. №&nbsp;2.
- Божков О. [Прошло сто лет. К чему пришли?](files/article_content1444125471430753file.pdf) 2014. №&nbsp;2.
- Смирнова Е. [Борис Докторов. Современная российская социология. История в биографиях и биографии в истории](files/article_content1443694950391992file.pdf). 2014. №&nbsp;1.
- Божков О. [Прошло сто лет... (о состоянии современной — не только российской — социологии)](files/article_content1404987464191542file.pdf). 2013. №&nbsp;6.
- Поляков Л. [Социология и культура: порядок слов](files/article_content1404811190183871file.pdf). 2013. №&nbsp;4.
- Корниенко А. [Отклик на книгу «Театр и публика: опыт социологического исследования 1960-1970-х годов»](files/article_content1404811209216597file.pdf). 2013. №&nbsp;4.
- Козлова Л. [Биографии российских социологов: самопознание и образ социологии](files/article_content138130734228397file.pdf). 2012. №&nbsp;5.
- Докторов Б. [Борис Раббот и страницы истории, которые нам еще предстоит узнать](files/article_content1381307398366301file.pdf). 2012. №&nbsp;5.
- [О президентской избирательной кампании 2008 года в США](files/article_content1356760458303443file.pdf). 2011. №&nbsp;1.
- [Книжная полка](files/article_content1356760437462161file.pdf). 2011. №&nbsp;1.
- Зарин М. [Социальная революция под музыку рингтонов](files/article_content1220006574357129file.pdf). 2007. №&nbsp;3.
- Желнина А. [Обзор новых книг для социологов](files/article_content1213795766256867file.pdf). 2007. №&nbsp;1.
- Желнина А. [Обзор новых книг для социологов](files/article_content1207924301450246file.pdf). 2006. №&nbsp;6.
- Новинки и бестселлеры по социологии и маркетингу. 2006. №&nbsp;6.
- Божков О. [О важности и смысле исторических свидетельств. Рецензия на книгу Б. Докторова «Отцы –основатели: история изучения общественного мнения »](files/article_content1210867786168724file.pdf). 2006. №&nbsp;5.
- Девит М. [Тетрасоциология как социальная теория и практика для 21 века: строительство культуры мира из естественного порядка социальной гармонии. Рецензия на книги Л.М. Семашко](files/article_content1208530308416129file.pdf). 2006. №&nbsp;2.
- Гавра Д. [Рецензия на книгу: Головин Н.А. «Теоретико-методологические основы исследования политической социализации»](files/article_content1207921373183270file.pdf). 2006. №&nbsp;1.
- Федотова Л. [От Гэллапа к Грушину: приглашение к размышлениям](files/article_content1207063297417485file.pdf). 2005. №&nbsp;6.
- [История и биография опросов общественного мнения](files/article_content1205856054347575file.pdf). 2005. №&nbsp;4.
- Смирнова Е. [Рецензия на книгу Г.И. Саганенко «Многообразие возможностей социологического изучения сферы образования»](files/article_content1204299312206228file.pdf). 2005. №&nbsp;2.
- Новинки и бестселлеры по социологии и маркетингу. 2001. №&nbsp;6.
- Новинки и бестселлеры по социологии и маркетингу. 2001. №&nbsp;5.
- [Новинки и бестселлеры по социологии и маркетингу](files/2001_4_10.pdf). 2001. №&nbsp;4.
- [Новинки и бестселлеры по социологии и маркетингу](files/2001-1-11.pdf). 2001. №&nbsp;1.

## Некролог

- [Памяти коллеги](files/2018-5-11.pdf). 2018. №&nbsp;5.
- Докторов Б., Филиппов Г. [Из прошлого ленинградской социологии](files/2018-1-10.pdf). 2018. №&nbsp;1.
- [Памяти Светланы Николаевны Игнатовой (1967-2017)](files/2017-6-08.pdf). 2017. №&nbsp;6.
- [Памяти Андрея Николаевича Алексеева (22 июля 1934 - 29 сентября 2017)](files/2017-5-09.pdf). 2017. №&nbsp;5.
- [Памяти Вячеслава Юльевича Сухачева (12.04.1955 — 10.11.2016)](files/2016-6-09.pdf). 2016. №&nbsp;6.
- [Памяти Бориса Ивановича Максимова (1934-2016)](files/2016-4-09.pdf). 2016. №&nbsp;4.
- [Памяти Игоря Ивановича Травина (1936-2016)](files/2016-3-08.pdf). 2016. №&nbsp;3.
- [Памяти Владимира Эммануиловича Шляпентоха (1926-2015)](files/article_content1478173233464041file.pdf). 2015. №&nbsp;6.
- [Памяти Самуила Ароновича Кугеля (1924 — 2015)](files/article_content1478172349474135file.pdf). 2015. №&nbsp;5.
- [Памяти Владимира Александровича Ядова](files/article_content1477989770469912file.pdf). 2015. №&nbsp;4.
- [Памяти Альберта Васильевича Баранова](files/article_content1476364903264141file.pdf). 2015. №&nbsp;1.
- [Памяти Александра Афанасьевича Клёцина](files/article_content1444125485118236file.pdf). 2014. №&nbsp;2.
- [Памяти Ингрид Освальд](files/article_content144369521871712file.pdf). 2014. №&nbsp;1.
- [Памяти Иосифа Гурвича](files/article_content1443695230119056file.pdf). 2014. №&nbsp;1.
- [Памяти Леонида Наумовича Столовича (1929-2013)](files/article_content1404987516216078file.pdf). 2013. №&nbsp;6.
- [Памяти Т.И. Заславской (1927-2013)](files/article_content140498633153069file.pdf). 2013. №&nbsp;5.
- [Памяти Леонида Евсеевича Кесельмана (1944-2013)](files/article_content1404811234360403file.pdf). 2013. №&nbsp;4.
- [Памяти Юлии Юрьевны Синелиной (1972-2013)](files/article_content1404810110372227file.pdf). 2013. №&nbsp;3.
- [Голод Сергей Исаевич (1935-2013)](files/article_content1404378762151559file.pdf). 2013. №&nbsp;1.
- Докторов Б., Столович Л. [Игорь Кон. Из переписки](files/article_content1356760697151527file.pdf). 2011. №&nbsp;3.
- [Памяти Валентины Федоровны Чесноковой](files/article_content1327768664325060file.pdf). 2010. №&nbsp;4.
- [Памяти Андрея Григорьевича Здравомыслова (1928-2009)](files/article_content1297505208129192file.pdf). 2009. №&nbsp;4.
- [Памяти В.В. Лецовича](files/article_content1205856370291777file.pdf). 2005. №&nbsp;4.
- [Памяти Г. С. Батыгина](files/article_content1197647141406961file.pdf). 2003. №&nbsp;3.
- [Памяти Э. В. Соколова](files/article_content1194856062337462file.pdf). 2003. №&nbsp;2.

## Публикации на разные темы

- Моор В. [Поэтические зарисовки к «афоризмам житейской мудрости» Артура Шопенгауэра](files/2018-6-06.pdf). 2018. №&nbsp;6.
- Докторов Б. [Валерий Голофаст: «...И чудо сделал я». Стихи, хокку](files/2018-3-10.pdf). 2018. №&nbsp;3.
- Алексеев А. [А.Н. Алексеев. Мои пожелания и/или распоряжения](files/2017-6-07.pdf). 2017. №&nbsp;6.
- [Содержание 1 - 6 номеров журнала за 2017 год](files/2017-6-09.pdf). 2017. №&nbsp;6.
- Протасенко Т. [Моя жилищная история: от Читы до Ленинграда](files/2017-5-06.pdf). 2017. №&nbsp;5.
- Божков О. [Не все зависит от нас, особенно жилье](files/2017-2-07.pdf). 2017. №&nbsp;2.
- Илле М. [Журналу «Телескоп» 20 лет!](files/2017-1-02.pdf) 2017. №&nbsp;1.
- Свечников В. [Социальное конструирование виртуальных реальностей: опыт взаимодействия с vip-персонами](files/2017-1-07.pdf). 2017. №&nbsp;1.
- [Содержание 1-6 номеров журнала за 2016 год](files/2016-6-10.pdf). 2016. №&nbsp;6.
- Тайц Д. [Туннель в Европу на Фурштатской зарос чертополохом](files/article_content1478173201226076file.pdf). 2015. №&nbsp;6.
- Божков О. [Об объекте и предмете социологии](files/article_content147696779050656file.pdf). 2015. №&nbsp;2.
- Фетисов В. [Социология: продолжение рефлексии относительно основных понятий](files/article_content1476967802443208file.pdf). 2015. №&nbsp;2.
- Илле М. [Юбилейный номер журнала "Телескоп"](files/article_content1404811085136819file.pdf). 2013. №&nbsp;4.
- Алексеев А. [«Телескоп» — на марше](files/article_content1404811102113417file.pdf). 2013. №&nbsp;4.
- Докторов Б. [«Телескоп»: праздник, который всегда во мне](files/article_content140481111112321file.pdf). 2013. №&nbsp;4.
- Ядов В. [Дибайки для студентов - социологов, или несерьезные заметки о серьезном ](files/article_content140481008778230file.pdf). 2013. №&nbsp;3.
- [Письмо в редакцию](files/article_content1356939446360035file.pdf). 2011. №&nbsp;6.
- [Содержание 1-6 номеров журнала за 2011 год](files/article_content132405027411826file.pdf). 2011. №&nbsp;6.
- Королева Т. [Онлайновый архив Ирвинга Гофмана](files/article_content1328103754153574file.pdf). 2010. №&nbsp;5.
- [Невыключаемое наблюдение](files/article_content1297505718305459file.pdf). 2009. №&nbsp;6.
- Божков О., Дивисенко К. [Электронная база данных Биографического фонда: краткий анализ материалов](files/article_content1215453273491266file.pdf). 2007. №&nbsp;3.
- Москвина В. [Проведение новогодних праздников петербуржцами в 2006 году](files/article_content1218780568485618file.pdf). 2007. №&nbsp;2.
- Ольнова Т. [Комфортность социальной среды в восприятии современных школьников](files/article_content1218780865368113file.pdf). 2007. №&nbsp;2.
- Подушко М. [Рынок маркетинговых исследований Санкт-Петербурга](files/article_content1211646764455279file.pdf). 2006. №&nbsp;6.
- Григорьев В. [Социолог в обществе](files/article_content1210867708271464file.pdf). 2006. №&nbsp;5.
- Дамберг С. [О прагматике российских социологических исследований](files/article_content1209135309184694file.pdf). 2006. №&nbsp;3.
- Григорьев С. [Упоминания высочайших особ как товар (по материалам придворной цензуры)](files/article_content120913543528422file.pdf). 2006. №&nbsp;3.
- Максимов Б. [Когда народ безмолвствует](files/article_content1208530128289041file.pdf). 2006. №&nbsp;2.
- Оберемко О. [Влияние идентификации авторства и жанра на интерпретацию публицистического текста](files/article_content120792210861329file.pdf). 2006. №&nbsp;1.
- Максимов Б. [Новое общественное движение «за иной мир» или всеевропейская тусовка социальных романтиков?](files/article_content1207922238276278file.pdf) 2006. №&nbsp;1.
- Мухортова В. [Формирование идентичности будущих врачей: мотивы выбора профессии](files/article_content1207063197484332file.pdf). 2005. №&nbsp;6.
- Максимов Б. [Рефлексии социолога на проявления быстротекущей жизни](files/article_content120534304283631file.pdf). 2005. №&nbsp;5.
- Француз Ю. [Академическая карьера в США: правила игры и мотивы осуществления](files/article_content1205855713418823file.pdf). 2005. №&nbsp;4.
- Тарасенко А. [История одного успеха: почему некоторым общественным организациям удается участие в законотворческом процессе?](files/article_content120585586031799file.pdf) 2005. №&nbsp;4.
- Лежикова А. [Социальное партнерство: какое оно сегодня, и каким оно может быть завтра](files/article_content1205855968477406file.pdf). 2005. №&nbsp;4.
- Краснов Р., Рылин С. [Корпоративные мероприятия в компаниях Санкт-Петербурга](files/article_content120429940739050file.pdf). 2005. №&nbsp;2.
- Соколов М. [Академический турист как социальный тип](files/article_content1195643995374312file.pdf). 2003. №&nbsp;6.
